### ISSUE TITLE
logger sample fails on qemu_xtensa due to lack of backend

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#10164]
Getting no output on both, see PR #10163 and the CI results.

**Comment by aescolar** [comment]
Regarding the native_posix case:
it was working on: 86442038e94815752ecedf0983cf0a8a64eca04e
it was broken on: 68249ce96622979d000c10c89e5e5192802b931b 
(after merging #9362)

**Comment by nashif** [comment]
> @nashif regarding qemu_xtensa target. It has no logger backends (as uart is the only available).

I am not sure I am following this, why does it need a special logger backend? it was logging just fine with old logger to the console. How is this different from qemu_x86 or qemu_nios2? What logger backends do those have?

**Comment by finikorg** [comment]
qemu uses own UART so it uses usual UART logging backend, @nordic-krch native_posix backend in only for native_posix board configuration.

**Comment by nordic-krch** [comment]
@nashif 
> I am not sure I am following this, why does it need a special logger backend? it was logging just fine with old logger to the console.

It's because new logger does not have (yet?) console backend. It has uart backend. So if target has no uart (or native_posix, or rtt when pr comes) it cannot do logging. We should add console backend but we need to be aware that it is byte API so it will slower than optimized uart backend (current uart backend is polling based, it's poor and needs to be improved as well but at least there is room for improvement).

**Comment by finikorg** [comment]
native_posix should be working fine, I tested several samples, all OK.
