### ISSUE TITLE
Depend on issue in Kconfig template file

### ISSUE THREAD

**Issue by jukkar** [zephyrproject-rtos/zephyr#10178]
I have a networking specific Kconfig template file used in #8816 
My Kconfig template file has this thing setup there
```
choice
	prompt "$(module-str)"
	default $(module)_LOG_LEVEL_WRN
	depends on $(module-dep)
```

I am trying to use the template like this:
```
module=NET_TCP
module-dep=NET_LOG && NET_TCP
module-str=Log level for TCP
source "subsys/net/Kconfig.template.log_config.net"
```
When using `make menuconfig` and when both NET_TCP and NET_LOG are enabled, the logging option is not shown and when searching NET_TCP_LOG_LEVEL in menuconfig, I see this:
```
NET_TCP_LOG_LEVEL(=)
NET_TCP_LOG_LEVEL_DBG(=n) "Debug"
NET_TCP_LOG_LEVEL_ERR(=n) "Error"
NET_TCP_LOG_LEVEL_INF(=n) "Info"
NET_TCP_LOG_LEVEL_OFF(=n) "Off"
NET_TCP_LOG_LEVEL_WRN(=n) "Warning"
```

If I have only one setting in module-dep, then everything works as expected. I would like to use the more complex `depends on` command as it would allow use of only one template file, now I am forced to create multiple template files with different set of dependencies.

**Comment by ulfalizer** [comment]
@jukkar 
This is by design, though designs can be argued. See the 'caveats' section in https://github.com/torvalds/linux/blob/master/Documentation/kbuild/kconfig-macro-language.txt.

`$()` is currently limited to producing (part of) a single token, and can only produce symbol names/strings. This makes sense inside quotes, as you don't want `"foo $(bar) baz"` to break if `$(bar)` expands to something with a `"` in it.

Outside quotes it's more arguable, but the feeling when we discussed it on LKML was that there would usually be a cleaner way to handle those multi-token cases in plain Kconfig. Always producing tokens simplifies the implementation a bit, and could prevent things from turning into the "Wild West" (though the case above isn't that bad).

Would this work?

```
if NET_LOG && NET_TCP

module=NET_TCP
module-str=Log level for TCP
source "subsys/net/Kconfig.template.log_config.net"

endif # NET_LOG && NET_TCP
```

What your code is actually doing is creating a reference to a symbol named `NET_LOG && NET_TCP` by the way, which isn't exactly obvious. The only checking that's done on the generated name at the moment is that it isn't empty.

The same approach could be used to define Make variables with spaces in them too, if you really wanted to, so that's where it came from. Maybe flagging some more things would be nice though...

**Comment by ulfalizer** [comment]
Looks like Make also refuses to create a variable with an empty name:

```make
empty =
$(empty) =
```

gives

```
Makefile:2: *** empty variable name.  Stop.
```

**Comment by ulfalizer** [comment]
Hmm... looks like that doesn't flag an error currently though. The only check is that you don't generate an empty symbol name when expanding a macro.

Expansion probably ought to check that valid symbol names are generated, along with an added check for trying to create a preprocessor variable with an empty name. It's a bit mixed up now. Might be more harmful than useful to allow creating Kconfig symbols with weird names.

That's unrelated to the single-token thing though.

**Comment by jukkar** [comment]
> This is by design, though designs can be argued.

This is unfortunate, it looked like a clean solution.

> Would this work?
> 
> ```
> if NET_LOG && NET_TCP
> 
> module = NET_TCP
> module-str = Log level for TCP
> source "subsys/net/Kconfig.template.log_config.net"
> 
> endif # NET_LOG && NET_TCP
> ```

Sure, that would work of course. It is just that I tried to avoid that in this case :)

Lets close this then as this is not going to work.
