### ISSUE TITLE
Shell: trying to browse history freezes shell on disco_l475_iot1

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#10413]
can be reproduced in samples/subsys/shell/shell_module when built for the disco_l475_iot1, run one command, for example "kernel threads", then try to re-run by pressing up arrow, the shell freezes.

Works fine on nrf boards.

**Comment by zerotri** [comment]
I'm seeing the same thing on stm32f746g_disco as well.

**Comment by jarz-nordic** [comment]
I will take a look this week.

**Comment by erwango** [comment]
Thanks @nashif , reproduced on disco_l475_iot1.
Behavior is slightly different on nucleo_f429zi, shell doesn't freeze, but 'arrow' symbols don't work. Backspace is working correctly, though.

**Comment by erwango** [comment]
I tested this is not an issue specific to STlink VCP.
We face the same behavior when bypassing ST-Link VCP.

`tests/drivers/uart/uart_basic_api` works fine, seems specific to shell implementation of uart service.

**Comment by jarz-nordic** [comment]
@erwango @zerotri @nashif : 
May you please test it with flow control switched on for serial driver?

**Comment by jarz-nordic** [comment]
yes

**Comment by erwango** [comment]
We don't have these pins available on ST-Link VCP.
I can have a try with VCP by-passing but need to find a proper RS232 cable.

That being said, shell seems to be working on frdm_k64f w/o CTS/RTS pins IIUC.

**Comment by jarz-nordic** [comment]
@erwango @nashif : I think I found a bug which can pop up when flow controll is off. If you will notice that shell has hanged please press capital `A`. :-)

I will submit PR shortly.

**Comment by jarz-nordic** [comment]
@erwango : I have disco_l475_iot1 on my table and I confirm observed issue.
However I am not sure it is related with the shell. It looks more like a driver issue to me.

I am debugging application with gdb. Once shell is frozen with an arrow, function `uart_stm32_poll_in` is always returning `-1` despite the fact I am typing characters.

**Comment by jarz-nordic** [comment]
@erwango @carlescufi  @nashif 
I found a root cause and I know how to fix it :)
Basically there is a weakness of ST UART driver, it is not handling overrun error. When this error occurs driver always returns that there is no new data received. According to ST specification:

>  if RXNE=0, then it means that the last valid data has already been read and thus there is
> nothing to be read in the RDR. **This case can occur when the last valid data is read in the**
> **RDR at the same time as the new (and lost) data is received.** 

Bolded case is not handled by ST UART driver.

I've prepared my fix for that by adding a function `LL_USART_ClearFlag_ORE(UartInstance);`. When I tested it shell is not freezing anymore:

```
if (!LL_USART_IsActiveFlag_RXNE(UartInstance)) {
		LL_USART_ClearFlag_ORE(UartInstance); /* This line fixes the problem */
		return -1;
	}
```

Unfortunately when serial driver is working in polling mode some characters are still lost so history will not work on ST board. However there is PR prepared by @nordic-krch (PR #10923) which is solving this problem. Serial RX is moved to be interrupt driven and received data is collected in a ring buffer. I tested it with disco board and history is working fine there.

**Nevertheless ST needs to improve serial driver to handle overrun error.**
