### ISSUE TITLE
tests/kernel/interrupt is failing on NRFx boards

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#10509]
Commit: 2a103ea67493ebcae5c5d7720f6e1a38a05faff1

Execution log:
```
**** Booting Zephyr OS 1.13.99 (delayed boot 1000ms) *****
Running test suite interrupt_feature
===================================================================
starting test - test_nested_isr
Triggering irq : 37
isr0 running !!
isr0 execution completed !!

    Assertion failed at zephyr.git/tests/kernel/interrupt/src/nested_irq.c:46: isr0: (new_val not equal to old_val)
Nested interrupt is not working

Triggering irq : 36
isr1 ran !!
FAIL - test_nested_isr
===================================================================
starting test - test_prevent_interruption
PASS - test_prevent_interruption
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

Platforms tested: nrf52_pca10040, nrf52840_pca10056

**Comment by nashif** [comment]
@kumarvikash1 please make sure @ajaykish sees that

**Comment by kumarvikash1** [comment]
@nashif , i have informed @ajaykish . I am not sure, why issues are not getting assigned to him.

**Comment by ajaykish** [comment]
Looks like due to low power 32 KHz timer in nrf board, we are not achieving the required sequence.
Expected log from this test:
 Triggering irq : 84
 isr0 running !!
 Triggering irq : 83
 isr1 ran !!
 isr0 execution completed !!
 PASS - test_nested_isr
 
 But in nrf board, once isr0 (low priority interrupt) starts execution with busy wait,
 isr1 (high priority interrupt) is not getting triggered meanwhile. 
 Same test is passing with other platforms.

@carlescufi could you please comment on this issue.
