### ISSUE TITLE
[Coverity CID :188890]Insecure data handling in /drivers/watchdog/wdt_qmsi.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#10750]
Static code scan issues seen in File: /drivers/watchdog/wdt_qmsi.c
 Category: Insecure data handling
 Function: get_timeout
 Component: Drivers
 CID: 188890
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by maxxlife** [comment]
@nashif Hi. Do you think that it is a good idea to fix that defect by writing a new function sat_subtract and perform a saturating subtract?
As I understand the issue is `count - 1` and its ability to underflow if `count=0`.

Please check my code idea prototype for that fix:
`extern int sat_subtract(u32_t a, u32_t b);`
`inline sat_subtract(u32_t a,  u32_t b)`
`{`
	`return ((a > b) ? (a - b) : 0);`
`}`
`static u32_t get_timeout(u32_t  timeout)`
`{`
`u32_t count = 0U;`
`return sat_subtract(count,1U);`
`}`
