### ISSUE TITLE
Can we sort the board docs alphabetically?

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/zephyr#10834]
Is it possible to have:

https://docs.zephyrproject.org/latest/boards/arm/index.html

Sorted alphabetically?

**Comment by dbkinder** [comment]
Actually, they are currently sorted... by filename but showing the doc title in the list.  So the unexpected order of titles such as:

- Arduino/Genuino Zero
- SAM D20 Xplained Pro Evaluation Kit
- SAM D21 Xplained Pro Evaluation Kit
- BBC MicroBit

is because the "SAM" document files are called ``atsamd20_xpro`` and ``atsamd21_xpro`` which nicely sort into the list at the end of the A's.

To fix this, we need to rename the board doc filenames consistent with the name of the board (and be consistent with the doc titles to always start with, for example, the manufacturer name.  For example, the title "ARM V2M Beetle" in file v2m_beetle.rst should be "V2M Beetle" (without "ARM" at the beginning).

So, this seems to be mostly a file renaming effort to get the file name constent with the doc title, plus tweaking a few doc titles to start with the manufacturer name (and not just the board name or the architecture).
