### ISSUE TITLE
Missing stm32l433.dtsi file

### ISSUE THREAD

**Issue by markusr** [zephyrproject-rtos/zephyr#10909]
I am trying to get a custom board with the STM32L433 running.
However, it seems that the ```<st/l4/stm32l433.dtsi>``` defined in  ```dts/arm/st/l4/stm32l433Xc.dtsi``` is missing.

@galak Can you take a look? Since you were the last to change these files.

**Comment by galak** [comment]
At a quick look it doesn't seem like we've ever had a board that uses STM32L433 in the tree, thus the issue you are running into.

@markusr I see two solutions:

1. You contribute the missing file (or maybe @erwango will)
2. We remove dts/arm/st/l4/stm32l433Xc.dtsi since its not used

Option 2, means you get all the fun :).

Thoughts?
