### ISSUE TITLE
MISRA C Do not use recursions

### ISSUE THREAD

**Issue by ceolin** [zephyrproject-rtos/zephyr#11425]
MISRA-C does not allows that a function call themselves, either directly or indirectly. Currently there is only one spot in Zephyr doing it  `_rb_walk()`.

rule 17.2

part of: #9552

**Comment by andyross** [comment]
MISRA exists just to make my life miserable, doesn't it?

(FWIW: I know of at least one other in mempool, though that one is proper tail recursion and maybe MISRA has an exception for that?)

Yeah, I'll take it.  FWIW: there is a non-recursive walker (a FOREACH kind of thing), but it's got significantly higher code size.

**Comment by ceolin** [comment]
it does feel to be in my shoes :)

Yeah, I'm sorry for that, I know that not using recursion here will increase and make it more complicated.

**Comment by pfalcon** [comment]
> MISRA exists just to make my life miserable, doesn't it?

Everyone's.

> proper tail recursion and maybe MISRA has an exception for that?

I'm sure tail recursion doesn't exist in MISRA's world. And speaking seriously, C doesn't guarantee tail-recursive optimization, so... just don't tell anyone there's another func like that ;-).

**Comment by andyross** [comment]
Actually looking at this more carefully, this should be doable for 1.14.  The two spots I know of are rb_walk above, and a tail recursion case in mempool.  The latter can be turned into iteration with 2-3 lines of code and an extra level of indentation, and it turns out the former is in fact no longer used in the tree beyond the test case (I needed it in the scheduler at one point, but I don't think that usage ever even merged).   Will submit a patch.

**Comment by andyross** [comment]
Merged the recursion patch.  Closing.
