### ISSUE TITLE
	How to build images for client or server in bluetooth mesh examples?

### ISSUE THREAD

**Issue by zzzh** [zephyrproject-rtos/zephyr#12228]
I noticed that in these examples, there's only one main.c file, and only one image file would be built, it can support different hardware, but seems not different roles?
Bluetooth Mesh is supposed to be run in different roles, right?
If one image is enough, how to set it for different roles?

**Comment by jhedberg** [comment]
It's up to you as the application writer to decide what models your node will have. It can have both server and client models (which to some extent are a bit arbitrary since both send and receive messages with the only difference being in who initiates sending request-style messages that the receiver responds to). You could e.g. have a node with buttons mapping to the Generic On/Off Client model and LEDs mapping to the Generic On/Off Server model. Who these models send messages to or receive messages from depends on how you configure your nodes using a Configuration Client Node (often the same device that performs provisioning of your mesh network).

**Comment by ioannisg** [comment]
@zzzh please, re-open if needed, to continue discussion
