### ISSUE TITLE
BLE400 / nRF51822 (nRF51) PWM clock too low (servo-motor example)

### ISSUE THREAD

**Issue by tg--** [zephyrproject-rtos/zephyr#12239]
I'm trying to use the "servo-motor" example to control a servo with my BLE400 using a Core51822 module and the nRF5 software PWM implementation.

Unfortunately it does not work.
I measured with a signal analyzer on the GPIO/PWM pin and I'm seeing pulsewidths of only 8.1 ms maximum, despite the code being set to about 20 ms (and I tried higher values as well).

It seems a 125 kHz clock is used (the prescaler is set to 16 MHz by default), which would explain the permanent 8.1 ms. It's possible to go lower, but no higher.

Can anyone confirm or explain this, or am I missing something?

**Comment by carlescufi** [comment]
@cvinayak could you please take a look?

**Comment by gamnes** [comment]
Hi @tg--, I just tested servo-motor example from master branch on a bbc_microbit board, and I can successfully set for example:
if (pwm_pin_set_usec(pwm_dev, 3, PERIOD, 15000)) {
In main and measure roughly 15ms on P0 (P0.03 on the nRF51822). 

The prescaler option for my setup is the default as set in master branch;
CONFIG_PWM_NRF5_SW_0_CLOCK_PRESCALER=3
This should give a clock of: 16M / (2^PRESCALER) = 16M / 16 = 1M. 

Can you please check your settings, and if they are correct, I will need some more information in order to help you as I am not seeing the same issue on my side.

**Comment by overheat** [comment]
@tg-- I have add hw pwm for nrf52 chips. #14853 Do you have time to review it?

**Comment by gamnes** [comment]
I think this issue can be closed now, @tg-- ?
