### ISSUE TITLE
File descriptors: Compile fails with non-POSIX out-of-tree libc

### ISSUE THREAD

**Issue by mped-oticon** [zephyrproject-rtos/zephyr#12368]
`lib/CMakeLists.txt` has a hard dependency on `zephyr_sources(fdtable.c)`.
`fdtable.c` in turn always includes `fcntl.h`.
`fcntl.h` is defined by POSIX.
Zephyr provides it with minimal libc: `zephyr/lib/libc/minimal/include/fcntl.h`.

We use a custom libc that does not have `fcntl.h`, so we must hack around this.

It seems there are two solutions:

1. Make the compliation of `fdtable.c` conditional on POSIX. But it appears `subsys/net/lib/sockets/sockets.c` makes use of the Zephyr-specific functions, beyond the POSIX ones.
2. Make inclusion of `fcntl.h` conditional on `CONFIG_POSIX_API`.

Please advise which is preferrable.

**Comment by SebastianBoe** [comment]
@aescolar : FYI

**Comment by pfalcon** [comment]
> Zephyr provides it with minimal libc: zephyr/lib/libc/minimal/include/fcntl.h.

> We use a custom libc that does not have fcntl.h, so we must hack around this.

And the best option would be to make a minimal fnctl.h. Looking at zephyr/lib/libc/minimal/include/fcntl.h , you'll see how minimal it should be indeed.

**Comment by pfalcon** [comment]
> Make the compliation of fdtable.c conditional on POSIX
> Make inclusion of fcntl.h conditional on CONFIG_POSIX_API

fdtable.c doesn't depend on POSIX, that's the reason it lives in lib/, not lib/posix/ . It's used by other subsystems beyond pure "POSIX layer". E.g., it's used by BSD Sockets API. To summarize current API design in Zephyr, we have:

1. Native Zephyr API, adhoc and proprietary. Its design oftentimes leaves much to be desired, that's why we constantly refactor it (either breaking it, or going thru acrobatics to not break it).
2. APIs inspired by POSIX, but following its spirit, not word. BSD Sockets API implementation (as of now) is such. fdtable is another example of such (meta-)API.
3. A POSIX API layer, which aspire to implement the API compliant by the word, not just by spirit, of POSIX, which lives in lib/posix/. Of course, it depends/supposed to depend on other parts of Zephyr, including those of p.2. (E.g. one sweet day Sockets API would be "fully" POSIX compliant (hopefully by a config var)).

So, that's once axis.

Another axis are bare-metal vs on-top-of-another-OS Zephyr targets. A critical case is when we try to implement Zephyr's POSIX on top of underlying POSIX OS. native_posix is such. Currently, it's something like fragile house made of cards - put together with a lot of pain already, and falling apart on any change. It's an open question how to deal with that.

**Comment by pfalcon** [comment]
> https://github.com/zephyrproject-rtos/zephyr/issues/12368#issuecomment-452263818

>  pfalcon commented 16 minutes ago •
> edited by mped-oticon

@mped-oticon, something weird has happened there. You seemed to have edited my comment, so now your words are in the comment signed by my name.

**Comment by pfalcon** [comment]
So skipping paradigmatic discussions that in general, it's not possible to tear a part of one software project, tear a part from another, put together, and expect it to work (for example, Zephyr supports 2 libc: newlib (specific version its SDK ships with) and minimal), there's a range of ways to solve this particular issue.

From (the most lazy, thus will fire back later again):
~~~
        /* Handle fdtable commands. */
        switch (cmd) {
+       #if 0
        case F_DUPFD:
                /* Not implemented so far. */
                errno = EINVAL;
                return -1;
+       #endif
        }
~~~

To (the most right): make fdtable.c compilation conditional on a hidden config symbol, and make existing subsys'es which depend on fdtable.c SELECT that symbol. Then you'll be able to build Zephyr against libc's which don't provide fcntl.h, unless you enable Zephyr features which depend on fcntl.h themselves.

**Comment by mped-oticon** [comment]
> > [#12368 (comment)](https://github.com/zephyrproject-rtos/zephyr/issues/12368#issuecomment-452263818)
> 
> > pfalcon commented 16 minutes ago •
> > edited by mped-oticon
> 
> @mped-oticon, something weird has happened there. You seemed to have edited my comment, so now your words are in the comment signed by my name.

You are right, Sorry! I clicked wrong. How about I delete this wonky comment to avoid confusion? It appears your later comments do not refer to this.

**Comment by pfalcon** [comment]
> How about I delete this wonky comment to avoid confusion?

That's probably the worst solution ;-). The easiest one is just to leave it as is, as it quotes my previous reply, so no discussion is lost per se. "Fully right" solution would be restore my comment as it was, and post yours as a separate one, but not worth spending time on that imho, let's better discuss proposed ways to resolve the actual issue.
