### ISSUE TITLE
add test to catch issues fixed in PR  #12384

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#12405]
Add a test that would catch the issue fixed in #12384

**Comment by nashif** [comment]
@LeiW000  @enjiamai  do we have test coverage for this?

**Comment by enjiamai** [comment]
@nashif  ,  do you mean which test case cover it?
![image](https://user-images.githubusercontent.com/9374762/120028260-07ad7d80-c027-11eb-8cab-2a3f958754e0.png)

**Comment by enjiamai** [comment]
Hi @nashif  we have the poll tests that cover this, I think it could be closed.

**Comment by nashif** [comment]
> Hi @nashif we have the poll tests that cover this, I think it could be closed.

This is not exactly test coverage. The issue was that is_polling was set to true, and the test still passed, see the original commit in #12384

**Comment by enjiamai** [comment]
> > Hi @nashif we have the poll tests that cover this, I think it could be closed.
> 
> This is not exactly test coverage. The issue was that is_polling was set to true, and the test still passed, see the original commit in #12384

Got your point. After checking, it cannot be caught by the current testcases. Ok, we will do it soon.

**Comment by cfriedt** [comment]
@LeiW000 , @Zhaoningx - any progress on this?

**Comment by LeiW000** [comment]
@Zhaoningx is going to work on it next week. Now he is busy on another urgent issue.

**Comment by Zhaoningx** [comment]
Hi @nashif , the code changed a lot after #12384, and I spent some time to understand if the code `poller.is_polling = false` makes sense. The code as below:
![image](https://user-images.githubusercontent.com/62736294/128047409-bc1add4c-e9b2-4b72-9c31-cf9fb8011ad7.png)

The bool value is_polling is used to judge the event is existing or not in k_poll function, in the function signal_poll_event, it seems it's not working to set the poller value, because if a event is fulfilled successfully, the event will be reset to NULL,also reset is_polling, if failed, a negative value will be returned and the thread of called k_poll function will don't callback. So @nashif , do you think the code of signal_poll_event make sense?

**Comment by Zhaoningx** [comment]
Hi @nashif , the code changed a lot after PR #12384, and I spent some time on this, and try to design testcase to detect is_polling value. But didn't work, in my opinion, it seems the is_polling is used in the main function k_poll to decide whether need to register an event and polling it, the value of is_polling that we want to detect is in signal_poll_event function, as you know, this function is used to fulfill an event and wake up k_poll thread callback. If successful, the event will be set to NULL whatever is_polling is true or false. If failed, it means the thread of k_poll expired, and k_poll thread will not wake up and callback. It seems the is_polling in signal_poll_event function can control nothing. I don't know how is_polling of signal_poll_event can control whether to poll and how it can be detected. So I would like to ask @nashif for help to comment here. Thanks.

**Comment by Zhaoningx** [comment]
Hi @nashif , could you take a look at this, thanks very much.
