### ISSUE TITLE
ble-mesh: How can I make my android phone as a Provisioner

### ISSUE THREAD

**Issue by wayen30** [zephyrproject-rtos/zephyr#1274]
I want to test ble-mesh. Beacause the ble mesh in zephyr does not support provisioner, I will do it with a ble board and a android phone. Is there a apk which can make the android phone as a provisioner?

Thanks!

**Comment by jhedberg** [comment]
There's an app from Silicon Labs that you should be able to use. Note that it only supports PB-GATT (since Android's BLE APIs are not suitable for PB-ADV). There's a link to this app in the blog post that I recently wrote: https://www.zephyrproject.org/community/blog/announcing-bluetooth-mesh-support-zephyr-project
