### ISSUE TITLE
openthread: sleepy end device not supported by zephyr router

### ISSUE THREAD

**Issue by turon** [zephyrproject-rtos/zephyr#12942]
When using a zephyr router, a sleepy end device (SED) can attach fine, but ping doesn't work.
We suspect that the frame pending bit isn't being supported correctly.

@rlubos

**Comment by rlubos** [comment]
> We suspect that the frame pending bit isn't being supported correctly.

You are right here, the whole frame pending API specified by OpenThread is not implemented in Zephyr:

The API is specified here:
https://github.com/openthread/openthread/blob/5b4e7f93315010bf504da49ba61f1c5bf7f56279/include/openthread/platform/radio.h#L609

And here are Zephyr's empty stubs:
https://github.com/zephyrproject-rtos/zephyr/blob/c39bb49e8458fd6548711ee01bd1fafe4ffa2e95/subsys/net/lib/openthread/platform/radio.c#L303

The difficult part here is that Zephyr's 802.15.4 driver API does not support such functionality (unless I miss something), so it needs to be extended first. I don't see other option, as we do support HW ACK sending - therefore we need a way to inform the radio whether to set frame pending bit or not.

**Comment by turon** [comment]
@carlescufi why is the priority low for this?  SED behavior is a critical feature of Thread, and it is mandatory in order to certify a Thread router.

**Comment by rlubos** [comment]
@turon Two PRs were submitted, introducing Sleepy End Device support into Zephyr: #15552 and #15685.

There's no out-of-the-box sample that implements SED yet, I'm thinking about adding an overlay for the `echo_client` that'd configure a SED device. Just note, that when configuring SED in Zephyr, one should avoid setting a custom IPv6 address with the Mesh Local prefix, otherwise it breaks the address registration procedure of the MTD child (see [this](https://github.com/openthread/openthread/pull/3640#discussion_r261723931) discussion).

**Comment by turon** [comment]
@rlubos Thanks for the update.  So when your changes are merged, will that allow a Zephyr router to accept and support an openthread cli SED?  That is the configuration I was testing with.

**Comment by rlubos** [comment]
@turon Yes, the scenario you describe should be fixed by #15685, which fixes the parent (router) side. #15552 on the other hand fixes the child part, allowing SEDs to be created with Zephyr.
