### ISSUE TITLE
CONFIG_BT leads Fatal fault in ISR on esp32

### ISSUE THREAD

**Issue by lilrom13** [zephyrproject-rtos/zephyr#13065]
**Describe the bug**
Add `CONFIG_BT=y` leads a `Fatal fault in ISR! Spinning...` on esp32.

**To Reproduce**
add `CONFIG_BT=y` to prj.conf
also reproducible with beacon sample

1. cd build/
2. cmake -GNinja -DBOARD=esp32 ..
3. ninja
4. cd ..
5. west -v flash -d build/ --skip-rebuild --esp-device /dev/tty.SLAB_USBtoUART

`** FATAL EXCEPTION
 ** CPU 0 EXCCAUSE 3 PS 0x00060020 PC 0x40082a23 VADDR 0x400805f8
 **  A0 0x80082a4e  SP 0x3ffb2cd0  A2 0x400805ec  A3 0x00000000
 **  A4 0x00000001  A5 0x3ffb4570  A6 0x3ffb2034  A7 0x00060d23
 **  A8 0x80082a0d  A9 0x3ffb2ca0 A10 0x00000000 A11 0x00000000
 ** A12 0x00000000 A13 0x3ffb4550 A14 0x00000000 A15 0x00000000
 ** LBEG 0x00000000 LEND 0x00000000 LCOUNT 0x00000000
 ** SAR 0x00000000
Current thread ID = 0x3ffb2034
Faulting instruction address = 0xdeaddead
Fatal fault in ISR! Spinning...
`

**Environment (please complete the following information):**
 - OS:  MacOS
 - Toolchain: ESP-IF

**Comment by jhedberg** [comment]
@galak I'm not at all familiar with esp32, and don't have any such HW. In fact, I didn't even realize we supported Bluetooth on it, so I'm not sure what I can do about this issue.

@lilrom13 how is Bluetooth supposed to work on your board? E.g. which HCI driver are you using?

**Comment by nashif** [comment]
bluetooth not supported on this platform.

**Comment by WilliamGFish** [comment]
@nashif 
Interesting article was published on how the Expressif team have released their version of BLE Mesh which has been built on top of Zephyr (as below).

It might be worth a conversation to see if they are willing to contribute to the overall Zephyr code base.

https://www.espressif.com/en/news/Espressifs_BLE_Mesh_SDK_Is_Now_Bluetooth_SIG_certified

**Comment by jhedberg** [comment]
@WilliamGFish thanks for pointing out the Espressif Mesh SDK. I'm happy proper credit is given to the Zephyr stack, since it's something that doesn't always happen in situations like this. From a quick look the main thing that might be worth looking at for Zephyr is the provisioner support since it's something we don't have. It looks like there might be some standard models code we could benefit from as well. Besides that, I wouldn't expect there to be much to port qualification-wise, since we do run all the relevant tests periodically, despite not having a formal qualification listing for the mesh stack.

**Comment by EddLeon** [comment]
@nashif Is there any future plan to support Bluetooth?
