### ISSUE TITLE
frdm_kl25z samples/basic/threads Kernel Panic

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#13463]
**Describe the bug**
frdm_kl25z samples/basic/threads Kernel Panic

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=frdm_kl25z  ..
3. make

**Expected behavior**
thread switch shall be working

**Impact**
1. the gpio setting is not platform independent

**Screenshots or console output**
```
***** Booting Zephyr OS 1.14.0-rc1 *****

ASSERTION FAIL [gpio_dev != ((void *)0)] @ /build/src/workspace/frdmkl25z_master-32BQPWFMHJHABGVMBAYRTODCAVUIGXJ6WJT3NCXTALMIGKHHKJ6A/samples/basic/threads/src/main.c:50

***** Kernel Panic! *****

Current thread ID = 0x1ffff000

Faulting instruction address = 0x1110
```

**Environment (please complete the following information):**
 - OS:  Linux
 - Toolchain  Zephyr SDK
 - Commit SHA or Version used
v1.14.0_rc1

**Comment by hakehuang** [comment]
@MaureenHelm

**Comment by overheat** [comment]
Hi hakehuang,

I have the same issue with you, and the only difference is that it happened on my pca_10056 board, which is an nRF52840 chipset on it.

Have gone through the code and document, the problem is in the GPIO driver missing on my Nordic pca_10056 board and maybe same on your board. As a result of this, the gpio driver didn't been linked, and a fault happens when you try to invoke it. 

There are two ways to solve this problem:
1. use " ninja menuconfig " and enable "GPIO Drivers" under "Device Drivers".
2. add "CONFIG_GPIO=y" to the end of  zephyr\samples\basic\threads\prj.conf, and re-build it!

Can you test it? I hope everything goes well!

**Comment by MaureenHelm** [comment]
> I have the same issue with you, and the only difference is that it happened on my pca_10056 board, which is an nRF52840 chipset on it.

Thanks @overheat for jumping in on this! Turns out it was a slightly different issue on the frdm_kl25z board, so your patch doesn't quite fix it.

**Comment by overheat** [comment]
> > I have the same issue with you, and the only difference is that it happened on my pca_10056 board, which is an nRF52840 chipset on it.
> 
> Thanks @overheat for jumping in on this! Turns out it was a slightly different issue on the frdm_kl25z board, so your patch doesn't quite fix it.

Thank you for your explanation.  Since I don't have frdm_kl25z board, I double checked it with "ninja menuconfig" under frdm_kl25z environmental. 
Yes, you are right. It a different issue even the console output is almost the same, cause the gpio driver already enabled for frdm_kl25z . So it looks like another issue for my Nordic's boards. I will re-submit it with a more proper description.
