### ISSUE TITLE
k_sleep() expires sooner than expected on STM32F4 (Cortex M4)

### ISSUE THREAD

**Issue by avisconti** [zephyrproject-rtos/zephyr#15216]
**Description**
I'm adding support for a new sensor shield (shield-iks01a3) which should be plugged
on Nucleo board (for example F411RE, which is based on Cortex M4).
I have a sample thread that reads sensor data every 2 secs using a k_sleep().
The sensors are  programmed to generate triggers at 100hz or 200hz.
I see that k_sleep() very often takes less than 2secs.

I opened a PR (#15024) with a temptative fix that make disappear the issue.
My observation is that there is a much higher rate of z_clock_set_timeout() calls with 
last_load < CYC_PER_TICK. If I force last_load to be at least CYC_PER_TICK the issue
again disappear.

**To Reproduce**
I'm currently not able to reproduce it w/o a proper h/w.
Only using Nucleo board plus x_nucleo_iks01a3 shield.
I can try to find an easy way.

**Expected behavior**
k_sleep() should wait the proper amount of time in all conditions.

**Impact**
Bug is annoying but not really severe for my development.

**Screenshots or console output**

**Environment (please complete the following information):**
 - OS: linux
 - Toolchain (e.g Zephyr SDK, ...)
 - latest code

**Additional context**

**Comment by andyross** [comment]
So... the bug that I thought I saw during review of the first patch turned out to not be one.  But on careful reflection I found a situation that could potentially be causing the behavior you're seeing.

While as explained, a LOAD value set to less than one tick is normal and desired, the driver was allowing VERY small LOAD values to be set (as low as 512 cycles), which create problems if you are running a busy app doing lots of interrupt masking for 512+ cycles.   The patch in #15219 adjusts the defaults a little, and also cleans up the code to be able to handle multiple-wraparounds-while-interrupt-is-masked conditions more gracefully.  Can you try it?
