### ISSUE TITLE
problem with pci_bus_scan resulting in an endless loop

### ISSUE THREAD

**Issue by eyuval** [zephyrproject-rtos/zephyr#1550]
I am using the standard paradigm for calling pci_bus_scan in a loop until it returns 0. However, in my scenario I  have several bars and I am hitting the condition 	'if (lookup.barofs >= max_bars)' at the end of pci_dev_scan, which resets the barofs and baridx for lookup.  What happens then, is that my pci_bus_scan loop simply restarts with bar 0 of the same device in an endless loop.

**Comment by nashif** [comment]
@dcpleung since you are looking at PCI now, can you look into this and see if it is valid and if it can be fixed?

**Comment by dcpleung** [comment]
For this behavior to manifest, the input parameter must have contained PCI_BAR_ANY, which will give you any BAR the pci_bus_scan() (and thus pci_dev_scan()) can find. Moreover, the current design does not guarantee a later call to pci_dev_scan() in the same thread will continue from previous call. For example, if another thread is scheduled and pci_dev_scan() is called, the global lookup struct will probably be changed.

So, in order to achieve the behavior to "scan until all BARs have exhausted", it requires re-working the flow to do external state tracking (e.g. having lookup struct per thread). The changes will not be trivial.

**Comment by dcpleung** [comment]
Took a look at it more. The currently pci_dev_scan() does not necessarily give you BAR #0 the first time it is called on a device/func pair. If the function is previously used, the internal struct is changed. So, for example, calling this function again with PCI_ANY_BAR may give you BAR #3 instead of #0.
