### ISSUE TITLE
flash: unify read alignment requirements

### ISSUE THREAD

**Issue by nvlsianpu** [zephyrproject-rtos/zephyr#16439]
### Problem to be covered:
Flash read API implementation have different requirement regards read-out offset and read-out length. These requirements are not precised by any API description.

Most of drivers allow unaligned read,. One driver enforce aligned access in terms on offset and length. One driver requires aligned offset only.

Problem with this diverse behavior cause unwanted complication in upper layer in order to adapt to what any flash driver supports. It cause for instance issue described here: #16438

### Solution:
Sufficient: At last make each driver capable to read unaligned length of data. Better if unaligned offset will be ensured for any driver.

#### Current state of flash drivers `read access requirement`:
(pleas correct here if I missed something)

QMSI has requirement for 4 B alignment of offset and length.
NIOS2 has requirement for 4 B alignment of offset.
NRF, MCUX, Geco, STM, SAM, SPI-NOR, w25qxxdv are capable of unaligned readout

**Comment by carlescufi** [comment]
Conclusion: `flash_read()` users should be able to use any address and length, aligned or unaligned.

@nashif can you see if the owners of QMSI and NIOS2 could add software emulation for unaligned reads?

**Comment by nvlsianpu** [comment]
@ramakrishnapallala  Are you able to align NIOS2 driver? Saw that you contribute it.

**Comment by nvlsianpu** [comment]
> @nashif  can you see if the owners of QMSI and NIOS2 could add software emulation for unaligned reads?
@nasthif ping
I want to act on API requirement change in order to solve this issue.

**Comment by d3zd3z** [comment]
Unlike writes, it should always be safe for the driver to read more data is then only return the data the user has requested. I think this change is a good idea.

**Comment by nvlsianpu** [comment]
QMSI driver was droped.
NIOS2 driver haw been improved

**Comment by d3zd3z** [comment]
> Unlike writes, it should always be safe for the driver to read more data is then only return the data the user has requested.

I should clarify this a bit, because it isn't quite true. It should be safe to read more data, up to the size of the read alignment. For example, a device that has 32-bit internal reads, and uses an ECC to protect those will always be safe to read a full 32-bits. But, if the driver were to read 64-bits from this device, it could receive an error on the second 32-bits if it hadn't been written.

Devices do not behave the same as far as reads from unwritten flash. Most seem to return a consistent pattern (all 1s or all 0s), but at least one, the LPC55S69, will bus-fault. #25206 attempts to make read more consistent on this device, but it will still return `-ENODATA` on unwritten data, or just `-EIO` if it isn't erased (which it would do for a larger read). This device has a write-granularity of 512, so 32-bit reads should always be safe.

So, I think this is safe to round the reads up, but we have to be careful about the size of the reads we do, and that we don't make them larger than the underlying write granularity of the device.
