### ISSUE TITLE
x86_64 crash with spinning child thread

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#17170]
**Describe the bug**
This is possibly related to #17167 but in this case, we are not running anything in user mode (no support on that platform). Instead what we are doing is setting the main thread to a cooperative priority, launching a preemptive child thread that hogs the CPU, and the system hangs when the parent thread goes to sleep.

**To Reproduce**
Grab this patch:
https://github.com/andrewboie/zephyr/commit/065678408b8c33f115c6c3894eed84a14a28d454

And run the hello_world sample.

**Expected behavior**
On qemu_x86 this completes as expected:

```
Booting from ROM..***** Booting Zephyr OS build zephyr-v1.14.0-1926-g4ce2753e6e3b *****
Hello World! qemu_x86
Child thread spinning...
SUCCESS
```

On x86_64 it just hangs:

```
Booting from ROM..Hello World! qemu_x86_64
```

**Impact**
Seems like a showstopper, this ought to work.

**Comment by andyross** [comment]
Bug was with k_thread_priority_set() on SMP assuming that it could unconditionally remove the thread from the run queue.  On SMP, the current threads aren't in the run queue.  Wasn't discovered because while we do have tests that call k_thread_priority_set(k_current_get(), ...), they're running with SMP disabled currently :(
