### ISSUE TITLE
Cmsis_rtos_v2_apis test failed on iotdk board.

### ISSUE THREAD

**Issue by chen-png** [zephyrproject-rtos/zephyr#17852]
**Describe the bug**
The cmsis_rtos_v2_apis test failed on iotdk board, we found that it will occur "Zephyr fatal error 2: Stack overflow" when running cmsis_rots_v2_apis test.

**To Reproduce**
1. source zephyr-env.sh
2. west build -b iotdk -p=auto tests/cmsis_rtos_v2
3. screen /dev/ttyUSB0 115200
4. west flash

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/52983984/62096188-654ed280-b2b5-11e9-88c0-909401b7812f.png)

**Environment (please complete the following information):**
 - OS: Fedora28
 - Toolchain: Zephyr SDK
 - Commit ID: e806bd977955

**Comment by IRISZZW** [comment]
This exception caused by violation stack memory access, as arc hardware stacking has been enable by default.

in function osThreadGetStackSpace called in <zephyr_root>/tests/cmsis_rtos_v2/src/thread_apis.c line 87, it will read from the unallocated stack region, which is not allowed.

you can disable arc hardware stacking use menuconfig.
(Top) → ARC Options → ARCv2 Family Options

![image](https://user-images.githubusercontent.com/16890595/62213953-a7236a00-b3d6-11e9-832f-f50dbf27001b.png)

Then rebuild and run.

**Comment by chen-png** [comment]
@IRISZZW Yes, you are right. I add one line in the zephyr/tests/cmsis_rtos_v2/prj.conf, 
        +    CONFIG_ARC_HAS_STACK_CHECKING=n
and then the issue has been solved.

**Comment by ioannisg** [comment]
@vonhust will you be able to take a look?

**Comment by maksimmasalski** [comment]
@vonhust Are you working on that issue?
