### ISSUE TITLE
devicetree: support multiple values in io-channels

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#18352]
The `io-channels` property was added in #18101 but the implementation doesn't seem to support multiple channels, although edtlib internal documentation suggests it should.

For example, I should be able to define a bank of ADC inputs corresponding to thermistors with something like
```
thermistor-bank {
	compatible = "voltage-divider";
	io-channels = <&adc 1>, <&adc 2>, <&adc 4>;
	output-ohms = <10000>;
};
```
Currently this produces multiple definitions for the same symbol.  I also tried:
```
io-channels = <&adc 1 &adc 2 &adc 4>;
```
with the same result, though edtlib seems to handle something similar for `foo-gpios`.

See [this example](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/arm/boot/dts/aspeed-bmc-opp-zaius.dts?h=v5.3-rc4#n111).

**Comment by ulfalizer** [comment]
@pabigot 
Could check what `write_iochannels()` does in `gen_defines.py`, and compare it against `write_gpios()`. Honestly, I don't know what output the code expects for all of these, so I might not be the best person to change it. :P

It's made to be easy to tweak at least. `gen_defines.py` decides what the output is, while edtlib is general.

**Comment by ulfalizer** [comment]
Maybe @jimparis has opinions.

**Comment by ulfalizer** [comment]
Re. `io-channels = <&adc 1>, <&adc 2>, <&adc 4>;` vs. `io-channels = <&adc 1 &adc 2 &adc 4>;`, they're treated exactly the same, and generate the same output with the devicetree compiler as well.

I added support for the first form in the type checker even though it's redundant, because it felt a bit mean to disallow something people probably do because they care about trying to make things readable.
