### ISSUE TITLE
Bluetooth: Mesh: Friend Clear Procedure Timeout

### ISSUE THREAD

**Issue by menglingao1997** [zephyrproject-rtos/zephyr#19263]
https://github.com/zephyrproject-rtos/zephyr/blob/99e935e2ba740c309d43a3608352e6bce494662e/subsys/bluetooth/mesh/friend.c#L647-L673

may be overflow:
```C
// unsigned type
duration = k_uptime_get_32() - frnd->clear.start; 
 	if (duration > 2 * frnd->poll_to) {
```

due to init as:
```C
frnd->clear.start = k_uptime_get_32() + (2 * frnd->poll_to);
```

again, mesh spec define the  friend clear procedure timeout as 2*poll_timeout.

**Comment by jhedberg** [comment]
It's almost two years ago I wrote this code, but to me it looks like the `frnd->clear.start` should simply be initialised to `k_uptime_get_32()` rather than what the code now does. Do you agree?

Regarding integer overflow, as long as we don't go past the same value as the start timestamp after wrapping around to 0, the subtraction will still yield the correct result.

**Comment by menglingao1997** [comment]
> It's almost two years ago I wrote this code, but to me it looks like the `frnd->clear.start` should simply be initialised to `k_uptime_get_32()` rather than what the code now does. Do you agree?
> 
> Regarding integer overflow, as long as we don't go past the same value as the start timestamp after wrapping around to 0, the subtraction will still yield the correct result.

sure
