### ISSUE TITLE
Bluetooth: Mesh: Provision Random buffer has too small size

### ISSUE THREAD

**Issue by LingoMeng** [zephyrproject-rtos/zephyr#19767]
https://github.com/zephyrproject-rtos/zephyr/blob/34b95feb54aa037fe1c1ec5dfc46b61603d420ea/subsys/bluetooth/mesh/prov.c#L984-L990

```C
PROV_BUF(rnd, 17); 
```

**Comment by jhedberg** [comment]
@menglingao1997 thanks! Since this is a simple one-line fix, do you want to try submitting a PR for it?

**Comment by jhedberg** [comment]
Btw, I'm thinking we should make PROV_BUF always allocate the opcode and only provide the parameter length to it, similar in spirit to what @trond-snekvik has been adding for model buffer allocation.

**Comment by jhedberg** [comment]
We've been lucky with this particular bug since while it's a buffer overflow, it overflows into the `u8_t conf_verify[16];` variable which isn't used at this point anymore in the function. Once the buffer size is fixed we could even reuse the buffer for the verification, or use a union, to save some call stack space.
