### ISSUE TITLE
SS register is 0 when taking exceptions on qemu_x86_long

### ISSUE THREAD

**Issue by andrewboie** [zephyrproject-rtos/zephyr#19837]
I am not completely sure this is a bug. But when handling exceptions on qemu_x86_long, I noticed that the SS register is 0. See below output when debugging tests/kernel/fatal.

Somehow, push and pop operations proceed without incident despite this situation. I did find in the IA Manual vol. 3a:

>  On privilege level changes, stack segment selectors are not read from the TSS. Instead, they are set to NULL.

But I'm not sure I fully understand the implications of this.

Feel free to close if this is all as expected.

```
(gdb) set arch i386:x86-64
The target architecture is assumed to be i386:x86-64
(gdb) target remote :1234
Remote debugging using :1234
0x000000000000fff0 in ?? ()
(gdb) b z_fatal_error
Breakpoint 1 at 0x101996: file /home/apboie/projects/zephyr-1.4/zephyr/tests/kernel/fatal/out/zephyr/include/generated/syscalls/kernel.h, line 161.
(gdb) c
Continuing.

Breakpoint 1, z_fatal_error (reason=0, esf=0xc350 <_exception_stack+848>)
    at /home/apboie/projects/zephyr-1.4/zephyr/tests/kernel/fatal/out/zephyr/include/generated/syscalls/kernel.h:161
161		compiler_barrier();
(gdb) info registers
rax            0x3f8	1016
rbx            0x0	0
rcx            0x3f8	1016
rdx            0x3f8	1016
rsi            0xc350	50000
rdi            0x0	0
rbp            0x0	0x0
rsp            0xc348	0xc348 <_exception_stack+840>
r8             0x1	1
r9             0x0	0
r10            0x0	0
r11            0x0	0
r12            0x0	0
r13            0x0	0
r14            0x0	0
r15            0x0	0
rip            0x101996	0x101996 <z_fatal_error>
eflags         0x206	[ IOPL=0 IF PF ]
cs             0x18	24
ss             0x0	0
ds             0x20	32
es             0x20	32
fs             0x20	32
gs             0x30	48
fs_base        0x0	0
gs_base        0xc400	50176
k_gs_base      0x0	0
cr0            0x80010011	[ PG WP ET PE ]
cr2            0x0	0
cr3            0xa000	[ PDBR=0 PCID=0 ]
cr4            0x220	[ OSFXSR PAE ]
cr8            0x0	0
efer           0xd00	[ NXE LMA LME ]
```

**Comment by gnuless** [comment]
This is entirely normal.  Long mode is flat, and can't use segmentation the way 16-/32-bit protected mode do. 

SS/ES/DS selectors are almost entirely ignored (and setting them to null selectors is valid) - the one exception I can think of is that IRETQ to any ring but 0 requires that the SS selector on the stack refer to a present selector (but is otherwise ignored).  Only parts of CS are used, those which determine privilege level and default operand size and such.

FS and GS are a different story, and honor the base addresses of the selector loaded, but even that is not all that useful.  You need to use MSRs to set their bases beyond 32 bits.

The long mode code actually loads a valid 64-bit flat ring 0 data descriptor into the segment registers, but that's just me being pedantic and it's kinda pointless.  Will kill.
