### ISSUE TITLE
CONFIG_NET_ROUTE_MCAST and CONFIG_NET_ROUTING can't be enabled

### ISSUE THREAD

**Issue by ulfalizer** [zephyrproject-rtos/zephyr#19898]
`NET_ROUTE_MCAST` and `NET_ROUTING` (defined in `subsys/net/ip/Kconfig`) aren't user-configurable (have no prompt), have no defaults, and aren't selected/implied, so there's currently no way to enable them, unless someone patches Zephyr or adds them to a `Kconfig.defconfig` somewhere.

Close this if that's fine. Just recording it.

**Comment by jukkar** [comment]
Using the routing code requires some extra work currently so enabling the NET_ROUTING by user is not possible atm. The reason is that the routing was used by RPL stack which was removed in 1.14. We did not remove the generic routing code as that can be used by by a separate RPL or similar implementation. Hopefully we could get RPL back in some future release in which case the routing code would be fully usable again. So this is a known issue.
