### ISSUE TITLE
CONFIG_HEAP_MEM_POOL_SIZE should not be limited

### ISSUE THREAD

**Issue by zzzh** [zephyrproject-rtos/zephyr#20418]
**Is your feature request related to a problem? Please describe.**
I need to allocate bigger RAM size than the limit ( Supported values are: 256, 1024, 4096, and 16384 )

**Describe the solution you'd like**
The size limit should come from hardware, not a config

**Describe alternatives you've considered**
Don't limit the CONFIG_HEAP_MEM_POOL_SIZE anymore

**Additional context**

**Comment by andrewboie** [comment]
I think this is a documentation issue, k_mem_pool works with larger heaps than this.

**Comment by zzzh** [comment]
@andrewboie 
Thanks, do you know how big it can be?

**Comment by dleach02** [comment]
Looking at the underlying implementation, there is no limit to the size of the pool except how much memory is actually available in the system. It isn't obvious why the documentation for the HEAP_MEM_POOL_SIZE even shows various individual sizes since the code is going to eventually define an aligned _mpool_buf_<name> character array. I'll post a PR to change the text in this kconfig item.
