### ISSUE TITLE
[Coverity CID :205640]Control flow issues in /subsys/testsuite/ztest/src/ztest.c

### ISSUE THREAD

**Issue by aasthagr** [zephyrproject-rtos/zephyr#20517]
Static code scan issues seen in File: /subsys/testsuite/ztest/src/ztest.c
 Category: Control flow issues
 Function: z_test_1cpu_stop
 Component: Other
 CID: 205640
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by aescolar** [comment]
efc1ec037be

**Comment by andyross** [comment]
FWIW: the complaint is that there's a loop of the form:

```
for(int i=0; i<MACRO_VALUE; i++) {
    ...
}
```

And the test is flagging the loop interior as dead because MACRO_VALUE evaluates to "1" in the configuration being tested.  We have coverage for that case (SMP targets with more than one CPU) for that elsewhere, but coverity doesn't know about it.

What's policy here?  We can put an #if around it, but that's just replacing one kind of dead code with another that coverity likes better, and IMHO not worth it.  Is there a way to get it access to the variant configurations? (Maybe not, I know it's sort of a performance problem already).
