### ISSUE TITLE
Add k_pipe_flush API

### ISSUE THREAD

**Issue by koffes** [zephyrproject-rtos/zephyr#21512]
It would be beneficial to be able to flush a k_pipe. Suggest adding a k_pipe_flush() API.

AFAIK k_pipe_cleanup() will free a dyn allocated buffer, but this will in many cases be too harsh. The k_pipe_flush() call will keep the buffer allocated, but clear the contents.

**Comment by aescolar** [comment]
CC @andrewboie @andyross

**Comment by peter-mitsis** [comment]
I've started taking a look at the pipe kernel objects. Here is how I am currently interpreting the enhancement request as it does not say anything about writers that are blocked.

A pipe flush would empty the contents of the pipe buffer (if applicable) and unblock all the blocked writers on that pipe. All data (both in the pipe and waiting to go into the pipe) is lost, but those previously pended writers think it succeeded. Blocked readers (if any) are unaffected. Allocated buffers are not freed.

**Comment by koffes** [comment]
As it is quite some time since I created this issue, I do not recall all details. Why would the pending data be lost?

**Comment by peter-mitsis** [comment]
Glad you asked. Admittedly, it might not be the best or ideal proposal (losing pending data), but it is at least a starting point to establish what we want the behaviour to be.

The model I had in my head was that of a clogged kitchen sink--the pipe is clogged/full (this is the pipe buffer) and there is water waiting to drain (this is all the blocked writers).  In this model, flushing the pipe not only removes the clog, but it allows all the water in the sink to drain too--otherwise the pipe (buffer) fills again and there may still be water in the sink (waiting writers). The lost data would be because in the flush, all the write data is not going to a reader; it would be like writing everything to /dev/null--it just goes into empty non-fillable space.

The above model is does differ from  k_pipe_cleanup() which was mentioned enhancement. k_pipe_cleanup() appears to only perform the cleanup if there are neither readers nor writers pending on the pipe--so it impacts only the allocated buffer (which also has the side effect of transforming the buffered pipe into a bufferless pipe--albeit broken).

The ultimate question is "What behaviour do we want/need from a pipe flush?"
