### ISSUE TITLE
mdns support with avahi as client

### ISSUE THREAD

**Issue by ehudmarvell** [zephyrproject-rtos/zephyr#22107]
I tried to enable mdns against avahi client(ubuntu 18.04) and it failed.

It failed on the following code while query_type is 12:

> int dns_unpack_query(struct dns_msg_t *dns_msg, struct net_buf *buf,
> 		     enum dns_rr_type *qtype, enum dns_class *qclass)
> {
> ....
> 	query_type = dns_unpack_query_qtype(end_of_label);
> 	if (query_type != DNS_RR_TYPE_A && query_type != DNS_RR_TYPE_AAAA) {
> 		return -EINVAL;
> 	}

basically I enabled CONFIG_MDNS_RESPONDER and IPV4\IPV6 on Network driver.

Environment:
 - OS: ubuntu 18.04 on the client side, zephyr running on cortex55
 - gcc
 - SHA: 51e4acb8e0b3abfc69e9fc974e662f5dfc374c23

My question is mdns should work with avahi? if yes, should I do any other configuration?
If not, which mdns client tool working fine with zephyr.

Thanks,
Ehud

**Comment by jukkar** [comment]
> My question is mdns should work with avahi? if yes, should I do any other configuration?

Short answer is yes, it should work with avahi. I remember testing it against avahi long time ago. It could have bitrotted as we do not yet have any automatic testing for network samples. There are couple mDNS issues (like #21970 and #21952)  that might affect how it works against avahi.
I will next try to figure out what is going on with #21970, perhaps your issue is related to that.
