### ISSUE TITLE
Bluetooth: SM/MAS/PROT/BV-01-C FAIL

### ISSUE THREAD

**Issue by agata-ponitka** [zephyrproject-rtos/zephyr#22786]
Describe the bug
After timeout Zephyr send pairing failed. 

To Reproduce
run auto-pts

Expected behavior
After timeout Zephyr should ignore pairing response.

[SM_MAS_PROT_BV-01-C_FAIL.zip](https://github.com/zephyrproject-rtos/zephyr/files/4197935/SM_MAS_PROT_BV-01-C_FAIL.zip)

**Comment by aescolar** [comment]
CC @joerchan

**Comment by jhedberg** [comment]
Based on our analysis on Slack: It looks like commit 6a71ebf6c53 from @Vudentz is to blame, since it adds the call to `smp_pairing_complete(smp, BT_SMP_ERR_UNSPECIFIED);` after setting `SMP_FLAG_TIMEOUT`, and then `smp_pairing_complete()` calls `smp_reset()` which in turn calls `atomic_set(smp->flags, 0);`

**Comment by joerchan** [comment]
In my opinion the change could be safely reverted. smp_pairing_complete with an error status is only going to call the security_changed and pairing_failed callbacks.
