### ISSUE TITLE
PTS: Test Framework: Bluetooth:  SM/MAS/SIP/BV-02-C-INCONCLUSIV 

### ISSUE THREAD

**Issue by agata-ponitka** [zephyrproject-rtos/zephyr#22927]
Describe the bug
Zephyr set IO capability to KeyboardOnly instead of KeyboardDisplay

To Reproduce
run auto-pts

Expected behavior    
IO capability needs to be set to KeyboardDisplay

[SM_MAS_SIP_BV-02-C-INCONCLUSIV.zip](https://github.com/zephyrproject-rtos/zephyr/files/4223855/SM_MAS_SIP_BV-02-C-INCONCLUSIV.zip)

**Comment by aescolar** [comment]
CC @jhedberg @joerchan

**Comment by jhedberg** [comment]
@aescolar this sounds more like a test setup error than a stack bug, do you agree?

**Comment by jhedberg** [comment]
Is the high priority really justified? I just took a look at `get_io_capa()` in `host/smp.c` and it *is* able to return KeyboardOnly, so this looks more like an auto-pts or tester app issue, and should therefore not be high priority (since the stack poses no obstacle for qualification in this particular case)
