### ISSUE TITLE
posix: clock: No thread safety clock_[get/set]time 

### ISSUE THREAD

**Issue by jdascenzio** [zephyrproject-rtos/zephyr#23419]
Hi,
Posix specify that clock_settime and clock_gettime are Multithread safe. However, the global variable rt_clock_base could be get/and set at the same time without protection... Is that normal?

**Comment by pfalcon** [comment]
Sorry for lack of any response here. That's definitely not normal, if POSIX stipulates that those functions should be MT-safe. It thus becomes a "known issue". I however agree with priority of "low" for this issue, as clock_settime() isn't expected to be called frequently, and most likely, would be called at application initialization, before application threads are created.

That said, patch is definitely welcome (I assume it wasn't posted, as there're no linked PR requests in github UI). Based on the above, I would also conjecture that we can avoid heavy-weight sync primitives for it, and just use irqlock (because again, clock_settime() isn't expected to be called often).
