### ISSUE TITLE
drivers: timer: nrf52: Question: Does nRF52840 errata 179 affect nrf_rtc_timer driver?

### ISSUE THREAD

**Issue by sslupsky** [zephyrproject-rtos/zephyr#23571]
I was reviewing the nRF52840 errata and came across errata 179, "RTC: COMPARE event is generated twice from a single RTC compare match".  See https://infocenter.nordicsemi.com/index.jsp?topic=%2Ferrata_nRF52840_Rev2%2FERR%2FnRF52840%2FRev2%2Flatest%2Ferr_840.html

This errata implies that anytime the RTC registers are accessed while waiting for a COMPARE event, a spurious interrupt will be generated.  The nrf_rtc_timer driver has several functions that access the RTC registers at anytime while while waiting for COMPARE events to occur through z_clock_set_timeout(), z_clock_elapsed() and z_timer_cycle_get_32().

The errata says:

> Tasks connected to RTC COMPARE event through PPI are triggered twice per compare match.

and

> Note that CPU interrupt from this event can still be enabled.

Is there a workaround possible for this errata that is compatible with Zephyr?  It appears that if I configure another COMPARE event to trigger a task for an endpoint using the PPI, then the nrf_rtc_timer driver will cause spurious events to the configured endpoint?  Further, it is not clear if other PPI endpoints are affected as well?

Finally, just to confirm, the CPU interrupts are not affected if a COMPARE event uses the PPI?

**Comment by nordic-krch** [comment]
Yes, anomaly is affecting only PPI connections since double events does not harm interrupt handling because they are next to each other so happen before interrupt is handled. `nrf_rtc_timer.c` is not using PPI so no workaround is applied. If user would like to use another COMPARE channels for his own purpose then he may be affected by this anomaly. Unfortunately, there is no good workaround for that as we have no control when system is reconfiguring event for system timer. Because of that it would not recommend to use PPI event for things where double event will cause an issue, e.g. timer in count mode or gpiote toggle. It should do no harm for tasks like start or stop.
