### ISSUE TITLE
litex_vexriscv: k_busy_wait() never returns if called with interrupts locked

### ISSUE THREAD

**Issue by stephanosio** [zephyrproject-rtos/zephyr#23622]
**Describe the bug**
k_busy_wait() never returns if called with interrupts locked on the `litex_vexriscv` platform, which uses `litex_timer` system timer.

For more details, refer to the issue #23519.

**Comment by stephanosio** [comment]
cc @mateusz-holenko

**Comment by carlescufi** [comment]
@mateusz-holenko do you have plans to address this?

**Comment by mateusz-holenko** [comment]
@carlescufi  - yes, we are planning to look at this soon.

**Comment by stephanosio** [comment]
Has this been addressed?

**Comment by mateusz-holenko** [comment]
We are currrently working on this. It turned out that the timer in LiteX is very simple and implementing a proper `k_busy_wait()` (allowing to wait for periods longer than 10ms) would require either a custom not-trivial implementation or extending the capabilities of HW (since it's a soft IP core anyway).

We decided to go with the second option and are now adding a register allowing to read the total number of timer ticks from reset to the timer itself. Once it's done and tested we will update the driver to use this in `k_cycle_get32()` function.
