### ISSUE TITLE
gap in support for deprecated Nordic board names

### ISSUE THREAD

**Issue by pabigot** [zephyrproject-rtos/zephyr#24158]
Something seems to be failing with the deprecated Nordic board names.

`samples/subsys/shell/fs/CMakeLists.txt` looks at the board name to determine whether the `mpu.conf` overlay is required.  The file was updated to use the new board names, and the addition is not performed for the deprecated name.

```
tirzah[346]$ rm -rf build && west build -b nrf52840dk_nrf52840 samples/subsys/shell/fs >/dev/null && grep CONFIG_MPU_ALLOW build/zephyr/.config 
Including boilerplate (Zephyr base): /mnt/nordic/zp/zephyr/cmake/app/boilerplate.cmake
CONFIG_MPU_ALLOW_FLASH_WRITE=y

tirzah[347]$ rm -rf build && west build -b nrf52840_pca10056 samples/subsys/shell/fs >/dev/null && grep CONFIG_MPU_ALLOW build/zephyr/.config 
Including boilerplate (Zephyr base): /mnt/nordic/zp/zephyr/cmake/app/boilerplate.cmake
CMake Warning at /mnt/nordic/zp/zephyr/cmake/app/boilerplate.cmake:200 (message):
  Deprecated BOARD=nrf52840_pca10056 name specified, board automatically
  changed to: nrf52840dk_nrf52840.
Call Stack (most recent call first):
  /mnt/nordic/zp/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /mnt/nordic/zp/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:17 (find_package)


# CONFIG_MPU_ALLOW_FLASH_WRITE is not set

```

**Comment by pabigot** [comment]
@carlescufi This is the underlying cause of #24145.

**Comment by carlescufi** [comment]
@tejlmand can you take a look please?
@pabigot thanks for the analysis

**Comment by tejlmand** [comment]
This happens because the sample CMakeLists.txt itself tests the board name BEFORE renaming is done.

Hence, it doesn't know anything about deprecated boards.
Secondly, it also happens before boilerplate is sourced, making things trickier.

Of course the easy fix is to just update to test both new and deprecated boards, but as this also affect aliases, it should be considered if we can do something else.
https://github.com/zephyrproject-rtos/zephyr/blob/master/samples/subsys/shell/fs/CMakeLists.txt#L5-L8

**Comment by tejlmand** [comment]
actually, the CMake code in the linked file will never work as intended, cause `APPLICATION_SOURCE_DIR` is a variable being defined in boilerplate, and hence not available in code at that time it is used.
