### ISSUE TITLE
question regarding c++

### ISSUE THREAD

**Issue by CodingGhost** [zephyrproject-rtos/zephyr#24195]
I hope its ok to ask here, but I have not found any other forum where I could ask, neither did I find enough information about my  issue.

does Zephyr fully support c++?
I started developing, but I cannot include vectors or strings..etc

I have added 
CONFIG_CPLUSPLUS=y
CONFIG_LIB_CPLUSPLUS=y

to my prj.conf, but it does not work.
how can I get this to work, and where should I be posting questions?

**Comment by pabigot** [comment]
No, Zephyr does not fully support C++.   #18554 has some status; though it refers to 2.1 I don't believe anything's changed.

Look to `tests/application_development/libcxx/` for the most advanced sample; in particular you need to use newlib in order to access standard library capabilities.  

You can ask questions in the [slack general channel](https://docs.zephyrproject.org/latest/guides/getting-help.html).
