### ISSUE TITLE
tests: kernel: timer: timer_api: regression on STM32 boards

### ISSUE THREAD

**Issue by ABOSTM** [zephyrproject-rtos/zephyr#26039]
**Describe the bug**
Since merge of 

> #25831 tests: kernel: timer_api: more attempts to make this pass on every Nordic board instance

there is a regression of tests/kernel/timer/timer_api on STM32 boards: 
disco_l475_iot1, nucleo_f746zg, nucleo_l152re , nucleo_wb55rg 

**To Reproduce**
1. west build -p auto -b nucleo_f746zg tests/kernel/timer/timer_api/
2. west flash
3. See error

**Expected behavior**
Test Passed

**Screenshots or console output**
```
*** Booting Zephyr OS build zephyr-v2.3.0  ***
Running test suite timer_api
===================================================================
starting test - test_time_conversions
PASS - test_time_conversions
===================================================================
starting test - test_timer_duration_period
PASS - test_timer_duration_period
===================================================================
starting test - test_timer_period_0
PASS - test_timer_period_0
===================================================================
starting test - test_timer_expirefn_null
PASS - test_timer_expirefn_null
===================================================================
starting test - test_timer_periodicity
PASS - test_timer_periodicity
===================================================================
starting test - test_timer_status_get
PASS - test_timer_status_get
===================================================================
starting test - test_timer_status_get_anytime
PASS - test_timer_status_get_anytime
===================================================================
starting test - test_timer_status_sync
PASS - test_timer_status_sync
===================================================================
starting test - test_timer_k_define
PASS - test_timer_k_define
===================================================================
starting test - test_timer_user_data
PASS - test_timer_user_data
===================================================================
starting test - test_timer_remaining

    Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/timer/timer_api/src/main.c:603: test_timer_remaining: (abs(delta_ticks) <= MAX(slew_ticks, 1U) is false)
tick/busy slew -2 larger than test threshold 0
FAIL - test_timer_remaining
```

**Additional context**
Note: Debugger show:
`target_rem_ticks = 501`
`rem_ticks = 499`
`slew_ticks=0`

and so `delta_ticks=-2` which is bigger than `MAX(slew_ticks, 1U)`

**Comment by ABOSTM** [comment]
@pabigot ,
Maybe
`       u32_t target_rem_ticks = k_ms_to_ticks_ceil32(DURATION / 2) + 1;`
should be replaced by
`       u32_t target_rem_ticks = k_ms_to_ticks_ceil32((DURATION + 1) / 2);`
 ?

**Comment by pabigot** [comment]
Interesting.  We were supposed to discuss #25831 in a multi-vendor context before merging; I didn't want that PR in the release precisely because it could introduce this sort of problem.

`target_rem_ticks` comes from 8fbc83c6511e5197ed06b3cd88469d671aed5082 via #25539 where it replaced `(dur_ticks / 2) + 1` for reasons described in the comment present in that commit.  At that time there was a hard-coded 3-tick margin resulting from early attempts to make the test work on Nordic.  (The test is not valid in cases where slew is zero, but we can't just not run it on those boards.)

Using `(DURATION + 1) / 2` instead of `DURATION / 2` has no effect since `DURATION` is even in the test.  Removing the `+ 1` and relying on the `ceil` alone seems reasonable.   In the original the ` + 1` was added in 0b12a7b463e9a3bd78559f1e5f807e1d6cb83760 and served as providing a margin when the test was one-sided.

Potential fix submitted.  This works on my l476rg.

**Comment by ABOSTM** [comment]
> Using (DURATION + 1) / 2 instead of DURATION / 2 has no effect since DURATION is even in the test.

It has some effect. I tested and test is passed.
DURATION is 100, 
and so `target_rem_ticks = k_ms_to_ticks_ceil32((DURATION + 1) / 2) = 500` instead of 501
