### ISSUE TITLE
Bluetooth: Mesh: Friend node unexpected un-reference buffer

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#26177]
**Describe the bug**
A single Friend node and low power node, establish friendship and run for a few days.
due to advertising message lost, this maybe cause friendship closed.

**but, unexpected friend node finally dies.**

Considering the log output, based on my inference. adv queue pool cache friend message and sametimes received lpn friend_clear message.

https://github.com/zephyrproject-rtos/zephyr/blob/636d6cd9cdb6648374bf906953d1a9b96f74aa7d/subsys/bluetooth/mesh/friend.c#L1079-L1092

`net_buf_unref(frnd->last);`
should add check the var frnd->last == NULL

**Comment by trond-snekvik** [comment]
Good find.

Looks like this is caused by `bt_le_adv_start` yielding when sending a synchronous command. The `BT_MESH_ADV(frnd->last)->busy = 0U` logic in `friend_clear` is based the adv thread not being preempted before the sleep in `adv_send`, but it would when hci_core grabs the hci semaphore.

I'll check if there are similar issues elsewhere and make a PR
