### ISSUE TITLE
xtensa xt-xcc inline warning

### ISSUE THREAD

**Issue by hongshui3000** [zephyrproject-rtos/zephyr#29706]
**Describe the bug**
xtensa xcc inline warning

**To Reproduce**
west build -b qemu_xtensa samples/hello_world

**Logs and console output**
E:/zephyrproject/zephyr/kernel/sched.c:699: warning: C99 inline functions are not supported; using GNU89
E:/zephyrproject/zephyr/kernel/sched.c:699: warning: to disable this warning use -fgnu89-inline or the gnu_inline function attribute
../kernel/include/ksched.h:58: warning: 'z_find_first_thread_to_unpend' declared inline after being called
../kernel/include/ksched.h:58: warning: previous declaration of 'z_find_first_thread_to_unpend' was here
E:/work/rtos_work/zephyrproject/zephyr/kernel/sched.c:719: warning: C99 inline functions are not supported; using GNU89
../kernel/include/ksched.h:43: warning: 'z_unpend_thread_no_timeout' declared inline after being called
../kernel/include/ksched.h:43: warning: previous declaration of 'z_unpend_thread_no_timeout' was here
E:/zephyrproject/zephyr/kernel/sched.c:964: warning: C99 inline functions are not supported; using GNU89
E:/zephyrproject/zephyr/kernel/sched.c:1080: warning: C99 inline functions are not supported; using GNU89
E:/zephyrproject/zephyr/kernel/sched.c:1088: warning: C99 inline functions are not supported; using GNU89
[65/65] Linking C executable zephyr\zephyr.elf

**Environment (please complete the following information):**
 - OS: ( Windows)
 - Toolchain (xcc)

**Comment by dcpleung** [comment]
This is due to XCC not supporting C99 inline as XCC is based on GCC 4.2. To get rid of these warning requires refactoring lots of scheduler code, which is undesirable to simply support an outdated compiler. My recommendation is to try a newer XCC release which has Clang support (e.g. has `xt-clang` executable), as it should have C99 inlining support alreay.

Closing this as "won't fix".
