### ISSUE TITLE
net: lwm2m: Correctly Support Bootstrap-Delete Operation

### ISSUE THREAD

**Issue by broglep-work** [zephyrproject-rtos/zephyr#29964]
# Summary  
- `DELETE /` is implemented as `DELETE /0` 
- `DELETE /`and `DELETE /x` for x != 0 is not supported/implemented

# Background
Zephyr client should support bootstrap-delete according to the [specification](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-1-7-6-0-6176-Bootstrap-Delete-Operation).
Currently the support is only implementing partially and that part not according to the specification: 

- If the client is in bootstrap mode and bootstrap server sends a DELETE request without `Uri-Path` option, then bootstrap_delete will be executed ([wm2m_engine.c:3344](https://github.com/zephyrproject-rtos/zephyr/blob/7127f0a7420869876e425f514dedf6c1645269a5/subsys/net/lib/lwm2m/lwm2m_engine.c#L3344))
- `bootstrap_delete` deletes SECURITY instances > 0

Given `bootstrap_delete` is called when no uri option is set, the assumed contract of that method is that it should correspond to DELETE /  where `all Instances of all Objects in the LwM2M Client MUST be removed (except for the two cases mentioned above)` where `The two exceptions are the LwM2M Bootstrap-Server Account, potentially including an associated Instance of an OSCORE Object ID:21, and the single Instance of the mandatory Device Object (ID:3), which are not affected by any Delete operation.`

# Proposal
1. Fix: Adjust current code to delete all other object instances as well
2. Enhancement: Support both no `Uri-Path` header and empty `Uri-Path` header, and treat them the same way 
3. Enhancement: Support deletion of all instance of a particular object

## Side Note
Sending a `DELETE /x` request to the client in bootstrap mode is executed as `DELETE /x/0` (goes through regular delete request handler that does not check if uri path has length >=2 as it is not allowed by the spec outside of bootstrap, object and instance id must be set)

**Comment by rlubos** [comment]
@broglep-work Thanks for reporting. Indeed the current implementation oversimplified a lot. I've pushed a PR with proposed changes:
https://github.com/zephyrproject-rtos/zephyr/pull/30200

I've verified that DELETE `/` and DELETE `/x` works as expected, I wasn't able to verify DELETE `/x/y` though as the bootstrap serves I tried with did not issue such operation. I'm not expecting any surprises there though since the same `bootstrap_delete` handler shall be called then, which implements single resource removal in a straightforward way.

During the rework I've also realized that bootstrap DISCOVER operation is totally broken, but that's a story for a separate PR.
