### ISSUE TITLE
twister: CI: Run twister daily builds with "--overflow-as-errors"

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#31348]
I understand that having ram overflows treated as errors was problematic for on-commit CI runs. What about adding this option to daily builds? It would allow to catch these errors in the CI, but won't block commits. 
@nashif @galak

**Comment by nashif** [comment]
This is actually a problem with the daily run, I do not think RAM/SRAM overflows should be treated as bugs or issues, this is going to be a never-ending thing. We have to accept the fact that not everything we build will fit in every configuration. My concern is that we will start filtering based on RAM in tests and will be excluding way too many boards just because of a few that are either misconfigured or require too much resources by default.

**Comment by golowanow** [comment]
@zephyrproject-rtos/testing after a while, let's discuss this problem once more - either here, or on Zephyr Testing WG meeting.
see also https://github.com/zephyrproject-rtos/zephyr/pull/92000

**Comment by PerMac** [comment]
Summary from a discussion during testing wg meeting:
We can:
- Use existing CI data to identify and fix footprint issues. (needs enabling in the CI)
- Set min_ram/flash in tests causing majority of failures.
- Have problematic platforms marked in platform.yaml to not cause overflow errors
- Treat overflows as errors only for runnable tests in CI (and on hw when devices are connected). Not executing a runnable tests (due to overflow) should be treated as a regression degrading a coverage scope.
- Avoid overgeneralizing fixes (e.g. setting overly high memory limits).
- Use integration platforms selectively to guard against regressions.
- Encourage smarter test scoping downstream to avoid unnecessary failures.
