### ISSUE TITLE
ppp: termination packet not sent

### ISSUE THREAD

**Issue by shlomow** [zephyrproject-rtos/zephyr#33099]
**Describe the bug**
When working with ppp protocol, everything connects okay, and I have a ping from my linux machine.
When I run `net iface down` from the shell I expected that the ppp stack will send termination packet to pppd.

**To Reproduce**
Build any sample with ppp and shell.

**Impact**
It has an impact on the cellular stack, since `ppp_stop` does not really disconnect the modem from the internet,
so when calling `start` after that, the modem is in data mode and not in command mode.

**Comment by mniestroj** [comment]
I am not so sure that we `net iface down` should map into "administrative Close" of PPP link. It is something to discuss how it should behave. In Linux for example, `pppd` is a userspace process that is responsible for setting up PPP link and configuring network interface. It creates ppp0 network interface, communicates over serial to setup a link and if everything is ready (PPP link is up) it sets ppp0 interface up, so that userspace applications can start using it. When userspace wants to shut down PPP, then it sends signal into `pppd` process (this is what `poff` does) to gracefully shut down PPP link. Note that you do not call `ip link set ppp0 down` or similar to achieve that, as it would just disable network interface and leave PPP link up.

So the question is: what are `net_if_up()` and `net_if_down()` responsible for in Zephyr? So far they are called both by network drivers to tell that network drivers are ready, as well as they are the mechanism applications can use for enabling/disabling network interface. This is why #28998 was started.
