### ISSUE TITLE
twister: Find and fix all "dead" samples/tests

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#33337]
**Is your enhancement proposal related to a problem? Please describe.**
There exist tests/samples in zephyr, that due to their yamls config, end up with an empty platform scope in the CI regression tests. It is a problem, as errors can leak into the main and won't be found. Such problems were already reported to me a couple of times. A contributor found an error in their PR in location, which the PR is not affecting, only because due to changing sth in the test, the full scope was tested and the fault was found. 
"Dead" tests (fully skipped in default CI) give a false impression to developers, that their code is fine and they can cause severe errors being hidden in the main for a long time. 

**Describe the solution you'd like**
To solve this we should at minimum verify that the situation, where the test is skipped on all platforms is not happening during the default CI run. I opt for giving a warning (or maybe an error) in every case when all platforms are skipped for a test. Would it be possible to do this at the scenario level (i.e. warning when a scenario is not tested at all?

**Additional context**
E.g this test (https://github.com/zephyrproject-rtos/zephyr/blob/master/tests/bluetooth/df/testcase.yaml): nrf52_bsim is not in the default platforms list and it is the only allowed platform in the testcase.yaml. The error was found only after some time, in a PR modifying a file in the test folder, where different platform scope was run in the CI. The author was confused, as their code wasn't the cause of the error.  This will be fixed by adding nrf52_bsim to 'integration_platforms" in the yaml. However, I believe it is important to have a solution, which will prevent such problems. 
I reported this as an enhancement, however, I think it should be treated as a bug with quite high priority

**Comment by nashif** [comment]
nrf52_bsim tests afaik have their own workflow and are not tested with twister, they use edtt and a special setup, that is why they are not default and are not executed by default.

saying that such a test is 'dead' is wrong because it would be covered in the daily build which runs on all available platforms. There are probably wrong filter that are real bugs, but this is not an issue AFAIK. If you want to test if this builds, you probably want to add another platform to the allow list and not this one, but, this also gives the impression that something actually has passed, although it is just only building and not executing...
