### ISSUE TITLE
Device tree: STM32L412 and STM32L422 are missing nodes

### ISSUE THREAD

**Issue by gudnimg** [zephyrproject-rtos/zephyr#33895]
I noticed the device tree for stm32l412xx and stm32l422xx are missing the following peripherals:

- [ ] I2C2
- [ ] LPTIM2
- [ ] ADC2
- [x] SPI2 (Included in PR: https://github.com/zephyrproject-rtos/zephyr/pull/34187)
- [ ] SPI3 (stm32l412xx only)
- [ ] USART3
- [x] ~~OPAMP1~~ (not supported by drivers)
- [x] ~~COMP1~~ (not supported by drivers)

We should add it the file `dts/arm/st/l4/stm32l412.dtsi`

This would enable the peripherals for the following chips and their respective supported boards:
* stm32l412x8
* stm32l412xb
* stm32l422xb

**Comment by erwango** [comment]
@GunZi200 Thanks for reporting. Don't hesitate to push the changes if you have some time.

Though, please note that OPAMP and COMP1 are not currently supported.
This also needs to be checked for LPTIM2 (I don't think it would work as is)

**Comment by erwango** [comment]
@gudnimg I propose to close this point as we don't claim that STM32 soc description are complete, but they are done on need basis. So that's ok to open a point is if there's an action to close it, but I don't want to keep these for long as I don't plan to track them.
Feel free to re-open if you have plans to fix
