### ISSUE TITLE
Tensorflow: Dedicated tflite-micro repository

### ISSUE THREAD

**Issue by JordanYates** [zephyrproject-rtos/zephyr#36947]
## Purpose

The tensorflow organisation has recently (June 25th) split out the tensorflow micro code into a dedicated repository, instead of being part of the parent tensorflow repo. The dedicated repository is considerably smaller (5.85MB instead of 680MB), and is where future development will take place. The old location of the tflite-micro code in the parent repository has been removed (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro).

https://github.com/tensorflow/tensorflow
https://github.com/tensorflow/tflite-micro

We should swap over from the tensorflow fork (https://github.com/zephyrproject-rtos/tensorflow) to a fork of the tflite-micro repository.

**Comment by carlescufi** [comment]
@laurenmurphyx64 is this something that you could take care of?

**Comment by carlescufi** [comment]
No objections from the TSC.

**Comment by galak** [comment]
I went ahead and created https://github.com/zephyrproject-rtos/tflite-micro

**Comment by laurenmurphyx64** [comment]
While working on this issue, I found that the Zephyr build for the examples in the new TFLM repo is broken due to recent changes made to the TF build system files that generate the CMakeLists.txt used by the Zephyr build system. I've filed an [issue](https://github.com/tensorflow/tflite-micro/issues/332) and submitted a [PR](https://github.com/tensorflow/tflite-micro/pull/333). I am now waiting for Google / Intel to legally approve me as a contributor.

**Comment by laurenmurphyx64** [comment]
After discussion in my PR to TensorFlow, I'm OK with making the Zephyr module. 

The module PR is here: https://github.com/zephyrproject-rtos/tflite-micro/pull/1. 
The Zephyr PR is here: https://github.com/zephyrproject-rtos/zephyr/pull/37318/
