### ISSUE TITLE
hello world doesn't work on qemu_arc_em when CONFIG_ISR_STACK_SIZE=1048510

### ISSUE THREAD

**Issue by wentongwu** [zephyrproject-rtos/zephyr#37704]
**Describe the bug**
hello world sample doesn't work on qemu_arc_em when CONFIG_ISR_STACK_SIZE=1048510

**To Reproduce**
1. mkdir build; cd build
2. cmake -DBOARD=qemu_arc_em -DCONFIG_ISR_STACK_SIZE=1048510 ..
3. make run

**Comment by wentongwu** [comment]
The SDK is 0.13.0

**Comment by IRISZZW** [comment]
@wentongwu I can reproduce it with qemu_arc_em and nsim_em boards. 
Then I try to CONFIG_ISR_STACK_SIZE=1048576 (1M), it works fine for both boards. I will continue debug it.
I'm so curios how did you get the ``magic number`` 1048510, Could you provide more details?

**Comment by IRISZZW** [comment]
@wentongwu  Could you please provide more details?

**Comment by wentongwu** [comment]
> @wentongwu Could you please provide more details?

someone told me it's just by accidental.

BTW I think this is a high priority bug because it impacts the basic function of Zephyr OS.

**Comment by IRISZZW** [comment]
@wentongwu usually stack address and stack size need stack alignment, 1048510 is not aligned to 4. so it may cause `Misaligned data access` exception.

**Comment by cfriedt** [comment]
Is a 1M stack common for ARC? Typically, we see stack sizes of 1kB, 2kB... even Linux has just started using a stack size of 8kB now for x86_64.

@wentongwu - have you tried a more conventional stack size such as `CONFIG_ISR_STACK_SIZE=4096`?

**Comment by wentongwu** [comment]
@cfriedt AFAIK nobody uses so large stack size in real product. But I don't want to talk about why we use so large stack in QEMU. And also Linux...

But the problem here is that the none-4byte-align stack size will cause qemu arc run incorrectly. Not sure if you have tried other size like `cmake -DBOARD=qemu_arc_em -DCONFIG_ISR_STACK_SIZE=4094 ..` or other platform like `mps2_an385`, `qemu_x86`, or zephyr old version(like 2.5).

**Comment by evgeniy-paltsev** [comment]
It's enough to use any unaligned ISR_STACK_SIZE, I.e ISR_STACK_SIZE=2050 instead of 2048.

The root cause seems to be in how we setup stack pointer in reset.S - we are setting it to unaligned value.

```
#define INIT_STACK z_interrupt_stacks
#define INIT_STACK_SIZE CONFIG_ISR_STACK_SIZE

	mov_s sp, INIT_STACK
	add sp, sp, INIT_STACK_SIZE

``` 

I guess it would be enough to check in compile time that we have proper CONFIG_ISR_STACK_SIZE alignment. 
@ruuddw @abrodkin any objections on this?

**Comment by abrodkin** [comment]
Indeed, we shouldn't set bogus values in `SP`. Another question is how to handle those cases. I'd say compile-time warning is OK.
We may otherwise try to compensate for funny sizes in-place, but that may unexpectedly move stack boundaries if we just silently align provided random value. Ah, and BTW what about `z_interrupt_stacks`, are we sure it's properly aligned as well?

**Comment by ruuddw** [comment]
Compile-time error seems fine in this case. For user stacks the alignment I believe is handled by macro's rounding up, but the alignment can be different depending on configuration (e.g. with or without MPU). In this case the alignment requirement is always the same, and word aligned stack and stack size are reasonable to enforce.
