### ISSUE TITLE
tests: newlib: Scenarios from tests/lib/newlib/thread_safety fail on nrf9160dk_nrf9160_ns

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#38044]
**Describe the bug**
2 test scenarios:
- libraries.libc.newlib.thread_safety.userspace.stress
- libraries.libc.newlib_nano.thread_safety.userspace.stress
fail on nrf9160dk_nrf9160_ns

**To Reproduce**
1. have nrf9160dk connected
2. go to zephyr dir
3. run `scripts/twister -T tests/lib/newlib/thread_safety -p nrf9160dk_nrf9160_ns --device-testing --device-serial /dev/ttyACM0`

**Expected behavior**
All these tests pass

**Impact**
Not clear

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v2.6.0-2549-g51f2022f7b49  ***
ASSERTION FAIL [((((size_t)128) << 10) - ((((unsigned long)(((uintptr_t) (&_end))) + ((unsigned long)(32) - 1)) & ~((unsigned long)(32) - 1)) - 0x20020000)) >= 8192] @ WEST_TOPDIR/zephyr/lib/libc/newlib/libc-hooks.c:128
memory space available for newlib heap is less than the minimum required size specified by CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE
E: r0/a1:  0x00000004  r1/a2:  0x00000080  r2/a3:  0x00000001
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x0005d8f7
E:  xpsr:  0x41000000
E: Faulting instruction address (r15/pc): 0x0005d910
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x200237e8 (main)
E: Halting system
```
and
```
*** Booting Zephyr OS build zephyr-v2.6.0-2549-g51f2022f7b49  ***
ASSERTION FAIL [((((size_t)128) << 10) - ((((unsigned long)(((uintptr_t) (&_end))) + ((unsigned long)(32) - 1)) & ~((unsigned long)(32) - 1)) - 0x20020000)) >= 2048] @ WEST_TOPDIR/zephyr/lib/libc/newlib/libc-hooks.c:128
memory space available for newlib heap is less than the minimum required size specified by CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE
E: r0/a1:  0x00000004  r1/a2:  0x00000080  r2/a3:  0x00000001
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x0005ce07
E:  xpsr:  0x41000000
E: Faulting instruction address (r15/pc): 0x0005ce20
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Current thread: 0x20023188 (main)
E: Halting system
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Toolchain: zephyr-sdk 0.13.0
 - Commit SHA or Version used: zephyr-v2.6.0-2549-g51f2022f7b49

**Comment by stephanosio** [comment]
In case of Cortex-M33 (ARMv8-M), `CONFIG_MPU_REQUIRES_POWER_OF_TWO_ALIGNMENT` is `n` and static allocation of the newlib heap area using `CONFIG_NEWLIB_LIBC_ALIGNED_HEAP_SIZE` is not done; instead, we use the leftover SRAM area for the newlib heap.

For `nrf9160dk_nrf9160_ns`, the leftover SRAM area is less than the minimum required size specified by `CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE` hence why we see this assertion message.

Normally, for any statically allocated regions, twister will skip the test if there is an overflow; but here, we implicitly make use of the leftover area without the linker's knowledge, so there is no linker error and twister ends up treating this as a failure at runtime.

For now, we can set `CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=0` for these testcases since they do not make use of any newlib functions that actually require large heap (e.g. `scanf`).

Eventually, we will need to rework the newlib hook implementation such that the newlib heap area is statically allocated and known to the linker. The size of the statically allocated heap area should be determined with `MIN(MIN_HEAP_SIZE, FREE_MEM_SIZE)` such that if `FREE_MEM_SIZE` is smaller than `MIN_HEAP_SIZE`, a linker error will occur and twister will skip these tests (with "SRAM overflow").
