### ISSUE TITLE
Bluetooth: host: Local Host terminated but send host number of completed Packed

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#38054]
![1630043781(1)](https://user-images.githubusercontent.com/26378606/131079101-9ef23c80-ae49-4c4d-8ba2-6a4a92a466fd.png)

1. Host Terminated Connection
2. Host Received ACL data EX
3. Host send Host number of completed packed
4. Controller Reponse error

**Comment by LingaoM** [comment]
I think we must judge whether the currently received hci command complete is what we expect instead of simple warning this and continue process this https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/hci_core.c#L2010. I looked at the current implementation mechanism, after the HCI Command complete event is received, it will directly reuse the buffer of the hci command and clear it in https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/bluetooth/host/buf.c#L98. I think this approach is not good, it will make us ignore the real hci command response. In this figure, we mistakenly discarded the response result of scan params. But I think this problem may still appear in other scenarios.

**Comment by Thalley** [comment]
Hi @LingaoM this sounds like a controller issue. From `7.7.19 Number Of Completed Packets event` in the core specification:

> The HCI_Number_Of_Completed_Packets event shall not specify a given Connection_Handle before the event indicating the corresponding connection has been created or *after an event indicating disconnection of the corresponding connection.*

**Comment by joerchan** [comment]
@Thalley You are reading the wrong text. That is about the Event from controller to host. This is about the command from host to controller.

@LingaoM Since the nature of the Host Number of Completed Packets is so different and we have an exception for it in the `bt_hci_cmd_send` function it seems like the proper way of handling it would be to have an exception for it in the command_done handling as well. That would be more future proof if there are any other cases that produces a command complete event for that specific command.

**Comment by Thalley** [comment]
@joerchan Ah, sorry for missing that. 

However, for the command the following text exists:

> The HCI_Host_Number_Of_Completed_Packets command may be sent at any time by the Host when there is at least one connection, or if the Controller is in local loopback mode, independent of other commands. **If the Host issues this command when neither of these cases applies, the Controller shall ignore it. ** 

So shouldn't the command in the HCI log have been ignored by the controller? This, couple with 

> Normally, no event is generated after the HCI_Host_Number_Of_Completed_Packets command has completed.

Should perhaps be the case here, and the controller shouldn't have send the event with the error in the first place?

**Comment by rugeGerritsen** [comment]
I agree with @joerchan that the host should be able to receive a command complete for the _Host Number Of Completed Packets command_
> Normally, no event is generated after the HCI_Host_Number_Of_Completed_-
Packets command has completed. However, if the HCI_Host_Number_Of_-
Completed_Packets command contains one or more invalid parameters, the
Controller shall return an HCI_Command_Complete event containing the error
code Invalid HCI Command Parameters (0x12). The normal flow control for
commands is not used for this command

**Comment by rugeGerritsen** [comment]
@LingaoM , from the shown trace, the host is doing the correct thing. It is sending _HCI_Host_Number_Of_Completed_Packets_ until it receives the _HCI_Disconnection_Complete event_.  @cvinayak , therefore this looks like a controller bug.

See Core 5.3, Vol 4, Part E, Section 4.3 Disconnection behavior:
>If flow control is also enabled in the direction from the Controller to the Host,
the Controller may, after it has sent an HCI_Disconnection_Complete event,
assume that the Host will flush its data buffers for the sent Handle when it
receives the HCI_Disconnection_Complete event. The Host does not have to
notify the Controller about this in an HCI_Host_Number_Of_Completed_-
Packets command.

**Comment by carlescufi** [comment]
@rugeGerritsen 

>The Host does not have to
notify the Controller about this in an HCI_Host_Number_Of_Completed_-
Packets command.

I think the spec is unclear here about what to do with a Host num complete that contains a disconnected connection handle. It could remember that this is a recently disconnected connection and not reply at all, or as is the case right now, it can reply with a command complete with invalid handle error. Handling the former would be difficult in the controller and seems not worth it, so let's adopt the latter for the controller (i.e. sending command complete with invalid handle error if the handle belongs to a disconnected connection). So instead I suggest  one of the following two options:

1. The Host sends the Host num complete, but ignores the command complete with invalid handle error
2. The Host does not send Host num completes at all for connections that have been disconnected

However, the Host num complete and the disconnection complete might come through a serial HCI connection at the same time, so we probably need a combination of both:

a) The Host will not send Host num complete for a connection that is disconnected (we reset the counters internally anyway and placing a now invalid connection handle in a command seems wrong)
b) The Host ignores command completes for Host num complete with invalid handle (in case the disconnection complete was not processed by the Host before sending the Host num complete, for example because they came at the same time over HCI)

I propose we implement both a) and b) which is exactly what #38056 is doing.

**Comment by Thalley** [comment]
> @rugeGerritsen @Thalley @joerchan @LingaoM
> 
> > The Host does not have to
> > notify the Controller about this in an HCI_Host_Number_Of_Completed_-
> > Packets command.
> 
> I think the spec is unclear here about what to do with a Host num complete that contains a disconnected connection handle. It could remember that this is a recently disconnected connection and not reply at all, or as is the case right now, it can reply with a command complete with invalid handle error. Handling the former would be difficult in the controller and seems not worth it, so let's adopt the latter for the controller (i.e. sending command complete with invalid handle error if the handle belongs to a disconnected connection). So instead I suggest one of the following two options:
> 
>     1. The Host sends the Host num complete, but ignores the command complete with invalid handle error
> 
>     2. The Host does not send Host num completes at all for connections that have been disconnected
> 
> 
> However, the Host num complete and the disconnection complete might come through a serial HCI connection at the same time, so we probably need a combination of both:
> 
> a) The Host will not send Host num complete for a connection that is disconnected (we reset the counters internally anyway and placing a now invalid connection handle in a command seems wrong)
> b) The Host ignores command completes for Host num complete with invalid handle (in case the disconnection complete was not processed by the Host before sending the Host num complete, for example because they came at the same time over HCI)
> 
> I propose we implement both a) and b) which is exactly what #38056 is doing.

Your suggestions are sound. The spec is indeed unclear (possibly erratum-unclear?) about what the controller should do. If we intend on having a controller that's usable by other than the Zephyr host (i.e. one that is truly HCI compliant), we may still need to implement the solution for the controller (if that is indeed what the HCI spec states).
