### ISSUE TITLE
Can't get FlexPWM working for imxrt1060

### ISSUE THREAD

**Issue by ric96** [zephyrproject-rtos/zephyr#38954]
I'm trying the blinky_pwm sample for the teensy4 using the onboard LED. I've added an dt overlay to add the pwm bits which look like:
```
/ {
	pwmleds {
		compatible = "pwm-leds";
		external_pwm_led: external_pwm_led {
			pwms = <&flexpwm1_pwm1 0>;
		};
	};

	aliases {
		pwm-led0 = &external_pwm_led;
	};
};

&flexpwm1_pwm1 {
	status = "okay";
};
```

But i'm getting the following error on the console:

```
*** Booting Zephyr OS build v2.7.0-rc2-54-g2160e0fc364d  ***
PWM-based blinky
Calibrating for channel 0...
[00:00:00.009,000] <err> pwm_mcux: Too long period (1171875), adjust pwm prescaler!
[00:00:00.017,000] <err> pwm_mcux: Too long period (585937), adjust pwm prescaler!
[00:00:00.026,000] <err> pwm_mcux: Too long period (292968), adjust pwm prescaler!
[00:00:00.034,000] <err> pwm_mcux: Too long period (146484), adjust pwm prescaler!
[00:00:00.042,000] <err> pwm_mcux: Too long period (73242), adjust pwm prescaler!
Error: PWM device does not support a period at least 62500
```

**Comment by danieldegrasse** [comment]
@ric96 I'm assuming you're using an external pin and LED for the teensy board, as the onboard LED is routed to `GPIO_B0_03`, which does not have a MUX option for the PWM module:
![image](https://user-images.githubusercontent.com/34665051/153059113-e4cbe0ba-c495-436a-81c6-f3ca8f424ed1.png)
In that case, you will need to add a function call to `IOMUXC_SetPinConfig` to select the correct flexPWM module, based on what you define in your dts overlay.

Regardless of your specific setup for PWM on the teensy, the blinky PWM sample does not work on RT series SOCs (I reproduced the issue on an RT1064 EVK), because the pwm sample does not attempt to calibrate PWM with a short enough period. The RT series flexPWM module's source clock is too fast to support PWM at any frequency lower than roughly 18 Hz, and the blinky sample never tries to set up PWM with a frequency that is this high. The linked pull request increases the maximum frequency the sample will try to use from 16 Hz to 32 Hz, allowing it to run.
