### ISSUE TITLE
TTY injects '~' to the output on input errors

### ISSUE THREAD

**Issue by rgoliver** [zephyrproject-rtos/zephyr#39209]
**Describe the bug**
The TTY Rx IRQ injects a '~' character into the Tx when it drops data, this is not an obvious error code and creates a lot of confusion and debugging in order to figure out where these random bytes are coming from in the output stream.

This also makes the assumption that the bytes being transmitted are not encoded and being directly read by a human. When any level of encoding is used this random injection of bytes to the output by a low level driver confuses everything. 

**To Reproduce**
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/console/tty.c#L58

**Expected behavior**
Something which doesn't inject random bytes into the output stream. Possible solutions:

- log the error, using the log module which will correctly apply the required encoding for the channel. 
- raise a flag or keep a count of dropped bytes which can be checked and handled elsewhere.
- have a callback or handler
- make it configurable

**Impact**
It injects random data into our encoded output stream which will require a bunch or retry logic to properly handle. This adds even more traffic when the buffer was already dropping data... It makes a bad situation much worse.

**Comment by pfalcon** [comment]
Yes, it's true that tty subsys injects the error indicator in the form of `~` character into the output when input overrun is detected. This was done on following grounds:

1. Normally, for well-supported hardware, it should never happen.
2. However, it does happen on various HW platforms in Zephyr, especially during development.
3. When input overrun happens, the communication is already ruined and further interaction/outcome is errornuous.
4. However, it's ruined in a way not obvious to a user.
5. Thus the idea to make it immediately visible to a user.
6. It takes shape of injecting some UART output due to the fact that UART system is a very basic and foundational one, to avoid dependency on other subsystems. For example, it could light a LED via a GPIO, but a hardware which has support only for UART (and no GPIO or anything else) is a pretty valid one.

So responding to the points in the original comment:

> this is not an obvious error code 

Well, there's no obvious error code for such a foundational issue. `~` was selected because it's usually typed rarely by a user. (Multi-byte sequence wasn't used to avoid possibility of output overrun or latency/deadlock amplification). Once you faced the situation once, it's easy to remember what it means. Perhaps it should be documented somewhere however.

> and creates a lot of confusion and debugging

I'm sorry, but I disagree. Symptomless loss of input for no apparent reason is what created and creates a lot of confusion and debugging. That's how `~` was added in the first place.

> This also makes the assumption that the bytes being transmitted are not encoded and being directly read by a human.

No, per above, that's not the assumption being made. The assumption is that in well-developed system (suitable for automated communication over UART), this issue never happens. But while a system is being developed - yes, it's being operated by a human, who has an easy chance to spot that something's wrong.

> When any level of encoding is used this random injection of bytes to the output by a low level driver confuses everything.

I don't see how random loss of input data creates less opportunity for a low-level driver confusion. In general, any communication channel is only so much reliable, and UART is not too much reliable at all. An automated agent (like driver) should be ready for anomalous output.

> this random injection of bytes 

Per above, it's not random, but quite deliberate.


> log the error, using the log module which will correctly apply the required encoding for the channel.

UART is foundational system and default logging happens using it. Thus it would create the issue of output amplification (one character pressed and lost, dozens of bytes being output), which may affect the system functioning in the first place.

> raise a flag or keep a count of dropped bytes which can be checked and handled elsewhere.
> have a callback or handler

All that is not obvious to a user. Remember, in well-developed system the issue should not happen at all.

> make it configurable

That's the only solution I personally find reasonable, as long as the default is on. Because again, that was intended as the basic debugging aid for bringing up and testing a new systems and configuration. Such an option would be also a good place to document this behavior.

> This adds even more traffic when the buffer was already dropping data... It makes a bad situation much worse.

Again I disagree. It was carefully designed to avoid output amplification (so, in a typical "echo" scenario, a user would get 1 output byte for each input byte - whether an actual input byte, or an error indicator that input was lost). And it makes bad, but sadly, fairly typical situation, easily debuggable.
