### ISSUE TITLE
net_buf and net_buf_simple need to be combined into a single type...

### ISSUE THREAD

**Issue by jimvert** [zephyrproject-rtos/zephyr#40562]
net_buf and net_buf_simple should be abstracted into a single type instead of have two types.  The differences should be abstracted away from the developer.  Right now, it's difficult to maintain a consistent application-level API having two different types.

**Comment by carlescufi** [comment]
@jhedberg assigned to you, any thoughts on the matter?

**Comment by jhedberg** [comment]
I don't see how they could be abstracted to a single type, since they don't implement the same APIs (net_buf is a superset of net_buf_simple), i.e. if you have a net_buf_simple, you can't pass it to APIs that expect a full net_buf. For the other direction, you can get a net_buf_simple out of a net_buf with: `struct net_buf_simple *simple = &buf->b`.
