### ISSUE TITLE
west flash, Invalid DFU suffix signature

### ISSUE THREAD

**Issue by gewoods3** [zephyrproject-rtos/zephyr#40714]
**Describe the bug**

1. west build -p auto -b adafruit_feather_stm32f405 samples/basic/blinky
2. west flash
3. see error
```
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
```

I reported this to http://sourceforge.net/p/dfu-util/tickets/
#129 Invalid DFU suffix signature, Zephyr, adafruit_feather_stm32f405
Response:

"This is an issue with the firmware file. You should ask the provider of the firmware file to include a DFU suffix. It helps to make sure firmware files are only downloaded to the right type of device, so that a user doesn't download it to a wrong device by accident. Currently dfu-util doesn't refuse to use the file even it lacks the suffix."

**Expected behavior**
No error.

**Impact**
annoyance, future showstopper: "A valid DFU suffix will be required in a future dfu-util release!!!"

**Comment by jfischer-no** [comment]
This is not related to USB device support in Zephyr, STM32F405 has built-in ROM USB DFU bootloader.
Could be west runner issue, but since there are not further details here except "A valid DFU suffix will be required in a future dfu-util release!!!", which has been around for many years and  "Currently dfu-util doesn't refuse to use the file even it lacks the suffix", I close it.
