### ISSUE TITLE
LE Audio: Use BT_MEDIA_PROXY values instead of BT_MCS

### ISSUE THREAD

**Issue by Thalley** [zephyrproject-rtos/zephyr#41197]
Use MEDIA_PROXY defines instead of BT_MCS defines in implementation where suitable.
Note: Also involves evaluating CONFIG names

2021-11-16:
Addition: Use BT_MCC, not BT_MCS, for client functions

**Comment by asbjornsabo** [comment]
It has previously been agreed that the media_proxy.h should define separately the same values as defined by mcs.h (in analogy with HCI, I believe).  This has been done.

"where suitable":
- the media_proxy.h defines the MEDIA_PROXY_* values, and should of course use these (instead of BT_MCS).
- the mpl.c should use the MEDIA_PROXY_* values, not the BT_MCS ones.

mcs.c and mcc.c should use the BT_MCS ones.
