### ISSUE TITLE
periodic_adv periodic_sync lost data

### ISSUE THREAD

**Issue by jenifer-su** [zephyrproject-rtos/zephyr#41777]
Hello,
i've two 52840DK,Windows10 X64,
D:\Program\ncs_v1.8.0\zephyr\samples\bluetooth\periodic_adv\
D:\Program\ncs_v1.8.0\zephyr\samples\bluetooth\periodic_sync\
using the BLE Zephyr controller.
now it work well,but when i change the interval time to 1s,
periodic_sync lost data packet 4 and 7. often lost.
how to advertising/receive continuous data (one by one and there is no repetition)?
how to change data lenght to big than 94?
and next i will change the timer interval 20ms,Is that ok?
![image](https://user-images.githubusercontent.com/549638/149276234-53272470-6f3d-4b5e-8f5d-a6237abeea7f.png)

![image](https://user-images.githubusercontent.com/549638/149276268-d1526372-f641-458d-bdf7-dfa6adc68082.png)

![image](https://user-images.githubusercontent.com/549638/149276884-9a08817c-aa96-497e-8043-2c7a55ae80b2.png)

thanks
Best regards,

**Comment by jenifer-su** [comment]
Hello,

I have found the problem because the data + 1 is modified before send complete(occasionally). The sent callback function needs to be enabled and the data can be modified after send complete. However, the sent callback function is not entered at present and the reason is being found. please view to 

[nRF Connect SDK1.8.0 periodic_adv no recv callback - Nordic Q&A - Nordic DevZone - Nordic DevZone (nordicsemi.com)](https://devzone.nordicsemi.com/f/nordic-q-a/83770/nrf-connect-sdk1-8-0-periodic_adv-no-recv-callback)


thanks
Best regards,

**Comment by carlescufi** [comment]
What you want to achieve is not really possible, because there is no guarantee of delivery for extended advertising packets, it's all best effort and some packets might be missed by the scanner, since there are no retransmissions to ensure all data reaches the scanner. Also, the application would have to be in sync with the clocks/timing of the controller to make sure it fits all slots with different indices.
