### ISSUE TITLE
CPU load halfed after PR #40784

### ISSUE THREAD

**Issue by alexsven** [zephyrproject-rtos/zephyr#41792]
**Describe the bug**
I noticed that the idle thread in simple samples like blinky is showing 49% cpu load. When checking out the commit just before the PR it shows 99% (as it should).
(https://github.com/zephyrproject-rtos/zephyr/pull/40784)

I've tested blinky for both nRF52840 and nRF5340, both show 49% CPU load for idle after PR, and 99% before the PR.

This PR was submitted by @peter-mitsis

**Comment by peter-mitsis** [comment]
Investigating ....

**Comment by peter-mitsis** [comment]
Alex,
What steps are you using to reproduce the problem? I ask because I am currently having difficulties just trying to build the blinky sample for the specified boards.

I've been trying to use ...
    west build -p -b <board name> ./samples/basic/blinky
... to just get a basic build of the sample project but it is giving me Kconfig build errors, for every board name that contains nrf52840 that I have tried so far.  At this point, I am assuming that either I have been picking the wrong board, and/or I have a knowledge gap.

**Comment by nashif** [comment]
`west build -b nrf52840dk_nrf52811  ./samples/basic/blinky` works fine...

**Comment by alexsven** [comment]
I used 
`west build -b nrf52840dk_nrf52840`
and 
`west build -b nrf5340dk_nrf5340_cpuapp`
depending on the board of course

**Comment by nordic-krch** [comment]
I am able to reproduce it on qemu_86 and qemu_86_64.
For reference, commit before the break: 0bd3d46cfb86021629bc505f8ebfa3d949a20437.
Application i used: https://github.com/zephyrproject-rtos/zephyr/commit/36c210e06b424d34b837160e98cc45e3e4d400fc

Prints 0.0% on 0bd3d46cfb86021629bc505f8ebfa3d949a20437 and
```
Hello World! qemu_x86_64
load: 57.4%
load: 60.1%
load: 61.6%
load: 62.6%
load: 100.0%
```
on lastest.

**Comment by peter-mitsis** [comment]
I'm able to duplicate it now--also on qemu_x86.

**Comment by peter-mitsis** [comment]
I found at least one issue related to the updating of the system's thread_runtime_stats.
   - The total cycles (non-idle) is including the number of idle cycles.

Consequently, the system's execution cycles (sum of total_cycles and idle cycles) ultimately includes the idle cycles twice.
