### ISSUE TITLE
docs: sphinx-build issue, zephyr conf.py issue or something else? 

### ISSUE THREAD

**Issue by mkschreder** [zephyrproject-rtos/zephyr#42573]
**Describe the bug**
There is a strange behavior on all zephyr versions where sphinx-build, when invoked directly from the doc folder deletes all files in the doc/_* folders. 

**To Reproduce**
Using sphinx version 3.3.1:
1. cd doc
2. sphinx-build . output
3. ls -la _scripts

The result is that 42 files under doc are deleted. 

```
$ git checkout doc 
Updated 42 paths from the index
```

**Expected behavior**
This unexpected deletion should never happen.

**Impact**
rst-sphinx syntax checking in emacs calls sphinx-build and results in files being deleted after just opening and editing doc/index.rst

I understand that proper way to invoke the build is through make, but dry running sphinx-build should not delete files and why is sphinx behaving this way? Is this a problem with sphinx-build or the zephyr config?

**Comment by gmarull** [comment]
Documentation should be built according to the procedures described here:
https://docs.zephyrproject.org/latest/guides/docs/index.html

Direct invocation of sphinx-build is not supported, since CMake generates some necessary files first. This may eventually change when Kconfig/DT docs are integrated into the regular Sphinx workflow. For the necessary sphinx-build CLI args, please check `doc/CMakeLists.txt`.
