### ISSUE TITLE
Inconsistent logging config result resulted from menuconfig.

### ISSUE THREAD

**Issue by smrtos** [zephyrproject-rtos/zephyr#43095]
**Describe the bug**
Inconsistent logging config result resulted from menuconfig.

**To Reproduce**
1. cd zephyr
2. cmake -B build -S samples/hello_world/ -GNinja -DBOARD=qemu_x86_64
2. cd build
3. ninja menuconfig
4. Check logging and enter the logging sub menu. It looks like this now:
![image](https://user-images.githubusercontent.com/54129187/155255256-1cb75963-59a2-4ecc-b8db-1900217f57e6.png)
5.  Check "Synchronous v2 (DEPRECATED)".  The "Mode" field will also change.  This is as expected.
     Shown as below:
![image](https://user-images.githubusercontent.com/54129187/155255430-0a0774a5-96df-448c-8407-3389669d1851.png)

6. Enter Mode submenu. Check "Deferred logging". As below:
![image](https://user-images.githubusercontent.com/54129187/155255530-91e08ea3-a5fa-4acd-ac88-eebd7ce283af.png)

7. Press ESC to return to parent menu. Now it shows inconsistent result as both deferred and synchronous:
![image](https://user-images.githubusercontent.com/54129187/155255664-ad0f99c5-b7a1-4221-9f14-6a79136c2da1.png)

8. Check the final effective zephyr/.config file. The inconsistency is persisted.
![image](https://user-images.githubusercontent.com/54129187/155255829-f971cd6d-242e-44a1-a8cf-27b62088974a.png)

**Expected behavior**
Only one logging mode should be displayed as chosen in menuconfig and  persisted in .config file.

**Comment by carlescufi** [comment]
@tejlmand is this an instance of the [stuck symbol problem](https://docs.zephyrproject.org/latest/guides/build/kconfig/tips.html#stuck-symbols-in-menuconfig-and-guiconfig)?

**Comment by tejlmand** [comment]
@smrtos this happens because of the deprecation of those symbols introduced with this PR #41755 .

@nordic-krch will you take a look at this ?
Initial look at the Kconfig indicates to me that maybe `choice LOG_MODE` should `depends on !<DEPRECATED_SYMBOLS>` so that if user selects any of the deprecated symbols, then it's not possible to also select a choice item.

But I think you are the best to judge the intentions with the deprecation introduced with https://github.com/zephyrproject-rtos/zephyr/pull/41755

**Comment by nordic-krch** [comment]
Fixed a bit dependencies. @smrtos note that options are deprecated and not recommended to be used. They were added only to support case when someone already had them set in `prj.conf`.
