### ISSUE TITLE
Missing SPI SCK on STM32F103vctx

### ISSUE THREAD

**Issue by calaghann** [zephyrproject-rtos/zephyr#43452]
**Describe the bug**
A custom board using stm32F103vctx MCU uses SPI1 with remaped sck pin pb3 does not output any clock signal. The SPI1 peripheral was used and configured with the stm vendor dts / dtsi. However once I tried to sent out some SPI commands using the stm spi driver I noticed that no spi clock signal is emitted on pb3 (using an oscilloscope). The other spi signals (MOSI, MISO and nCS on pb4, pb5 and pb8) are correctly pushed by the stm spi driver. 
A quick implementation using only STM HAL produces the same register contents of the affected register banks GPIOB, AFIO, and SPI1. However using STM HAL the clock signal is emitted correctly on pb3. 

**To Reproduce**
1. Grab a plattform using a stm32F103 MCU (preferably stm32F103vctx)
2. configure SPI1 in the dts e.g. like this
`pinctrl-0 = <&spi1_sck_master_pb3 &spi1_miso_master_pb4 &spi1_mosi_master_pb5>;
	cs-gpios = <&gpiob 8 (GPIO_ACTIVE_LOW)>;
        pinctrl-names = "default";
	status = "ok";
`
4. try to send something on SPI using stm spi driver and `spi_transceive_dt`
5. measure spi clock on pb3 (e.g by using oscilloscope or logic analyzer)

**Expected behavior**
SPI communication with remapped Pins pb3, pb4 and pb5 is working

**Impact**
In that case no SPI communication can be established which is a show stopper on my board right now. 

**Environment (please complete the following information):**
 - OS: Windows
 - Toolchain Zephyr SDK
 - Commit SHA 49d08c25

**Comment by FRASTM** [comment]
when remapping the SPI1 (REMAP_1), I suspect a pin conflict between SPI1 and DEBUG pins
PB3 and JTDO
PB4 and NJTRST 

--> if SPI1 is remapped then` LL_GPIO_AF_DisableRemap_SWJ(); ` or or` LL_GPIO_AF_Remap_SWJ_NOJTAG();`

**Comment by calaghann** [comment]
Thanks for your update. We had a further look into that and found the config option `GPIO_STM32_SWJ_NOJTAG`. After setting this option we were able to see the clock (so pin conflict seems the right idea). Unfortunately after that we were not able to debug with SWD - the program is getting stuck in the ARM reset (reset.S).

**Comment by GeorgeCGV** [comment]
This is the same issue as #38354 and relates to the #38741 PR (regarding AFIO and SWJ).

Unfortunately, the issue doesn't seem to be resolved in the latest Zephyr.
Setting the `CONFIG_GPIO_STM32_SWJ_NOJTAG`  results in getting stuck within `z_arm_reset`. When `SWJ_CFG` is left unchanged, then PB3 can't be used as SPI 1 SCK pin.

**Comment by erwango** [comment]
> Setting the `CONFIG_GPIO_STM32_SWJ_NOJTAG` results in getting stuck within `z_arm_reset`.

Do you get the same issue even when not using SPI1 at all (eg: hello_world)?

**Comment by GeorgeCGV** [comment]
> > Setting the `CONFIG_GPIO_STM32_SWJ_NOJTAG` results in getting stuck within `z_arm_reset`.
> 
> Do you get the same issue even when not using SPI1 at all (eg: hello_world)?

yes

**Comment by erwango** [comment]
@GeorgeCGV Thanks for the investigation and finding the issue!
For the fix, I suggest to purely remove `gpio_stm32_afio_init` and move its logic directly in `pinctrl_stm32.c` (and `pinmux_stm32.c` while it's still there).

**Comment by GeorgeCGV** [comment]
The PR is created. I can confirm that the SPI 1 SCK signal is present on PB3. Unfortunately, we still didn't manage to communicate with the other IC over the SPI 1 on F1VC (_L5 manages to communicate with that IC, so it is not a custom driver issue_), investigating further...

Some notes:

HAL and LL don't disable the `LL_APB2_GRP1_PERIPH_AFIO` clock.

There is a difference in the order of how SWJ and remap are being set between HAL and LL:
* HAL
  * Enables the clock and disables JTAG in `HAL_MspInit` (`HAL_Init`)
  * Enables remap **after** GPIO initialization
* LL
  * Enables the clock and disables JTAG
  * Reads `MAPR` and awaits `AFIO_MAPR_SWJ_CFG_JTAGDISABLE` to be set (`SWJ_CFG` part, it supposed to be **write-only**).
  * Enables remap **before** GPIO initialization

**Comment by GeorgeCGV** [comment]
Everything works now.

![works](https://user-images.githubusercontent.com/5956504/157987316-c356ec7e-48a4-4403-9b29-af8fef343202.PNG)

What helped is the usage of  `AFIO_MAPR_SWJ_CFG` (`111`) during every remap setting and not disabling the `AFIO` clock after the SWJ initialization.

Unfortunately, it is unknown how setting the `AFIO_MAPR_SWJ_CFG` (`111`) helps. However, HAL and LL do the same.

For example:

```
__STATIC_INLINE void LL_GPIO_AF_EnableRemap_SPI3(void)
{
  SET_BIT(AFIO->MAPR, AFIO_MAPR_SPI3_REMAP | AFIO_MAPR_SWJ_CFG);
}
```

As for the initialization and the clock - now it is similar to the HAL. `AFIO` clock is enabled, then comes the `SWJ_CFG` application, then remap happens later on (*if required*).

> purely remove gpio_stm32_afio_init

The SWJ initialization was moved into `pinctrl` and `pinmux` modules. 

I don't think that we shall get rid of the `SYS_INIT` approach. There might be a case when no remap is used but someone needs some IO pin that is occupied by the JTAG or SWD in the project. Therefore, we have to provide a way to free the desired pin (_e.g. <kbd>PB4</kbd>, <kbd>PA15</kbd>, etc..._).

The PR also follows your suggestion regarding the DTS usage instead of Kconfig for the SWJ. That makes more sense, as it is a setting that is more or less F1 specific.
