### ISSUE TITLE
Bluetooth: Use hardware encryption for encryption

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#44281]
I noticed that `bt_encrypt` uses `tc_aes` is used for software encryption. Why not use HCI to hand over to the controller for hardware encryption? This saves a lot of CPU occupation and stack space, and can improve the sending and receiving performance of mesh

**Comment by carlescufi** [comment]
cc @trond-snekvik @jhedberg @joerchan

**Comment by carlescufi** [comment]
As far as I know, no particular reason other than no one has implemented it yet. On Nordic devices we do use the hardware encryption, but directly and not via HCI.

**Comment by jhedberg** [comment]
@LingaoM I'd be surprised if HCI over a physical transport is faster than doing the calculation on the local CPU. It sounds like the cipher is not properly optimised or you have a slow CPU. Normally, when optimizing execution one tries minimize IO-bound operations, but this would do the opposite.

**Comment by joerchan** [comment]
What kind of setup is this anyway?

In zephyr we have a method for faster encryption / rand through the BT_CTLR_CRYPTO instead of BT_HOST_CRYPTO.
Only use-case for this feature request is in a host-only build where you want save code-space by not having encryption in the host image.
Offloading encryption to the controller chip in this case is highly unlikely to result in any sending or receiving performance increase.
