### ISSUE TITLE
samples: net: ieee802154: Sample is not working on nRF52840 platform

### ISSUE THREAD

**Issue by KaSroka** [zephyrproject-rtos/zephyr#4442]
net/ieee802154 sample is not working on nRF52840, I will take a look at it when updating Nordic's 15.4 driver to the latest version.

**Comment by dleach02** [comment]
What is the failure?

Note that I had to increase the stack size for the main thread in the echo sample while working on the NXP KW41Z 15.4 driver. 

I bumped both of these but not sure where these should be set by default since I believe they are impacted by the protocol stacks in play which can change:

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

**Comment by tbursztyka** [comment]
the sample does not exist any-more so, closing
