### ISSUE TITLE
intel_adsp: kernel.common tests are failing

### ISSUE THREAD

**Issue by yerabolu** [zephyrproject-rtos/zephyr#44758]
**Describe the bug**
kernel.common tests are failing on intel_adsp25/18/15 .

**To Reproduce**
1. twister -W -p intel_adsp_cavs25 --device-testing --device-serial-pty=$HOME/zephyrproject/zephyr/soc/xtensa/intel_adsp/tools/cavstwist.sh --west-flash=$HOME/zephyrproject/zephyr/soc/xtensa/intel_adsp/tools/cavstwist.sh -T tests/kernel/common/ -vvv
2. See error

Tests started failing after the commit:  b1182bf8 got merged. 

**Logs and console output**
```
Running test suite common
===================================================================
START - test_bootdelay
PASS - test_bootdelay in 0.1 seconds
===================================================================
START - test_irq_offload
PASS - test_irq_offload in 0.1 seconds
===================================================================
START - test_nested_irq_offload
Assertion failed at WEST_TOPDIR/zephyr/tests/kernel/common/src/irq_offload.c:209: nestoff_timer_fn: (nested_executed is false)
nested irq_offload did not run
```
**Environment (please complete the following information):**
 - OS: Fedora
 - Toolchain (e.g Zephyr SDK, ...): SDK 13.2
 - Commit SHA: 37e561f42e52

**Additional context**
After git bisect, tests started failing after commit:  b1182bf8.

**Comment by andyross** [comment]
Got it.  It was the outer lock around the timeout handling; it disables interrupts (duh, that's the point), but our irq_offload() test case actually relies on a synchronous interrupt triggering while a k_timer handler (in the timer ISR!) is running, so it broke.   That's arguably a sloppy test case, and it would be good if we were to specify how irq_offload() is supposed to work, but that outer lock was sort of a mess anyway, so that's where we want to fix it.  The newer code is better in all ways anyway.
