### ISSUE TITLE
twister  : frdm_k64f ：the test case tests/subsys/logging/log_switch_format/logger.syst.v2.immediate/ blocks 

### ISSUE THREAD

**Issue by shaoanxli** [zephyrproject-rtos/zephyr#46368]
**Describe the bug**
When running the twister command , the test case blocks at "SYST Sample Execution Completed". And the test case add in this commit: 1c1748d5795ced54cbf2b8242b0d4010cbf1781e. Before the DEVICE log, there is a DEBUG log "DEBUG   - Could not find a matching testcase for logger.syst.v2.immediate" ,this may provide a clue.

**To Reproduce**
1. source zhephyr-env.sh
2. twister -p frdm_k64f --device-testing --hardware-map map.yml -T tests/subsys/logging/log_switch_format/ -vv
3. See error

**Expected behavior**
The test log goes pass as expected.

**Impact**
The test blocks at "SYST Sample Execution Completed".

**Logs and console output**
```
*** Booting Zephyr OS build zephyr-v3.1.0-165-g90537fe447d6  ***
Running TESTSUITE test_log_switch_format
===================================================================
START - test_log_switch_format_success_case
SYS-T RAW DATA: 220A000B1700C0000000000000004572726F72206D657373616765206578616D706C652E00
hello sys-t on board frdm_k64f
[00:00:00.029,000] ^[[1;31m<err> log_switch_format: Error message example.^[[0m
hello sys-t on board frdm_k64f
SYS-T RAW DATA: 220A000B17008B010000000000004572726F72206D657373616765206578616D706C652E00
hello sys-t on board frdm_k64f
SYST Sample Execution Completed
```

**Environment:**
OS: Linux,
Toolchain Zephyr SDK 0.14.1
Commit SHA or Version: 0a758c36c864cc138941848f42c8ea4aa7dc95b3

**Comment by fabiobaltieri** [comment]
@aasthagr could you look into this?

**Comment by aasthagr** [comment]
Sure, I will take a look.

**Comment by aasthagr** [comment]
The testcase tests/subsys/logging/log_switch_format/logger.syst.v2.immediate does pass. It doesn't fail or is not blocked as it executes till the "PROJECT EXECUTION SUCCESSFUL" and twister does indicate it as a passing testcase. See below:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/48465656/173749069-95eedaed-f384-467d-9927-5ebba1f5cd17.png">

I do see the line below in logs which you have indicated, but its just a DEBUG log. I am not sure what that means though, because the testcase is identified and executed by twister:
DEBUG   - Could not find a matching testcase for logger.syst.v2.immediate

**Comment by shaoanxli** [comment]
Sorry maybe the description is not very accurate, this should really be the problem of twister. This problem is only seen when using the twister command.
