### ISSUE TITLE
openthread net_mgmt_event_callback expects event info.

### ISSUE THREAD

**Issue by KenMacD** [zephyrproject-rtos/zephyr#46594]
**Describe the bug**

When a feature enables `CONFIG_NET_MGMT` (for example `CONFIG_NET_DHCPV4`) openthread will fail to compile with the error:

```
Building C object zephyr/subsys/net/l2/openthread/CMakeFiles/subsys__net__ip__l2__openthread.dir/openthread.c.obj
...zephyr/subsys/net/l2/openthread/openthread.c: In function 'ipv6_addr_event_handler':
...zephyr/subsys/net/l2/openthread/openthread.c:125:8: error: 'struct net_mgmt_event_callback' has no member named 'info'
  125 |  if (cb->info == NULL || cb->info_length != sizeof(struct in6_addr)) {
      |
```

This is happening with version 3.0.99, but appears to be unchanged.

The [code in openthread.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/l2/openthread/openthread.c#L113=) is wrapped with a check for `CONFIG_NET_MGMT_EVENT`, but then goes on to access fields that are only available if `CONFIG_NET_MGMT_EVENT_INFO` is also set.

As a workaround `CONFIG_NET_MGMT_EVENT_INFO=y` can be specified directly in the project config.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain: nrf 2.0.0 using gcc-arm-embedded to compile

**Comment by rlubos** [comment]
@KenMacD I've submitted a PR that fixes the build error in case `CONFIG_NET_MGMT_EVENT_INFO` is disabled. I've originally wanted to enforce `NET_MGMT`/`NET_MGMT_EVENT`/`NET_MGMT_EVENT_INFO` with select when OpenThread is enabled, but it's not really viable since not all applications would need this (for instance RCP). Therefore it should be application responsibility to enable them if needed.
