### ISSUE TITLE
on x86, k_is_in_isr() returns false in execption context

### ISSUE THREAD

**Issue by inteljiangwe1** [zephyrproject-rtos/zephyr#47081]
For k_is_in_isr() description, it checks whether the code is running at interrupt level. And it is used by caller to customize the behavior, like avoiding take semaphare in isr handler.
But on execption context, it returns false in execption context on x86

**Comment by inteljiangwe1** [comment]
@peter-mitsis any comments?

**Comment by peter-mitsis** [comment]
@inteljiangwe1 - Apologies for the late reply. My attention had been focussed on other issues tagged as higher priority. However, I now have a small window to take a look at this before I jump onto the next priority item.

**Comment by peter-mitsis** [comment]
To fix or not to fix, that is the question.

I've spent the last couple of hours getting somewhat re-acquainted with this code as a fair bit has happened since I last looked at this code (over 5 years ago).  If I am following things correctly, this appears to be by design, and this will probably fall under "do not fix". (To be clear, this is not a final verdict; it is just an early indicator.)  I will still need to dig a little further, consult and confirm that I have the right mental model before I can say for sure. Either way, I expect to add a comment that will explain why.

**Comment by peter-mitsis** [comment]
So I did some more digging. Exceptions, unlike interrupts, are handled at thread level. They may do things that interrupts are not allowed to do such as block on a resource.

I am certain now that this issue qualifies as a "Do Not Fix".

**Comment by peter-mitsis** [comment]
Although there are similarities between exceptions and interrupts, on x86 they are sufficiently different such that k_is_in_isr() returns false inside an exception handler (unless the exception occurred during the handling of an interrupt).

**Comment by inteljiangwe1** [comment]
thanks Mitsis for explaination
@kwd-doodling for awareness
