### ISSUE TITLE
Enhance Testing and Test Coverage

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#5027]
We should shift focus to quality of tests rather than quantity…
- [ ] Every API needs to be tested and verified
- [ ] Advanced Use Case testing
   - [ ] 100s of threads
   - [ ] Determinism
   - [ ] Using External IO
   - [ ] Heavy Load, MTBF style testing
- [ ] Implement mechanism to detect APIs not being documented or tested
- [ ] Implement coverage analysis 
   - [ ] Using native port
   - [ ] Using gcov tricks on target platforms and Qemu (via GDB)

**Comment by marc-hb** [comment]
Related (or even duplicate for some?)

Enhance Testing and Test Coverage #5027
Provide a mean to find tests with 0 platforms due to bad filtering #652
No test builds these files #12860
need to improve filtering and coverage in sanitycheck #6857
Suspicious PCI and build_on_all default test coverage #15604
