### ISSUE TITLE
Bluetooth: RPA expired callback inconsistently called

### ISSUE THREAD

**Issue by joerchan** [zephyrproject-rtos/zephyr#51247]
**Describe the bug**
The RPA expired callback is inconsistently called for advertising sets.
1. RPA expired callback called on advertising set using its identity address if there is another user of RPA timer
2. RPA expired callback called on disabled advertising set if there is another user of the RPA timer.

Added the RPA expiration callback to the shell in order to demonstrate the issues.
```
diff --git a/subsys/bluetooth/shell/bt.c b/subsys/bluetooth/shell/bt.c
index 7c4a630d58..7ecd803eb1 100644
--- a/subsys/bluetooth/shell/bt.c
+++ b/subsys/bluetooth/shell/bt.c
@@ -274,6 +274,24 @@ static void adv_connected(struct bt_le_ext_adv *adv,
                    bt_le_ext_adv_get_index(adv), adv, str);
 }
 #endif /* CONFIG_BT_PERIPHERAL */
+#if defined(CONFIG_BT_PRIVACY)
+static int rpa_expire_count = 3;
+static bool adv_rpa_expired(struct bt_le_ext_adv *adv)
+{
+               shell_print(ctx_shell, "Advertiser[%d] %p RPA expired",
+                   bt_le_ext_adv_get_index(adv), adv);
+
+               return true;
+}
+#endif /* defined(CONFIG_BT_PRIVACY) */
+
 #endif /* CONFIG_BT_EXT_ADV */
 
 #if !defined(CONFIG_BT_CONN)
@@ -563,6 +581,10 @@ static struct bt_le_ext_adv_cb adv_callbacks = {
 #if defined(CONFIG_BT_PERIPHERAL)
        .connected = adv_connected,
 #endif /* CONFIG_BT_PERIPHERAL */
+#if defined(CONFIG_BT_PRIVACY)
+       .rpa_expired = adv_rpa_expired,
+#endif /* defined(CONFIG_BT_PRIVACY) */
```

Reproduce:
```
west build -b nrf52840dk_nrf52840 ../zephyr/tests/bluetooth/shell  -- \
-DCONFIG_BT_PRIVACY=y \
-DCONFIG_BT_LOG_SNIFFER_INFO=y \
-DCONFIG_BT_RPA_TIMEOUT=10
```

1. RPA expired callback called on advertising set using its identity address if there is another user of RPA timer
```
uart:~$ bt fal-add F4:3C:20:48:15:CA (random)
uart:~$ bt scan on fal
Bluetooth active scan enabled
uart:~$ bt adv-create conn-scan identity
Created adv id: 0, adv: 0x20002348
uart:~$ bt adv-start
Advertiser[0] 0x20002348 set started
Advertiser[0] 0x20002348 RPA expired
Advertiser[0] 0x20002348 RPA expired
uart:~$ bt scan off
Scan successfully stopped
# No more RPA expirations
```

2. RPA expired callback called on disabled advertising set if there is another user of the RPA timer.
```
uart:~$ bt fal-add F4:3C:20:48:15:CA (random)
uart:~$ bt scan on fal
Bluetooth active scan enabled
[00:00:46.310,302] <inf> bt_id: bt_id_set_private_addr: RPA: 53:CD:C2:A9:A3:2F
uart:~$ bt adv-create conn-scan
Created adv id: 0, adv: 0x20002348
[00:00:52.830,261] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 47:58:00:75:D4:7B
uart:~$ bt adv-start
Advertiser[0] 0x20002348 set started
Advertiser[0] 0x20002348 RPA expired
[00:01:46.321,044] <inf> bt_id: bt_id_set_adv_private_addr: RPA: 5E:4C:64:18:35:F2
uart:~$ bt adv-stop
Advertiser set stopped
Advertiser[0] 0x20002348 RPA expired
Advertiser[0] 0x20002348 RPA expired
uart:~$ bt scan off 
Scan successfully stopped
# No more RPA expirations
```

**Expected behavior**
The rule for when an RPA expiration callback should be called should not be dependent on other roles running.

**Impact**
Applications must track their own state of the advertiser enabled, or if using identity address.

**Environment (please complete the following information):**
 - Commit SHA or Version used: zephyr 3.2.0 release + shell modification.

**Comment by kapi-no** [comment]
Ad 2.

If you trigger the rpa_expired callback only for the enabled set, then it's impossible for the API user to check if the advertising payload should also be rotated once the advertising is restarted from the disabled state. In this corner case, they will miss the RPA rotation notification that is scheduled by the global timeout for all advertising sets. IMO, the API user should have total control over RPA rotation for their advertising set.

> Expected behavior
The rule for when an RPA expiration callback should be called should not be dependent on other roles running.

It had been already dependent before the addition of the ```rpa_expired``` callback because all advertising sets share the same global timeout. In this case, some other enabled advertising set can invalidate the RPA for the disabled advertising set (dependency on other roles). Without the ```rpa_expired```  callback execution, the user of the disabled set does even know that its RPA has changed.
