### ISSUE TITLE
mgmt: mcumgr: Improve fs_mgmt file upload/download

### ISSUE THREAD

**Issue by nordicjm** [zephyrproject-rtos/zephyr#52075]
**Is your feature request related to a problem? Please describe.**
At present, the fs_mgmt upload/download functions are self contained, this means that for each command, the underlying file is opened, seeked to the desired offset, and data read/written, then the file is closed. This works, but has an enormous overhead, reducing the throughput by roughly 6 times. This can be improved by keep the file handle open (optionally, via Kconfig) so that if the same file is written to/read from, it uses the existing object without needing to open or close it, this will vastly speed up file transfers.

Also the file access hook can be simplified to run once upon file being opened or closed, instead of for each read/write.

Note that this will require locking the file object to a specific transport, to prevent data leaking or access by a different transport/connection.

**Describe alternatives you've considered**
Leaving it as is.

**Comment by de-nordic** [comment]
NFS does the same thing. The problem is that it is hard to tell when operation will end and how long should the file handle be opened. This will add requirements for additional timeout mechanism to close the file handle when connection breaks too long.
Currently when you can resume uploading file, as long as device does not get reset, anytime you want.
