### ISSUE TITLE
Cannot build apps with main in a .cpp file

### ISSUE THREAD

**Issue by yperess** [zephyrproject-rtos/zephyr#52376]
See https://github.com/zephyrproject-rtos/zephyr/pull/52375 for a sample.

The issue (I think) is with how the linker renames the main function in C++ binaries. Though I have no expertise in how this is done or things related to the linker.

Setting priority high since this is blocking all our downstream projects using C++ (everything that's building with Pigweed and work in progress on CHRE).

**Comment by stephanosio** [comment]
We have a sample that builds with `main` in a C++ source file and it seems to be working fine (even on `native_posix`):
https://github.com/zephyrproject-rtos/zephyr/blob/84c09433b574b40a7d673fb47a1600c64b1d57c8/samples/subsys/cpp/cpp_synchronization/src/main.cpp#L133

Maybe you forgot to enable `CONFIG_CPP_MAIN=y`?

**Comment by yperess** [comment]
I see that now, is there a reason this Kconfig wasn't defaulted to `y`? This broke a lot of projects downstream.

**Comment by yperess** [comment]
Changed priority to low

**Comment by stephanosio** [comment]
> I see that now, is there a reason this Kconfig wasn't defaulted to `y`? This broke a lot of projects downstream.

See https://github.com/zephyrproject-rtos/zephyr/pull/51966#issue-1436262818

> p.s. CONFIG_CPP_MAIN is not default y when C++ support is enabled because it is common to have main() implemented in a C source file for Zephyr applications even when C++ support is enabled.

**Comment by yperess** [comment]
I guess it's one of those "now that I know". I disagree with the idea that it's "common" all of our projects are either 100% C, or migrating to 100% C++. It's possible that I'm more limited in my understanding of the cpp subsystem on Zephyr, but I always find it odd that I need to enable `CONFIG_CPLUSPLUS=y` for the projects, I always expected the build system to just know it's there similar to how we use `#ifdef __cplusplus`. Adding yet another odd thing to C++ is a bit frustrating.

The short of it is I would really like that Kconfig to be defaulted to `y`, but I'm not about to argue it, the overhead of starting a new project is really just remembering a bunch of boiler plate Kconfigs.

**Comment by stephanosio** [comment]
> I guess it's one of those "now that I know"

Sure, it is fairly new; but, it has also been documented for those are new to Zephyr and looking to use C++ in their application:

https://github.com/zephyrproject-rtos/zephyr/blame/main/doc/develop/languages/cpp/index.rst#L27-L31

> I disagree with the idea that it's "common" all of our projects are either 100% C, or migrating to 100% C++.

If you ask most people who are developing Zephyr applications (or who develop embedded applications for microcontrollers in general), I am sure they will say what you are doing is something out of ordinary and not very common.

> It's possible that I'm more limited in my understanding of the cpp subsystem on Zephyr, but I always find it odd that I need to enable `CONFIG_CPLUSPLUS=y` for the projects, I always expected the build system to just know it's there similar to how we use `#ifdef __cplusplus`.

Zephyr is written in C and it is a C-first operating system.

C++ support is an optional feature in Zephyr that exists mainly for compatibility reasons (e.g. if you have a library written in C++ that you want to use in a Zephyr application), similar to POSIX and CMSIS RTOS API support.

Writing a 100% "native" C++ application is not one of the use cases that the Zephyr OS (or Zephyr C++ subsystem for that matter) targets. None of the Zephyr API is "natively" C++, and will likely never be.

> The short of it is I would really like that Kconfig to be defaulted to `y`

If you feel very strongly about this, feel free to open an issue for this and take it to the Architecture WG.

For now, I will close this issue since you **can** build apps with main in a .cpp file.

**Comment by yperess** [comment]
@stephanosio just for future consideration, I'm not sold on C++ being an exception. From all the teams at Google that I've talked to, chromium is the only one that is using C as a primary language (and that's likely to change soon). So I would like to see C++ be a strong consideration in Zephyr.
