### ISSUE TITLE
Empty "west build --test-item" doesn't report warnings/errors

### ISSUE THREAD

**Issue by PerMac** [zephyrproject-rtos/zephyr#52614]
Using --test-item tells west which entry from testcase/sample.yaml to use. However, this option returns no errors nor warnings when a given item cannot be selected. 

To reproduce:
- Modify testcase.yaml at zephyr/tests/kernel/common/testcase.yaml by adding some wrong option, e.g. `-CONFIG_PAKSGPGKAGSGPADKG_SANE=y`  into `extra_configs`  of kernel.common.misra

- run `west build zephyr/tests/kernel/common --pristine always --board native_posix --test-item kernel.common.misra`
This will work correctly. kernel.common.misra will fail the build

The following scenarios are IMO problematic:
- change name of testcase.yaml to eg. test.yaml and run the above command again.
- change "tests" to sth else, e.g "builds" in testcase.yaml and run the above command again.
- use an non-existing entry, e.g due to a typo `--test-item kernel.common.mirsa` and run the above command again.

West won't report any issue, most likely building the default one.
I believe an error has to be returned if an item cannot be found.

**Comment by marc-hb** [comment]
Thanks for the report. I transferred this to the `zephyr` repo because the `west build` command is not part of `west`. If you run `git grep test.item` in both repos you will find nothing in the `west` repo and the (relatively simple) implementation of `--test-item` in `zephyr/scripts/west_commands/build.py`. If you look at the short `_parse_test_item()` there you will see that the general logic of that function is "look everywhere and grab every CMake argument we can find". So it's not a big surprise that it does not fail when nothing is found.

You could change the logic a bit to fail when either no file is found or when no CMake argument is found (which one??) but this would unfortunately break backwards-compatibility. It's not a stretch of the imagination to think some current `--test-item` users may have come to actually rely on `--test-item` doing nothing in come cases: for instance you could use that generated some `testcase.yml` at build time and conveniently test with versus without some CMake option. Could also be convenient to compare results of tests run by CI.

**Comment by mbolivar-nordic** [comment]
@carlocaione originally added support for this feature to `west build` -- can you take a look?

**Comment by carlocaione** [comment]
> @carlocaione originally added support for this feature to `west build` -- can you take a look?

nope, I suggested that but @nashif actually wrote the code.

**Comment by mbolivar-nordic** [comment]
> > @carlocaione originally added support for this feature to `west build` -- can you take a look?
> 
> nope, I suggested that but @nashif actually wrote the code.

Thanks for the correction; assignee applied
