### ISSUE TITLE
ESP32 Wifi driver returns EIO (-5) if connecting without a sleep sometime before calling

### ISSUE THREAD

**Issue by dean-at-evos** [zephyrproject-rtos/zephyr#52868]
Using ESP32-C3, although I suspect this could occur with any ESP32 as they all appear to use the same driver, zephyrproject/zephyr/drivers/wifi/esp32/src/esp_wifi_drv.c.

Calling this function from main at start up fails the connect, unless you have slept (or yielded) to allow the driver's handler thread to run;
```c
#define WIFI DT_NODELABEL(wifi)
const struct device *const wifi_dev = DEVICE_DT_GET(WIFI);

#define MY_SSID "your_ssid"
#define MY_PSK "your_psk"

int iStartWiFi() {
	int ret = 0;

	if(!device_is_ready(wifi_dev)) { 
		LOG_ERR("WiFI device not ready");
		return -ENODEV;
	}

	//Set up call backs for net events
	net_mgmt_init_event_callback(&con_discon, handler_cb, NET_EVENT_WIFI_CONNECT_RESULT | NET_EVENT_WIFI_DISCONNECT_RESULT);
	net_mgmt_init_event_callback(&ipV4_cb, handler_cb, NET_EVENT_IPV4_DHCP_START | NET_EVENT_IPV4_DHCP_BOUND);
	net_mgmt_add_event_callback(&con_discon);
	net_mgmt_add_event_callback(&ipV4_cb);

	//Fill out the wifi config struct
	struct wifi_connect_req_params wifi_config;
	//Esp driver only seems to use these params...
	wifi_config.security = WIFI_SECURITY_TYPE_PSK;
	wifi_config.ssid = MY_SSID;
	wifi_config.ssid_length = MIN(MY_SSID, WIFI_SSID_MAX_LEN);
	wifi_config.psk = MY_PSK;
	wifi_config.psk_length = MIN(MY_PSK, WIFI_PSK_MAX_LEN);
	
	//Get the api for the wifi dev
	const struct net_wifi_mgmt_offload *wifi_api = wifi_dev->api;

	LOG_DBG("Trying to connect to %s:%s", wifi_config.ssid, wifi_config.psk);

	//Try and connect....
        k_msleep(1) //Will possibly fail with EIO if no sleep here
	ret = wifi_api->connect(wifi_dev, &wifi_config);
	
	if (ret)
	{
		event_cb = NULL;
		LOG_ERR("WiFi Connect failed %d", ret);
	}

	return (ret);
}
```
It seems to fail as when the call to connect reaches here;
```c
static int esp32_wifi_connect(const struct device *dev,
			    struct wifi_connect_req_params *params)
////////////////////->
	if (data->state != ESP32_STA_STARTED) {
		LOG_ERR("Wi-Fi not in station mode");
		wifi_mgmt_raise_connect_result_event(esp32_wifi_iface, -1);
		return -EIO;
	}
```
Unless the main thread has slept or yielded, this section hasn't run;
```c
static void esp_wifi_event_task(void)
////////////////////->
		case ESP32_WIFI_EVENT_STA_START:
			esp32_data.state = ESP32_STA_STARTED;
			net_eth_carrier_on(esp32_wifi_iface);
			break;
```
Hope this makes sense to you gurus out there.

**Comment by sylvioalves** [comment]
@dean-at-evos, would you try using proper `net_mgmt` API for this? `net_mgmt(NET_REQUEST_WIFI_CONNECT..`?

**Comment by dean-at-evos** [comment]
I will come back to that code and try that. I couldn't find a good example of the 'right' way to setup the connection, so I just hacked away :) I'll update this issue when I get back to it. Thanks for your time @sylvioalves

**Comment by dean-at-evos** [comment]
@sylvioalves Have got back to this project now and tried the ```net_mgmt``` api. Still shows the same behaviour when trying to connect from within the main loop if the system workqueue hasn't had a chance to run.
The work around for me in the end was to add something like...
```c
int sleep_cnt = 0;
while (!net_if_is_up(iface) && (sleep_cnt < 10)) {
        k_sleep(K_MSEC(100));
	sleep_cnt++;
	LOG_DBG("Wait net iface %d", sleep_cnt);
}

if (!net_if_is_up(iface)) {
	LOG_ERR("WiFi iface not up");
	return -ENOTCONN;
}
```
before connecting. Not a big deal but I guess a time sucker trying to work out why I could connect using the sample code but not from my app.....
If you suggest a good place to document this, or an approach to fix it I'll submit a PR. Otherwise, I'll close the issue.

**Comment by nashif** [comment]
@sylvioalves  Can you please take another look at this?

**Comment by thc1006** [comment]
Reopening per the bot's "you can always re-open" notice with fresh evidence from 2026-06-02.

**Status on both branches today:**
- `v3.7-branch` HEAD: the pre-check `if (data->state != ESP32_STA_STARTED) return -EIO;` survives at `drivers/wifi/esp32/src/esp_wifi_drv.c:394`.
- `main` HEAD (`4036b7f`): same pre-check survives at `:541`.
- `esp_wifi_event_task` still sets `ESP32_STA_STARTED` only after the kernel yields to it.
- `git log drivers/wifi/esp32/src/esp_wifi_drv.c --since=2025-01-01`: zero PRs touch this block (24 commits cover PMF, SAE, APSTA, BSSID, MAC fixes only).

**Espressif's own contract**: the ESP-IDF Wi-Fi Driver guide [Station Scenarios s3.2-3.3](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/wifi.html) requires `WIFI_EVENT_STA_START` to fire before `esp_wifi_connect()`. The Zephyr wrapper exposes that contract without any synchronization primitive.

**Reproduced 2026-06-02** on ESP32-S3-DevKitC + Zephyr v3.7-LTS + hal_espressif. Application-side workaround: a 3-s-cooldown retry loop on `NET_REQUEST_WIFI_CONNECT` from the main 1 Hz tick. Repro firmware: https://github.com/thc1006/fieldguard-esp32s3 commit `8fa35c1` (function `oob_wifi_retry_connect_if_needed` in `firmware/fieldguard_watchdog/src/wifi_sense.c`). Smoke: cold-boot DUT now associates at t≈1.4 s vs. no-retry baseline = never associates.

**Related**: this is the CONNECT-path sibling of issue #110290 (SCAN-path `scan_cb` leakage, fixed on `main` by #106329, also un-backported to v3.7-LTS).

**Proposed fix**: convert `esp32_wifi_connect()` to block on a `k_sem` raised by `esp_wifi_event_task` on `ESP32_WIFI_EVENT_STA_START`, with a finite timeout (e.g. `K_MSEC(CONFIG_WIFI_ESP32_CONNECT_WAIT_MS)`, default 2000), returning `-ETIMEDOUT` only on timeout. Eliminates the documented `k_msleep(1)` / `net_if_is_up` poll workaround.

Happy to submit the PR if a maintainer (@sylvioalves) confirms direction.

**Comment by sylvioalves** [comment]
@thc1006 Hi, would you check the branch/url of the code you share as reference ( I can't open it)? I can't reproduce this in current main so I wanted to have the same test case.

**Comment by thc1006** [comment]
Sorry, that link was to a private repo of mine. Here's a standalone version you can drop into a fresh sample directory if you have a minute to try it:

`prj.conf`:
```
CONFIG_NETWORKING=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_LOG=y
```

`src/main.c`:
```c
#include <zephyr/kernel.h>
#include <zephyr/net/net_if.h>
#include <zephyr/net/net_mgmt.h>
#include <zephyr/net/wifi_mgmt.h>
#include <zephyr/sys/printk.h>

int main(void)
{
	struct net_if *iface = net_if_get_first_wifi();
	struct wifi_connect_req_params p = {
		.ssid = "DUMMY", .ssid_length = 5,
		.psk  = "12345678", .psk_length = 8,
		.security = WIFI_SECURITY_TYPE_PSK,
		.channel = WIFI_CHANNEL_ANY,
		.band = WIFI_FREQ_BAND_2_4_GHZ,
	};
	int ret = net_mgmt(NET_REQUEST_WIFI_CONNECT, iface, &p, sizeof(p));
	printk("connect ret=%d\n", ret);
	return 0;
}
```

Built against `main` at `4036b7f` for `esp32s3_devkitc/esp32s3/procpu`, flashed with `west flash --reset-type watchdog-reset`, then power-cycled. I get `ret=-5` (-EIO) on 3 of 3 cold boots. Adding `k_sleep(K_MSEC(50))` at the top of `main()` closes the window and it succeeds, which lines up with what Espressif documents for `esp_wifi_connect()` in their [station example](https://github.com/espressif/esp-idf/blob/master/examples/wifi/getting_started/station/main/station_example_main.c) (call it from a `WIFI_EVENT_STA_START` handler).

The race only fires if connect is issued before `esp_wifi_event_task` has had a chance to set `data->state = ESP32_STA_STARTED`. Most samples have enough init work that the event task gets to run first, so the window stays closed. That might be why it didn't reproduce for you.

If you're open to it, a small change in the pre-check would let apps just retry instead of bailing out hard:

```diff
-	if (data->state != ESP32_STA_STARTED) {
-		return -EIO;
+	if (data->state != ESP32_STA_STARTED) {
+		return -EAGAIN;
 	}
```

`-EAGAIN` is the usual signal for "not ready yet, try again", and anything currently checking `ret < 0` would behave the same. I can open a PR with that plus a short note in the WiFi mgmt API docs that mirrors the ESP-IDF precondition, if you'd like.

Thanks again for the time on this.
