### ISSUE TITLE
`net_tcp: context->tcp == NULL` error messages during TCP connection

### ISSUE THREAD

**Issue by tatuylonen** [zephyrproject-rtos/zephyr#53500]
I'm frequently getting "net_tcp: context->tcp == NULL" log messages when trying to connect to a TCP port on the local network from an STM32F407 board running Zephyr.  Everything seems to work, but I suspect the error message (perhaps from net_tcp_update_recv_wnd()?) might indicate a race condition in initializing the socket context during successful TCP connection establishment.  So far I've not detected actual adverse effects other than the error message in the logs.  My application basically does a DNS lookup, creates an AF_INET TCP socket, calls connect(), and makes a small HTTP POST request using http_client_req() (there is a simple web server on my workstation that it connects to).  The error message is printed on most connections, but not always.  It looks like it gets printed after connect() returns, during http_client_req processing.  My http post data is under 200 bytes, response from server under 50 bytes (excluding headers).  Send and receive buffers are 1024 bytes.

I've not noticed any adverse effects despite the error message so far, but if it is a race condition as I suspect, it might also cause other difficult-to-diagnose problems later.

This is with Zephyr 3.2.0, custom board based on STM32F407ZG, development platform Ubuntu 22.04.  CONFIG_ETH_STM32_HAL=y, CONFIG_ETH_STM32_HAL_API_V2=y.

**Comment by rlubos** [comment]
Indeed, I confirm this can take place if the TCP connection is closed **before** all of the data is read from the socket. There seems to be a problem with the underlying TCP connection referencing, the application layer (socket) should ref the connection so that it's not released too early (i. e. before the socket is closed) which is not the case right now. I'm looking into this.
