### ISSUE TITLE
k_busy_wait function hangs on when CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE is set with CONFIG_PM.

### ISSUE THREAD

**Issue by fomst** [zephyrproject-rtos/zephyr#53522]
**Describe the bug**
k_busy_wait() function doesn't return when  CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE and CONFIG_PM are enabled.

For blinky example when above configuration options are enabled the LED is turned on once and doesn't change it's state.
Adding of few logs revealed that program hangs on the k_busy_wait() function and no code is executed after call to this function.

Hardware is: STM32WB55 NUCLEO board.

**To Reproduce**
1. Open samples/basic/blinky example main.cpp and use k_busy_wait() instead of k_sleep().
2. Add CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE=y and CONFIG_PM=y to prj.conf.
3. Build and run application.

**Expected behavior**
When enabled CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE and CONFIG_PM  have no impact on k_busy_wait() functionality.

**Impact**
Unable to use k_busy_wait() when CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE  enabled.

**Logs and console output**

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain 0.15.0
 - [27ec69eca18]

**Additional context**
It may be that the problem is caused by that the timer which is used to count ticks is not re-enabled after application returns from idle. Then ticks are not incremented and k_busy_wait() never returns from this for loop:
```	
for (;;) {
		uint32_t current_cycles = k_cycle_get_32();

		/* this handles the rollover on an unsigned 32-bit value */
		if ((current_cycles - start_cycles) >= cycles_to_wait) {
			break;
		}
	}
```

**Comment by FRASTM** [comment]
In the stm32_lptim_timer.c, when setting a timeout of MAX_WAIT, the lptim is stopped, but depending on the CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE, it should either be stopped (true) or should count a very long period.

**Comment by r2r0** [comment]
@FRASTM IMO your solution will make no difference for `k_busy_wait` behavior because described case is for enabled `CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE`.
For me it looks that problem is more generic and it is not strictly related to STM32. This is because there is not defined any logical connection (in generic code) between code using `k_cycle_get_32` (like `k_busy_wait`) and the timer used in the implementation of `k_cycle_get_32`.
Either `k_busy_wait` should be not available when `CONFIG_SYSTEM_CLOCK_SLOPPY_IDLE` is enabled or there should be added some code to automatically start timer used in `k_cycle_get_32`.

**Comment by fomst** [comment]
Hi,
sorry for late answer.
@FRASTM i've tried your proposal but this doesn't help.

**Comment by r2r0** [comment]
Would it be Ok to just add small disclaimer for `k_busy_wait` documentation?

**Comment by r2r0** [comment]
Tiny PR with documentation fix added.
