### ISSUE TITLE
add_compile_definitions does not "propagate upwards" as supposed to when using west

### ISSUE THREAD

**Issue by erlingrj** [zephyrproject-rtos/zephyr#53579]
**Describe the bug**
I have this simple project

CMakeLists.txt
```
add_subdirectory(foo)
target_sources(app PRIVATE main.c)
```

foo/CMakeLists.txt
```
add_compile_definitions(FOO=42)
```

The expected behavior is that main.c is compiled with -DFOO=42. However, this is not the case. For some reason the compile definitions does not propagate "upwards" as they are supposed to do. If I instead do

CMakeLists.txt
```
add_compile_definitions(FOO=42)
target_sources(app PRIVATE main.c)
```

Then everything works as expected. Any suggestions here?

**Comment by thedjnK** [comment]
Invalid issue caused by using the wrong cmake command. `include()` should be used here which will share the same scope as the parent, `add_subdirectory()` will create a child scope inheriting the parent's variables as duplicates, but they are separate. Updating them from the child will not propagate them back to the parent.

**Comment by erlingrj** [comment]
Thank you, you are right. Sorry for confusion
