### ISSUE TITLE
net: socket: tls: cannot send when using blocking socket

### ISSUE THREAD

**Issue by vaussard** [zephyrproject-rtos/zephyr#54275]
**Describe the bug**
We are updating our codebase to Zephyr 2.7. I hit an issue when reaching Zephyr 2.6. Looking at the latest commits in `subsys/net/lib/sockets/`, I believe that this issue still exists in the latest version (but cannot test).

#27054 added locking to the socket layer. There is a mechanism to release the lock using a condition variable when calling `zsock_recv_stream()` but this is not enough when using a TLS socket:
- Calling `recv()` on a TLS socket calls `z_impl_zsock_recvfrom()`, which locks the mutex of the TLS socket FD before calling `ztls_recvfrom_ctx()`
- `tls_rx()` will call `zsock_recvfrom()` on the underlying socket FD, which locks the mutex of the "regular" socket FD
- `zsock_recv_stream()` calls `k_condvar_wait()`, but this releases only the mutex of the "regular" socket FD. This leaves the mutex of the TLS socket FD locked as long as no data is received (for a blocking socket)
- Now if another thread in the application calls `send()` on this TLS socket, it will block forever while trying to lock the mutex of the TLS socket FD

If the server sends some data, this will release the mutex, which will allow to send some data until `recv()` is called again. But this is not acceptable in our case.

I understand that the expected usage would be to use non-blocking sockets. We will probably migrate to this paradigm in the future, but this will require some significant effort on our side. Also most users would probably expect blocking sockets to work.

I did a not-very-pretty workaround to release the mutex from `ztls_recvfrom_ctx()`, by looking up the FD based on the context pointer, then getting the lock using `z_get_fd_obj_and_vtable()` and unlocking it before calling `recv_tls()`. But I feel like I am fighting against the layering of the TLS sockets.

Would you see a better option ?

Worth noting that sockets_can had a similar looking issue, but #39187 does not look easily applicable in my case. The root cause in my case is due to the TLS socket using 2 different FD and locking both of them, but unlocking only 1 when waiting for data.

**Expected behavior**
It should be possible to use `recv()` and `send()` on blocking TLS sockets.

**Impact**
The application cannot send data, which is not very useful :-)

**Comment by rlubos** [comment]
It seems to me that in order to achieve the behavior you expect, we might need to redesign how TLS layer interacts with the underlying socket.

I don't think we should consider releasing mutex for the entire `recvfrom()` call, as this may lead to some potentially dangerous scenarios. For example, if the TLS socket is closed, while still inside `mbedtls_ssl_read()`, the `close()` call will release the mbed TLS context that's currently in use, most likely leading to some nasty outcome. 

To me it seems the mutex should only be released when the underlying socket could potentially block. This shouldn't be done however inside the functions registered with `mbedtls_ssl_set_bio()` as those are called from within mbed TLS, leading to potential issues described above. Hence, I think we should redesign the interaction with the underlying socket. A rough idea on what could be done:
* Make all `zsock_recvfrom()` with the underlying socket non-blocking (for example by providing `ZSOCK_MSG_DONTWAIT` to the call. This should make all `mbedtls_ssl_read()` calls non-blocking as well.
* For non-blocking sockets this change doesn't really make a difference. But for blocking ones, we need to implement the "blocking" part outside of `mbedtls_ssl_read()`. This should be done inside `recv_tls()`/`recvfrom_dtls_common()`, and could be implmented for example with `poll()`. The `poll()` shall block until new data arrives, and only for this call the mutex should be released.
* Now, as `mbedtls_ssl_read()` could now return `-EAGAIN` for blocking sockets as well, this would also need extra handling. I. e. instead of returning from the function, for blocking socket the `poll()`/`mbedtls_ssl_read()`  should be repeated.
* Finally, TLS sockets should then need to handle `NET_OPT_RCVTIMEO` option on its own, as the underlying socket is no longer in a blocking manner.

@vaussard Any thoughts?

**Comment by vaussard** [comment]
Thank you for your insights @rlubos.

> I don't think we should consider releasing mutex for the entire recvfrom() call

I fully agree. I just did a quick around in order to avoid being blocked during testing but I am looking for a better solution.

> I think we should redesign the interaction with the underlying socket.

I think that this can work. I can give it a try if we have no better idea.

I am slightly afraid that we are workarounding the design limitations of the TLS layer due to the current locking scheme, and that it could break in other ways in the future. IMHO the core issue seems to be due to the double locking (TLS socket + regular socket) for each and every socket call, which is also not ideal from a performance point of view. 

Maybe a dumb idea, but what about making the locking in the socket layer optional? When creating a new TLS socket, the underlying socket would be created with the locking disabled. In that case:

- Locking would be disabled in sockets.c when called from the TLS layer
- The locking in the TLS layer would be enough to guarantee the mutual exclusion
- We would have to rework `tls_rx()` and `dtls_rx()` in order to release the mutex using a condition variable, as done in sockets.c and sockets_can.c
  - If we want to reuse `zsock_wait_data()` like in sockets_can.c, we would have to override `cond.lock` with the mutex from the upper (TLS) layer. Not sure how clean that would be ?

What do you think ?

**Comment by rlubos** [comment]
> We would have to rework tls_rx() and dtls_rx() in order to release the mutex using a condition variable, as done in sockets.c and sockets_can.c

This raises my concern, as it's exactly the behavior I've wanted to avoid. We'd release the mutex protecting TLS context while inside `mbedtls_ssl_read()`, which I'm not convinced would be safe for the reason described above. 

> If we want to reuse zsock_wait_data() like in sockets_can.c, we would have to override cond.lock with the mutex from the upper (TLS) layer. Not sure how clean that would be ?

The problem is that this would introduce a dependency on the TCP/UDP socket implementation details. 

Please note that with the current TLS socket design, based on standard socket calls only, it's possible replace the underlying socket  implementation with for example offloaded implementation. Providing any cross dependency between TCP and TLS sockets would break this nice feature.

**Comment by carlescufi** [comment]
> I think that this can work. I can give it a try if we have no better idea.

@vaussard do you still plan to give this a go? Thanks!

**Comment by rlubos** [comment]
@vaussard I've prepared https://github.com/zephyrproject-rtos/zephyr/pull/56324, please give it a try.

**Comment by vaussard** [comment]
Sorry I missed the notification. Yes it was on my list of things to do. I was about to resume now when I noticed the PR.

Thank you @rlubos, I will test.
