### ISSUE TITLE
DHCPv4 starts even when interface is not operationally up

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#54457]
With recent introduction of network interface states like administration and operation, DHCPv4 client should wait for the interface to be operationally up (net_mgmt event) and only then should start, else we the L2 driver just drops the packets.

This is evident by configuring `CONFIG_NET_CONFIG_INIT_TIMEOUT=0` i.e., the L2 interface by default is operationally down (e.g., Wi-Fi), so, we disable network timeout, so, `setup_dhcvpv4` is called and we can see `net_if: iface xxx is down` prints. But if we leave the timeout by default, the DHCPv4 is not started by default as the network interface is timed out, so, not setup takes place and then DHCPv4 waits till `NET_EVENT_IF_UP` from the driver and it works.

**Comment by rlubos** [comment]
> This is evident by configuring CONFIG_NET_CONFIG_INIT_TIMEOUT=0 i.e., the L2 interface by default is operationally down (e.g., Wi-Fi), so, we disable network timeout, so, setup_dhcvpv4 is called and we can see net_if: iface xxx is down prints. But if we leave the timeout by default, the DHCPv4 is not started by default as the network interface is timed out, so, not setup takes place and then DHCPv4 waits till NET_EVENT_IF_UP from the driver and it works.

Generally, I find it a bit odd that the interface configuration behaves differently, depending on the timeout setting. In both cases the interface may be down, but if the timeout is not set (i. e. equal to 0), the network interface IPv4/IPv6/DHCPv4 startup code will be executed, otherwise not. The latter is a problem, as DHCPv4 has built-in logic to detect when the interface was brought up, but if the DHCP was not started on the interface on the first hand, it will not work, as the state machine will remain in the disabled state.

Therefore, I suggest to unify the behaviour with interface configuration in both cases, and update DHCP/MLD not to take attempts to send any data if the interface is down. See https://github.com/zephyrproject-rtos/zephyr/pull/54490.
