### ISSUE TITLE
flash_flexspi_nor_init return -ENODEV in flash_mcux_flexspi_nor.c for NXP mimxrt1060_evk board

### ISSUE THREAD

**Issue by ofirshe** [zephyrproject-rtos/zephyr#55258]
I'm currently working on the NXP mimxrt1060_evk board and facing some issues while attempting to read and write from the flash memory on board. Specifically, I am having trouble with the device_is_ready() function, which is returning -ENODEV when I enter with the debugger into flash_flexspi_nor_init().

Here's the section of the code in flash_mcux_flexspi_nor.c driver that's causing the issue:
```
struct flash_flexspi_nor_data *data = dev->data;
	uint8_t vendor_id;

	if (!device_is_ready(data->controller)) {
		LOG_ERR("Controller device is not ready");
		return -ENODEV;
	}
```

my code to reproduce the error:
```
const struct device *flash_dev = DEVICE_DT_GET(DT_NODELABEL(is25wp064));
if (!device_is_ready(flash_dev)) 
{
  return -1;
}
```

I have observed an additional issue where the flash_write() function appears to be stuck in the FLEXSPI_WriteBlocking() function within the while block shown below:
```
while (0U == ((status = base->INTR) & (uint32_t)kFLEXSPI_IpTxFifoWatermarkEmptyFlag))
{
}
```
I believe that the issues are interrelated.

Zephyr version: 3.3.99
build: zephyr-v3.3.0-596-g1d672aedb9d2
zephyr commit hash is 8b4407ab7cfb8319c3bf57cb01cbcb8cf9b7eb46.

An important point to mention is that evkbmimxrt1060_flash_component_nor test which is available in MCUexpresso SDK was successfully passed when I executed it on the same board.

Best regards,
Ofir.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the needed information from https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by decsny** [comment]
I have confirmed that the `tests/drivers/flash` test is failing on the RT1050 on the latest main, but passes on version 3.3.0, which uses this flexspi nor flash driver. I bisected and found that it was broken by commit 8c6137d7a794f84ca963d79ed9529f43ff61eee5 (author @fabiobaltieri).

**Comment by decsny** [comment]
I have increased the priority to medium for this bug because the flexspi nor flash driver seems to be broken for all of the i.MX RT devices, including RT10XX, RT11XX, and RTXXX, and they all break on this commit I mentioned above.

**Comment by decsny** [comment]
So far I have not found any difference in the Kconfig symbol outputs other than re-ordering

**Comment by decsny** [comment]
I believe that what happened is that the device ordinal numbers changed and that affected the order that the driver initializations happen, and since the flexspi flash driver depends on the flexspi device being initialized, the flexspi flash driver initialization will fail if it happens first, but currently I do not have a board with me to test this theory

**Comment by fabiobaltieri** [comment]
Hey thanks for bisecting the problem, yes unfortunately that patch potentially changed the initialization order of some peripherals that have the same level and priority. Here's what happened:

`nxp,imx-flexspi-nor` is initialized as

https://github.com/zephyrproject-rtos/zephyr/blob/43d19c0b5f06a1c51c580d13845eee2bddbe15f6/drivers/flash/flash_mcux_flexspi_nor.c#L609-L610

`nxp-imx,flexspi` is initialized as

https://github.com/zephyrproject-rtos/zephyr/blob/43d19c0b5f06a1c51c580d13845eee2bddbe15f6/drivers/memc/memc_mcux_flexspi.c#L280-L281

As it happens both `CONFIG_FLASH_INIT_PRIORITY` and `CONFIG_KERNEL_INIT_PRIORITY_DEVICE` are set to 50, so the corresponding init section in the build ends up being `.z_device_POST_KERNEL50_` for both. The sections are sorted alphabetically by the linker but since they have the same name it means that the relative init order was the linking one, which changed after my patch sorting the list. I thought that those section had the initialization function name in it for some reason, which would have made the order stable regardless of the linking order at some extent, but that turned out to not be the case, sorry about it.

So that changed exposed the fact that the two devices depended on each other but were being initialized with the same priority, it's a good idea to adjust the priority of one of the two to make sure that that is stable and independent on the linking order.

As for that change, I can add a line in the release notes for 3.4 indicating that the change may potentially expose some initialization "race condition", or we may revert it altogether. I'll bring this up at the next release meeting.

**Comment by decsny** [comment]
Hi @fabiobaltieri, thank you for helping to clear this up. I definitely agree that these flexspi driver initializations should have their priorities adjusted since one depends on the other. I personally do not think that your commit should be reverted. It has shown that some of our driver priorities are dangerously set. I have been looking around at the tree and it seems this is not the only case of an NXP device driver relying on another NXP device driver being initialized despite having the same priority as each other. I will work on a PR to fix these issues for NXP devices next week. Again, thanks for the response.

**Comment by hakehuang** [comment]
@fabiobaltieri , I find this dependency can be exposed by device tree see below:

```
            flexspi: spi@402a8000 {
                        compatible = "nxp,imx-flexspi";
                        reg = < 0x402a8000 0x4000 >, < 0x60000000 0x800000 >;
                        interrupts = < 0x6c 0x0 >;
                        #address-cells = < 0x1 >;
                        #size-cells = < 0x0 >;
                        ahb-bufferable;
                        ahb-cacheable;
                        status = "okay";
                        pinctrl-0 = < &pinmux_flexspi1 >;
                        pinctrl-names = "default";
                        ahb-prefetch;
                        ahb-read-addr-opt;
                        rx-clock-source = < 0x1 >;
                        is25wp064: is25wp064@0 {
                                compatible = "nxp,imx-flexspi-nor";
```

would that possible that we process the init sequence marco derive from the device tree level?

**Comment by fabiobaltieri** [comment]
> would that possible that we process the init sequence marco derive from the device tree level?

It's a long standing issue, don't think anyone managed to find a clean way of doing it yet unfortunately. It may be possible to validate that at build time though, trying to cobble together something.
