### ISSUE TITLE
Documentation dark mode renders difficult to read images with transparent backgrounds

### ISSUE THREAD

**Issue by pdgendt** [zephyrproject-rtos/zephyr#57069]
**Describe the bug**
The documentation contains images with transparent backgrounds, which can contain (black) text. Using dark mode can make it difficult to read these.
See for example: https://docs.zephyrproject.org/3.3.0/connectivity/networking/net-stack-architecture.html#network-data-flow

**Expected behavior**
Text embedded in images should always be readable.

**Impact**
Annoyance

**Comment by kartben** [comment]
Thanks for reporting this. I'll work on a fix.
FWIW the images on this particular page probably need to be reworked independently of the current fix. The issue is not that they have a transparent background per se, but rather that some of the main elements on them have some level of transparency when they shouldn't. See e.g. 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/128251/233329278-ff5b6ece-814e-4e08-8e76-eb74b867ca53.png">
