### ISSUE TITLE
lwm2m: block-wise context retrieval method

### ISSUE THREAD

**Issue by RomainPelletant** [zephyrproject-rtos/zephyr#57165]
**Describe the bug**
Based on Zephyr LwM2M client and Leshan software, OTA feature in push mode in not able to success due to token update between each block-wise packet from Leshan (Californium precisely).
It seems that token changes during block-wise transfer is a valid behavior : [here](https://github.com/eclipse/leshan/issues/1422)

**To Reproduce**
1. LwM2M client sample with OTA object implemented in push mode
2. Write binary from Leshan on 5/0/0 object
3. LwM2M client creates the block-wise context successfully 
4. The second block-wise transferred cannot be associated to a block context cause the token has changed (and block-wise context retrieval is based on token)

**Expected behavior**
Complete an entire block-wise transfer

**Additional context**
It is possible to disable that feature from Californium side (as noticed in Leshan/Californium issue) in setting this line in Californium config : COAP.BLOCKWISE_REUSE_TOKEN=true

Do you see a method to update block-wise context retrieval?

**Comment by rlubos** [comment]
Perhaps instead of identifying the block transfer with a token, we could identify one with the LwM2M resource path? I don't really see another option, given that we can no longer rely on a token, there's nothing else constant at the CoAP level other than URI. 

`token`/`tkl` fields of `struct lwm2m_block_context` in such case no longer seem to be needed, and we could replace `level`/`res_id`/`res_inst_id` with a proper `struct lwm2m_obj_path` entry, to identify the block context.

Any thoughts? CC @SeppoTakalo
