### ISSUE TITLE
cmake: Accept CONFIG_XX overrides from command line

### ISSUE THREAD

**Issue by aescolar** [zephyrproject-rtos/zephyr#5723]
It would be very nice to have the option to override configuration of a project from the command line when calling cmake.
Something like:
```cmake .. -DBOARD=native_posix -DCONFIG_COVERAGE=y -DCONFIG_BT=n```

The idea is that this configuration overrides would have priority over project and arch/board/driver.. options.
They would be fully ephemeral == lost as soon as a new reconfiguration is run.
(If the user wants persistent changes to the configuration he should change the project file)

The 2 uses I see right now:
* Automation: A script like sanitycheck could set CONFIG_COVERAGE from the command line, instead of setting it in the prj files.
* Quick overrides for manual tests to enable/disable features.

**Comment by pfalcon** [comment]
I'd find this useful. More specifically, I'd suggest to establish a suitable CFLAGS-like option, e.g. CFLAGS_EXTRA, using which you can pass any $(CC) flags, being them -D or any other.

No idea how this would work with Cmake though.

**Comment by aescolar-ot** [comment]
@pfalcon : Note that I meant configuration options. Not just the C pre-processor flags in which they end.

**Comment by SebastianBoe** [comment]
> I'd find this useful. More specifically, I'd suggest to establish a suitable CFLAGS-like option, e.g. CFLAGS_EXTRA, using which you can pass any $(CC) flags, being them -D or any other.

cmake -DEXTRA_CFLAGS="-DFOO=3 -fpermissive"

is supported.

**Comment by pfalcon** [comment]
@SebastianBoe : any way to pass that into Makefile generated by CMake?

**Comment by SebastianBoe** [comment]
> @SebastianBoe : any way to pass that into Makefile generated by CMake?
Assuming you mean passing it when Make is invoked then no.
The closest thing would be

cmake .. -DEXTRA_FLAGS="-DFOO=3" && make

**Comment by nashif** [comment]
> @SebastianBoe : any way to pass that into Makefile generated by CMake?

how is this related to this issue? 

I think this is about overriding Kconfig variables on the command line and also resolve dependencies, not just define them.

**Comment by ulfalizer** [comment]
If you can get the overrides into `kconfig.py`, then it should be as simple as calling `kconf.syms[sym_name].set_value(value)` after loading the fragments. `set_value()` is what `load_config()` uses internally as well.

That will also generate the `warning: BLAH was assigned the value ... but got the value ...` warning if the symbol gets a different value due to dependencies, and will also warn if the value is invalid for the type or if the symbol has no prompt (user values never have an affect on promptless symbols).

Automatically enabling dependencies is a pretty common request, but unfortunately it's trickier than it might seem at first. Consider a dependency like `depends on (FOO || !BAR) && BAZ != "hmz"` for example. Probably best to require people to manually enable dependencies.

I added myself as a watcher. Might've noticed...

**Comment by SebastianBoe** [comment]
Re-assigning to me as this is a build-system feature request.

**Comment by aescolar** [comment]
@SebastianBoe : Does this one look to tricky to implement?
