### ISSUE TITLE
CI: test: mimxrt595_evk_cm33: 4b7f156403523360ba3d589fa65f677aed42e1df : expose mutex can't called right after init issue 

### ISSUE THREAD

**Issue by hakehuang** [zephyrproject-rtos/zephyr#57783]
**Describe the bug**
enable the CONFIG_NO_OPTIMIZATIONS=y in hello_world cause the zephyr hangs in fixregulator call

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using?
  mimxrt595_evk_cm33
 - What have you tried to diagnose or workaround this issue?
 below commit fixes this issue by remove the k_mutex_lock() call right after k_mutex_init()
 ```
commit 0a55ec8d52f781ccd50795feba7e9fb2ed03258e
ubuntu@ubuntu-OptiPlex-7050:/home/shared/disk/zephyr_project/zephyr_rt595/zephyr$ git show zephyr-v3.3.0-3302-g7fa4776948d5
commit 7fa4776948d5a31f8362223ecc2fbf622d1df4cb (HEAD, refs/bisect/bad)
Author: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
Date:   Thu Apr 27 09:24:26 2023 +0200

    drivers: regulator: fixed: refactor initialization code.

    In some cases, the enable pin may be already enabled by a previous
    stage, e.g. bootloader. Therefore, it is not desirable to disable
    the pin, as it could cause malfunctioning of the device. Refactor init
    procedure so that we pick the right GPIO flags during the first
    configuration stage.

    Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>



```

**To Reproduce**
1. cd hello_world
2. add CONFIG_NO_OPTIMIZATIONS=y to prj.conf
3. west build -b mimxrt595_evk_cm33
4. west flash
5. serial console has no output

**Expected behavior**
expect the hello world string

**Impact**
k_sem_init

**Environment (please complete the following information):**
 - OS: (e.g. Linux, )
 - Toolchain (e.g Zephyr SDK, ...)
 - Commit SHA or Version used: 4b7f156403523360ba3d589fa65f677aed42e1df

**Comment by hakehuang** [comment]
@dleach02 , @mmahadevan108

**Comment by dleach02** [comment]
@hakehuang this is actually a dual problem not related to our platform. The first is a stack size problem. When you turn off optimizations you need to greatly bump up your stack(s) because the system will consume much more stack space. As an experiment, I doubled the size of the main and privileged stacks and things start working again:

CONFIG_NO_OPTIMIZATIONS=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_PRIVILEGED_STACK_SIZE=2048

The second problem is something we have observed related to the logging subsystem and what the gcc compiler does when you have logging turned off when compiling with no optimizations. The generated code to functions with logging functions will have a huge adder to the SP for no real reason. In this particular case, the mutex you were concerned about was okay. When locking it would eventually go to z_impl_k_mutex_lock() where there are some LOG macros that are all compiled out. But if you expand the preamble on the problematic code you will see this large adjustment to the SP (0x400+) which will cause the system to blow the stack. 

Daniel first observed this a while ago but we don't quite know why the compiler does this.

**Comment by dleach02** [comment]
Entered #57970 to track this... closing this one
