### ISSUE TITLE
esp32c3_devkitm not working with mesh examples

### ISSUE THREAD

**Issue by ShahinHaque97-CT** [zephyrproject-rtos/zephyr#58185]
**Describe the bug**
esp32c3_devkitm not working with any BLE MESH example, Application halts after Bluetooth is initialized, before mesh is initialised.
This example has been tested on other boards such as nRF Series boards and is working. 

**Expected behavior**
Mesh to be initiated and visible on the provisioning application on the phone. 

**Impact**
Unable to continue until solved.

**Logs and console output**
Log:
```
I (49) boot: ESP-IDF 075894ed2 2nd stage bootloader
I (49) boot: compile time 12:30:08
I (49) boot: chip revision: 3
I (51) boot.esp32c3: SPI Speed      : 40MHz
I (56) boot.esp32c3: SPI Mode       : DIO
I (61) boot.esp32c3: SPI Flash Size : 4MB
I (65) boot: Enabling RNG early entropy source...
I (71) boot: Partition Table:
I (74) boot: ## Label            Usage          Type ST Offset   Length
I (82) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (89) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (96) boot:  2 factory          factory app      00 00 00010000 00100000
I (104) boot: End of partition table
I (108) esp_image: segment 0: paddr=00010020 vaddr=00000020 size=0001ch (    28)
I (116) esp_image: segment 1: paddr=00010044 vaddr=3fc9a730 size=00ca8h (  3240) load
I (126) esp_image: segment 2: paddr=00010cf4 vaddr=3fc9b3d8 size=006b0h (  1712) load
I (134) esp_image: segment 3: paddr=000113ac vaddr=40380000 size=08030h ( 32816) load
I (150) esp_image: segment 4: paddr=000193e4 vaddr=00000000 size=06c54h ( 27732)
I (156) esp_image: segment 5: paddr=00020040 vaddr=3c000040 size=04090h ( 16528) map
I (162) esp_image: segment 6: paddr=000240d8 vaddr=00000000 size=0bf40h ( 48960)
I (177) esp_image: segment 7: paddr=00030020 vaddr=42010020 size=32f7ch (208764) map
I (227) boot: Loaded app from partition at offset 0x10000
I (227) boot: Disabling RNG early entropy source...
*** Booting Zephyr OS build zephyr-v3.3.0-4220-gf5830f3c3fe2 ***
Initializing...
Bluetooth initialized
assert co_utils.c 728, param 000000ff 000000ff
```
**Environment (please complete the following information):**
Windows 10
Zephyr version: latest west init as of 23/05/23
Toolchain: From Espressif
Modifications: An overlay to add an LED for the ON/OFF MESH.
BOARD=esp32c3_devkitm

**Additional context**

The esp32c3_devkitm is working with BLE examples, just not BLE MESH examples

**Comment by ShahinHaque97-Corintech** [comment]
Update: 
I have found the Bluetooth Mesh Shell test, which has allowed me to run some commands:

Mesh init and other commands run fine, the issue is with provisioning

uart:~$ mesh prov pb-adv on
assert co_utils.c 728, param 000000ff 000000ff

Program Halted

uart:~$ mesh prov pb-gatt on
assert co_utils.c 728, param 000000ff 000000ff

Program Halted.

Same error as before.

**Comment by rftafas** [comment]
I would not say it is a bug, because we are currently not supporting BT Mesh. We actually have reports of some users that have successfully made it to work. Unfortunately, I haven't seen them contributing and they haven't shared with us their improvements. I can't say that NVS is the cause for now, so any testing and more info is very welcome.

BTW, BT Mesh falls short to other tasks we have in roadmap (Mainly S3 and better MCUboot support).

**Comment by ShahinHaque97-Corintech** [comment]
I'd have assumed it was supported as in the espressif docs it states:

"Bluetooth mesh is not a wireless communications technology, but a networking technology. This technology is dependent upon Bluetooth Low Energy (BLE) - a wireless communications protocol stack.

Built on top of Zephyr Bluetooth Mesh stack, the ESP-BLE-MESH implementation supports device provisioning and node control. It also supports such node features as Proxy, Relay, Low power and Friend." - https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/esp-ble-mesh/ble-mesh-index.html

**Comment by rftafas** [comment]
Well, I can't say it is a debased assumption, that's for sure. Besides, it is certainly feasible. Thus, if you decide to get hands on, let us know and help during roadblocks.

**Comment by matt-wood-ct** [comment]
Is there anyway we can progress on this, does anyone know who managed to get it working, could we get their username so we can get in contact.
We would really like to get mesh going on the C3 otherwise we will have to go back to ESP-IDF for out application which would be disapointing given all that Zephyr has to offer.

**Comment by rftafas** [comment]
I can't point the finger and I suppose these people are reading to this so, it is up to them and I'm sorry to be of little help. I would suggest old school debugging. We have been increasing the availability of tools. Core Dump and OpenOCD. C3 has the builtin USBSerial/JTAG so it comes handy. Again, put your findings here so we can help.

As for using ESP-IDF, first, it is the official tool so I see no problems doing it and, second, have in mind that moving to Zephyr from ESP-IDF is only possible through physical flashing of the device (anything other than that may be feasible, but it is not on roadmap yet - check MCUboot for ESP-IDF around the internet).

**Comment by jorcis** [comment]
Working with the latest Zephyr OS build zephyr-v3.4.0-1061-gabfd23406057, doesn't it ?

**Comment by jhedberg** [comment]
@ShahinHaque97-CT I'll close this since it seems this might already be fixed. Feel free to reopen if the issue still exists.
