### ISSUE TITLE
kernel: CONFIG_SYS_CLOCK_EXISTS can be enabled without system clock implementation

### ISSUE THREAD

**Issue by MarekPieta** [zephyrproject-rtos/zephyr#58269]
**Describe the bug**
We can enable the `CONFIG_SYS_CLOCK_EXISTS` Kconfig option without actually enabling the implementation of the system clock (e.g. with explicitly disabled `CONFIG_NRF_RTC_TIMER` on nRF SoC based boards). The build would succeed until the system clock API is used somewhere in the code (using the system clock API would trigger linker failures).

**To Reproduce**
1. Build `hello_world` sample on `nrf52840dk_nrf52840` with `CONFIG_NRF_RTC_TIMER=n`
2. See the linker error (zephyr/kernel/timeout.c:64: undefined reference to `sys_clock_elapsed').
3. Disable also the `CONFIG_SYS_CLOCK_EXISTS`.
4. See that build is now successful.

**Expected behavior**
The `CONFIG_SYS_CLOCK_EXISTS` should depend on the fact that a driver implementation is available to avoid making impression that feature is available when it actually is not. I think we may also need to ensure that only one system clock driver implementation is enabled at a time.

**Impact**
It is quite easy to make improper application configuration and the related linker failures may remain hidden for a long time.

**Environment**
Zephyr version: `49c7aa56fa0c1e61de95577e5fdc1877872b549c` (current main). Can be also replicated with other versions.

**Comment by nordic-krch** [comment]
It looks like the logic in Kconfig is flipped so when `CONFIG_SYS_CLOCK_EXISTS` is set, only then section with timer driver is enabled: https://github.com/zephyrproject-rtos/zephyr/blob/fe10c0b423cabbee3f2780d1c0e7046e1d2b75f1/drivers/timer/Kconfig#L8

The fix would be to change it so that each system timer driver is selecting `CONFIG_SYS_CLOCK_EXISTS`. I am not sure if there are any blockers (out of tree drivers?) @teburd @andyross what are your thoughts?
