### ISSUE TITLE
LE Audio: controller: Failed to send to sink ASE

### ISSUE THREAD

**Issue by mkasenberg** [zephyrproject-rtos/zephyr#58325]
In some of BAP/UCL/STR PTS test cases the IUT has to configure 1 SINK ASE to streaming state and send packets with random data. While testing Zephyr Host + Zephyr Controller setup some issue appear and only a first packet is received by controller of the PTS dongle. More over the packet has a random sequence number. Bluetooth Protocol Viewer logs:
[zephyr_BAP_UCL_STR_BV_033_C.cfa.txt](https://github.com/zephyrproject-rtos/zephyr/files/11576281/zephyr_BAP_UCL_STR_BV_033_C.cfa.txt)

I repeated tests for Zephyr Host + Packetcraft Controller setup and this works fine:
[packetcraft_BAP_UCL_STR_BV_033_C.cfa.txt](https://github.com/zephyrproject-rtos/zephyr/files/11576271/packetcraft_BAP_UCL_STR_BV_033_C.cfa.txt)

### Zephyr Host + Zephyr Controller setup:

In samples/bluetooth/hci_rpmsg, create bttester_hci_rpmsg_overlay.conf file with:
`echo CONFIG_BT_CTLR_CONN_ISO_LOW_LATENCY_POLICY=y > bttester_hci_rpmsg_overlay.conf`
(related issue #57088)

Build the controller with:
`west build -b nrf5340dk_nrf5340_cpunet -- -DOVERLAY_CONFIG='nrf5340_cpunet_iso-bt_ll_sw_split.conf;bttester_hci_rpmsg_overlay.conf' `

Flash the controller with:
`west flash --recover`

In zephyr/test/bluetooth/tester build the tester app:
`west build -b nrf5340dk_nrf5340_cpuapp . -- -DOVERLAY_CONFIG='overlay-le-audio.conf`

Flash the app with:
`west flash`

### Zephyr Host + Packetcraft Controller setup:
Download the controller binary:
https://github.com/nrfconnect/sdk-nrf/blob/v2.3.0/applications/nrf5340_audio/bin/ble5-ctr-rpmsg_3330.hex

and flash with:
`nrfjprog --program *.hex --chiperase --coprocessor CP_NETWORK -r`

Download this overlay:
[packetcraft-overlay-le-audio.txt](https://github.com/zephyrproject-rtos/zephyr/files/11576221/packetcraft-overlay-le-audio.txt)

and in zephyr/test/bluetooth/tester build the tester app:
`west build -b nrf5340dk_nrf5340_cpuapp . -- -DOVERLAY_CONFIG='packetcraft-overlay-le-audio.txt`

Flash the app with:
`west flash`

**Comment by nashif** [comment]
@carlescufi can you assign please?

**Comment by mkasenberg** [comment]
Maybe this could help a little #58432

**Comment by cvinayak** [comment]
> Maybe this could help a little #58432

@mkasenberg Thank you debugging the issue using the samples.

I have added a new Kconfig to relax ISOAL in Zephyr Controller from being strict in dropping stale Tx ISO SDUs in this PR: https://github.com/zephyrproject-rtos/zephyr/pull/58717

Please add `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n`, i.e.
`echo CONFIG_BT_CTLR_ISOAL_SN_STRICT=n >> bttester_hci_rpmsg_overlay.conf`

Do let me know if mitigates dropped SDUs...

Thank you in advance for testing

**Comment by mkasenberg** [comment]
Works great! Thanks

**Comment by cvinayak** [comment]
Thank you.

> Works great! Thanks

means, as in #58717 and the Kconfig option set to false fixes this github issue, right?

**Comment by mkasenberg** [comment]
Yes, I just checkout to your PR #58717, have:
```
CONFIG_BT_CTLR_CONN_ISO_LOW_LATENCY_POLICY=y
CONFIG_BT_CTLR_ISOAL_SN_STRICT=n
```
in my bttester_hci_rpmsg_overlay.conf and the BAP/UCL/STR/BV-033-C test case passes without issues.

**Comment by cvinayak** [comment]
Reopening the issue, as using `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n` is just masking the fact that the `zephyr/test/bluetooth/tester` is providing stale Packet Sequence Number for the Tx ISO Data.

@mkasenberg Please see this change in the sample in https://github.com/zephyrproject-rtos/zephyr/pull/58717 for better understanding, hope you can correct the tester so that the Controller is not provided with stale Sequence Number?

**Comment by mkasenberg** [comment]
I see. In that case, it would be good to have in bap api a function that will return `struct bt_iso_tx_info *`, like this function (from iso.h) does:
```int bt_iso_chan_get_tx_sync(const struct bt_iso_chan *chan, struct bt_iso_tx_info *info);```
so you can be sure you have the correct sequence number in case the host clock gets out of sync with the controller clock.

**Comment by mkasenberg** [comment]
Oh, I found out that I can use `struct bt_iso_chan *bt_bap_stream_iso_chan_get(struct bt_bap_stream *stream)` to get the `bt_iso_chan*`, so will try with that.

**Comment by cvinayak** [comment]
Good.

But, from BT Spec. v5.4, Vol. 4, Part E, section 7.8.96 LE Read ISO TX Sync command

```
This command is used to read the TX_Time_Stamp and Time_Offset of a
transmitted SDU identified by the Packet_Sequence_Number on a CIS or BIS
identified by the Connection_Handle parameter on the Central or Peripheral.
```

You will only get seq_num used in the last call to `bt_bap_stream_send()`, you still need to keep time since `bt_bap_stream_send()` call to determined elapsed SDU_intervals until the next `bt_bap_stream_send()` call, and add that to the seq_num.

**Comment by cvinayak** [comment]
@Thalley and @niag-Oticon   I am confused by the below in Spec.

BT Spec. v5.4, Vol. 4, Part G, Section 3.3 TIME STAMP FOR SDU

```
When an HCI ISO Data packet sent by the Host does not contain a Time_-
Stamp or the Time_Stamp value is not based on the Controller's clock, the
Controller should determine the CIS or BIS event to be used to transmit the
SDU contained in that packet based on the time of arrival of that packet.
```

Does this mean, the controller should not drop the SDU or it should drop the SDU based on Packet_Sequence_Number? i.e. we today do not adjust the payload_number because  isoal_tx_unframed_get_next_payload_number()  does not check ts_flag  in the HCI ISO Data Packet.

**Comment by Thalley** [comment]
> @Thalley and @niag-Oticon I am confused by the below in Spec.
> 
> BT Spec. v5.4, Vol. 4, Part G, Section 3.3 TIME STAMP FOR SDU
> 
> ```
> When an HCI ISO Data packet sent by the Host does not contain a Time_-
> Stamp or the Time_Stamp value is not based on the Controller's clock, the
> Controller should determine the CIS or BIS event to be used to transmit the
> SDU contained in that packet based on the time of arrival of that packet.
> ```
> 
> Does this mean, the controller should not drop the SDU or it should drop the SDU based on Packet_Sequence_Number? i.e. we today do not adjust the payload_number because `isoal_tx_unframed_get_next_payload_number()` does not check `ts_flag` in the HCI ISO Data Packet.

I am not sure I follow: Why does the presence or absence of the timestamp affect how the packet sequence number is handled?

**Comment by niag-Oticon** [comment]
I would say that in implementing the ISO-AL I interpreted that as the controller has permission to decide which event to use to transmit the SDU based on the time of arrival, not that it must move the SDU to payloads that guarantees transmission.

But just so that we are clear, the ISO-AL does not drop anything. What it does is fragment an SDU into payload PDUs maintaining the stream alignment based on the PSN. If an SDU is delayed (especially with FT=1) then the payloads that the SDU is placed in might have expired or might be too close to expiry such that they are flushed. I would say that is the very nature of an ISO channel where if data is late beyond the configured leniency, it expires.

**Comment by cvinayak** [comment]
> > @Thalley and @niag-Oticon I am confused by the below in Spec.
> > BT Spec. v5.4, Vol. 4, Part G, Section 3.3 TIME STAMP FOR SDU
> > ```
> > When an HCI ISO Data packet sent by the Host does not contain a Time_-
> > Stamp or the Time_Stamp value is not based on the Controller's clock, the
> > Controller should determine the CIS or BIS event to be used to transmit the
> > SDU contained in that packet based on the time of arrival of that packet.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does this mean, the controller should not drop the SDU or it should drop the SDU based on Packet_Sequence_Number? i.e. we today do not adjust the payload_number because `isoal_tx_unframed_get_next_payload_number()` does not check `ts_flag` in the HCI ISO Data Packet.
> 
> I am not sure I follow: Why does the presence or absence of the timestamp affect how the packet sequence number is handled?

Because the spec tells "the Controller should determine the CIS or BIS event to be used to transmit the SDU contained in that packet based on the time of arrival of that packet".

Say, `the time of arrival of the packet`  to the Controller is **before** the BIG/CIG Event, then this packet is transmitted on-air. But a second packet to the Controller is just **after** the 2nd BIG/CIG event, and a third packet is just **before** the 3rd BIG event. The expected behavior on the receiving device would be to get the first packet, second is lost and third packet is received at their respective SDU intervals (and correct Packet_Sequence_Number s) .

If we were to have the second packet transmitted in the 3rd BIG/CIS event, then the receiving side will have audio playback skewed; imagine this is a phone call and we do not want delayed conversations (increasing latency due to skewing incrementally).

Another case, when using Packet_Sequence_Number, if the host is **drifting**, then the `payload_count` used to determine the PDU transmitted in the Controller would always be ahead of any received Packet_Sequence_Number; Controller will drop every ISO Data packet, considering it as stale. In such cases, it is responsibility of Host to use HCI_LE_Read_ISO_TX_Sync and synchronize the next Packet_Sequence_Number when sending new ISO Data packet.

> I would say that is the very nature of an ISO channel where if data is late beyond the configured leniency, it expires.

I agree with this, and the current upstream implementation matches this.

**Comment by mkasenberg** [comment]
I just observed that if the `bt_bap_stream_send` is called subsequently with sequence number equaled to 0, the controller will select the proper value of sequence number on its own. Hence sending works without `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n`. Would be ok to use it in the tester for PTS tests with streaming for now?

**Comment by Thalley** [comment]
> I just observed that if the `bt_bap_stream_send` is called subsequently with sequence number equaled to 0, the controller will select the proper value of sequence number on its own. Hence sending works without `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n` and additional timer for sequence number increasing, would be ok to use it like that in the tester for PTS tests with streaming for now?
> 
> If this is a valid behavior, maybe the description of seq_num parameter should be updated:
> 
> ```
>  * @param seq_num  Packet Sequence number. This value shall be incremented for each call to this
>  *                 function and at least once per SDU interval for a specific channel.
> ```

Yes, I think we need to update that documentation. The Core Spec mandates that the PSN shall be updated per SDU interval, but that's all it says. Anything outside of that requirement is as of BT 5.4 implementation specific

**Comment by niag-Oticon** [comment]
> I just observed that if the `bt_bap_stream_send` is called subsequently with sequence number equaled to 0, the controller will select the proper value of sequence number on its own. Hence sending works without `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n` and additional timer for sequence number increasing, would be ok to use it like that in the tester for PTS tests with streaming for now?
> 
> If this is a valid behavior, maybe the description of seq_num parameter should be updated:
> 
> ```
>  * @param seq_num  Packet Sequence number. This value shall be incremented for each call to this
>  *                 function and at least once per SDU interval for a specific channel.
> ```

That's an exploit that we left for Vendor Specific path where we didn't want to manage the sequence number according to the SDU interval and the hardware of the source generating the SDUs would guarantee SDUs being an interval apart and aligned to drifts in the transmission reference points.

If the packet sequence number does not change then the timestamps either provided by the source or included by the controller is used (based on the controller's clock) instead of the packet sequence number to decide the position of the SDU in the stream. It can certainly be used by an application, but it should not be considered specification compliant or used for qualification.

It is not exactly the equivalent of `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n` since it will choose the nearest SDU synchronisation reference based on time elapsed between SDUs received, where as `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n` is very likely to shift the SDU to payloads that will transmit. If the source generating the SDUs drifts, then there is still a possibility of fragmenting into payloads that are expired or close to expiry.

**Comment by cvinayak** [comment]
Lowering the priority of this gh issue, as there are multiple ways to unblock testing.
- Make tester have seq num incremented per each SDU interval
- Use `CONFIG_BT_CTLR_ISOAL_SN_STRICT=n` in the Zephyr Controller
- Or use sequence number equaled to 0 for each ISO Data

**Comment by mkasenberg** [comment]
Resolved by making the tester to increment the sequence number for each SDU interval as suggested.
