### ISSUE TITLE
TFM-M images ran without confirm it

### ISSUE THREAD

**Issue by nandojve** [zephyrproject-rtos/zephyr#58361]
**Describe the bug**
When build and flash a TFM image on hardware was noted that it is not possible to get version. This happens because images not execute the psa_fwu_accept(IMAGE_ID_FOO) at any moment. When image state is printed it is possible to see value 4 - PSA_IMAGE_PENDING_INSTALL. This was discovered when investigating #53537.

**To Reproduce**
Currently this is not possible to reproduce in hardware since example in v3.2 doesn't have a way to perform a fw_update and on mainline the example was temporary removed.

**Expected behavior**
The images that are generate on Zephyr and should be directly flashed on the hardware require a special parameter when signing the binaries to inform that image is committed. However, the images that are generated for FOTA MUST NOT set that bit.

As a suggestion, I think we could use same principle that is already used with MCUboot. The system builds the images and after that the user should execute the `west sign` passing the correct parameters including the private key. An additional step like `west merge` could  join S+NS image as a final step if necessary. This could be more familiar for users that already know how to use MCUboot and imgtools.

**Impact**
The wrong management of those option my compromise a application on field.

**Environment (please complete the following information):**
 - OS: Linux
 - Toolchain Zephyr 3.2
 
CC: @erwango

**Comment by microbuilder** [comment]
@nandojve Closing this as a bug since it feels like a feature request, rather than a bug. We don't currently have an integration sample in Zephyr for the firmware update service (FWU) in TF-M, since FWU got a new 1.0 API in TF-M 1.7.0, which was incompatible with the 0.7 release that we had a rudimentary sample for in earlier releases.

Expecting a call to `psa_fwu_accept(IMAGE_ID_FOO)` when FWU integration isn't currently supported in Zephyr with TF-M isn't a bug.

Can you instead raise a new feature request issue for a TF-M integration sample in Zephyr based on FWU 1.0 and TF-M >=1.7.0, which seems to be what is actually required? A sample contribution is welcome as well if you're actively working on FWU yourself!

Feel free to correct me if I'm misunderstanding the issue you've raise here, though, and we can reopen this as a bug.
