### ISSUE TITLE
OT: utilsFlashWrite does not take into account the write-block-size

### ISSUE THREAD

**Issue by jfischer-phytec-iot** [zephyrproject-rtos/zephyr#5943]
OpenThread utilsFlashWrite does not take into account the write-block-size. OT uses a multiple of 4 while writing to the flash. This leads to a bus fault on a platform like K64F where write-block-size is 8.

Is it possible to abstract utilsFlash* over a file system like nffs?

**Comment by KaSroka** [comment]
File abstraction can be used to emulate flash for OpenThread - as example you can see posix OpenThread platform: https://github.com/openthread/openthread/blob/master/examples/platforms/posix/flash.c 

We can also write our own settings modulethat uses file directly instead of flash: https://github.com/openthread/openthread/blob/master/examples/platforms/utils/settings.cpp

**Comment by carlescufi** [comment]
@jfischer-phytec-iot Sounds to me like we could write an abstraction over FCB or NFFS. Any takers to implement this in the 1.11 timeline?

**Comment by carlescufi** [comment]
@jfischer-phytec-iot are you going to give this a go?

**Comment by nashif** [comment]
any update on this?

**Comment by rlubos** [comment]
I'll look into this issue. We need a better way to store OpenThread settings - it became an recurring problem recently (#12944, #13687).

**Comment by rlubos** [comment]
No longer an issue with #21796.
