### ISSUE TITLE
Remove the dependency on USB_CDC_ACM from the USB_DEVICE_INITIALIZE_AT_BOOT Kconfig

### ISSUE THREAD

**Issue by robhelvestine** [zephyrproject-rtos/zephyr#61988]
## Introduction

There is a Kconfig option, USB_DEVICE_INITIALIZE_AT_BOOT, that is dependent on USB_CDC_ACM. However, I don't believe it should be. The USB subsystem should be able to be initialized at boot, even if USB_CDC_ACM is not used. I would like to remove this dependency from the Kconfig file. 

### Problem description

The USB device shall be able to be initialized at boot, even if USB_CDC_ACM is not used. This allows other USB Devices to use this Kconfig and get initialized at boot. There's no functional reason USB_CDC_ACM needs to be used to enable the usb subsystem on bootup. 

### Proposed change

A user will be able to initialize the usb subsystem at bootup if USB_CDC_ACM is used, or if not. 

## Detailed RFC

I would like to remove the `depends on USB_CDC_ACM` from the `config USB_DEVICE_INITIALIZE_AT_BOOT` located at subsys/usb/device/Kconfig. Furthermore the Help string will be altered so it is accurate. 

### Dependencies

This Kconfig is used in only one place, at the very bottom of usb_device.c, in the init function. Note that the Kconfig is only used here (the general USB device init), and not in cdc_acm.c, which you might expect if this was truly dependent on USB_CDC_ACM. 

### Concerns and Unresolved Questions

I do not have any and have tested this on my custom hardware. 

## Alternatives

The alternative from the user's perspective is to create an application level file that calls usb_enable(NULL). However, this is redundant and confusing and not entirely necessary.

**Comment by jfischer-no** [comment]
> There is a Kconfig option, USB_DEVICE_INITIALIZE_AT_BOOT, that is dependent on USB_CDC_ACM. However, I don't believe it should be. The USB subsystem should be able to be initialized at boot, even if USB_CDC_ACM is not used. I would like to remove this dependency from the Kconfig file.

There are many parts of USB device support that require initialization at the application level (usually done by the application). USB_DEVICE_INITIALIZE_AT_BOOT is only there because it was handled differently in the past, and unfortunately we failed to clean it up properly, and there are some boards that think it is good to initialize a subsystem at boot time, but it is not. There is some configuration overhead in the examples to disable the USB_DEVICE_INITIALIZE_AT_BOOT, option, as it would not work otherwise. There is more maintenance, documentation, and configuration overhead just because this option is there. Finally, this option goes away when we switch to the new stack. Sorry, but I am a little tired of explaining again why it is bad to have it in the Zephyr tree.

> The alternative from the user's perspective is to create an application level file that calls usb_enable(NULL). However, this is redundant and confusing and not entirely necessary.

Yes, please. Everyone is free to implement this option in their application/downstream repository and enable USB support at whatever level they want.

**Comment by jfischer-no** [comment]
> There is a Kconfig option, USB_DEVICE_INITIALIZE_AT_BOOT, that is dependent on USB_CDC_ACM. However, I don't believe it should be. The USB subsystem should be able to be initialized at boot, even if USB_CDC_ACM is not used. I would like to remove this dependency from the Kconfig file.

There are many parts of USB device support that require initialization at the application level (usually done by the application). USB_DEVICE_INITIALIZE_AT_BOOT is only there because it was handled differently in the past, and unfortunately we failed to clean it up properly, and there are some boards that think it is good to initialize a subsystem at boot time, but it is not. There is some configuration overhead in the examples to disable the USB_DEVICE_INITIALIZE_AT_BOOT, option, as it would not work otherwise. There is more maintenance, documentation, and configuration overhead just because this option is there. Finally, this option goes away when we switch to the new stack. Sorry, but I am a little tired of explaining again why it is bad to have it in the Zephyr tree.

> The alternative from the user's perspective is to create an application level file that calls usb_enable(NULL). However, this is redundant and confusing and not entirely necessary.

Yes, please. Everyone is free to implement this option in their application/downstream repository and enable USB support at whatever level they want.
