### ISSUE TITLE
net: lwm2m: send callback behavior on blockwise operation

### ISSUE THREAD

**Issue by RomainPelletant** [zephyrproject-rtos/zephyr#64290]
**Describe the bug**
Initiate blockwise operation on send method will never call send callback.

**To Reproduce**
1. Enable blockwise feature
2. send data greater than COAP BLOCK SIZE and register send callback

**Expected behavior**
The send callback shall be called to get send result

**Environment (please complete the following information):**
 - OS: MacOS
 - Toolchain 0.16.1
 - Zephyr 3.5

**Comment by henrikbrixandersen** [comment]
Please submit code change proposals as pull requests, not patches attached to issues.

**Comment by rlubos** [comment]
Isn't the `CONTINUE` code already handled at the CoAP library level, so that the reply callback is only called on the final block response? For reference: https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/coap/coap.c#L1744

Also I don't think I follow the user data change, isn't `struct lwm2m_message` preserved for the consecutive blocks? CC @SeppoTakalo

**Comment by SeppoTakalo** [comment]
I see.. 
`build_msg_block_for_send()` will reset the message structure, and get rid of CoAP reply structure that was having the `user_data` pointer.
