### ISSUE TITLE
net: Add IGMP shell to manage multicast groups

### ISSUE THREAD

**Issue by krish2718** [zephyrproject-rtos/zephyr#64389]
**Is your feature request related to a problem? Please describe.**
Test multicast groups, handy to have a shell command rather than writing applications for testing.

**Describe the solution you'd like**
It’s handy to have a IGMP shell as part of net to manage and test multicast groups, multicast is essential for Matter.

Below should suffice to start with:

`net igmp join <group address>`

`net igmp leave <group address`

**Comment by jukkar** [comment]
I am not sure we need separate shell commands for this. As the multicast networking does not really work without joining to IGMP (for IPv4) or MLD (for IPv6), we could modify the `net ipv4` and `net ipv6` shell commands so that when user adds a multicast address to the interface, the shell command will automatically join the multicast group.

**Comment by jukkar** [comment]
I can implement this, will send a PR shortly.

**Comment by krish2718** [comment]
> that when user adds a multicast address to the interface, the shell command will automatically join the multicast group.

Yes, this is how it works in Linux, adding a route will trigger IGMP join.
