### ISSUE TITLE
RFC: API Change: Make net_buf pool as rodata

### ISSUE THREAD

**Issue by LingaoM** [zephyrproject-rtos/zephyr#66265]
## Introduction

Since most of field in the pool should not change at runtime, and same part of field will change at runtime, so make this struct as rodata, and move some part of variables field to runtime structure, this change will more safely than put this to ram.

### Problem description

Many fields should not change at all at runtime.

### Proposed change

The field `lock`, `uninit_count ` and `avail_count` will move to new structure call `struct net_buf_pool_rt_ctx`.
And any access this fields from `pool->lock` change to `pool->rt->lock` etc...

## Detailed RFC

After this changed, as show in the bellow, the fields `free`, `lock`, `uninit_count` and `avail_count` will move to new structure call `struct net_buf_pool_rt_ctx`, those fields will keep variables, but other fields which not move to `struct net_buf_pool_rt_ctx` will change to const, not support change at runtime.

```C
struct net_buf_pool {
	/* Network buffer pool runtime ctx */
	struct net_buf_pool_rt_ctx {
		/** LIFO to place the buffer into when free */
		struct k_lifo free;

		/* to prevent concurrent access/modifications */
		struct k_spinlock lock;

		/** Number of uninitialized buffers */
		uint16_t uninit_count;

#if defined(CONFIG_NET_BUF_POOL_USAGE)
		/** Amount of available buffers in the pool. */
		atomic_t avail_count;
#endif /* CONFIG_NET_BUF_POOL_USAGE */
	} * const rt;
```

**What are the benefits of that?**

More safely and save some memory :).

**Comment by rodrigopex** [comment]
@LingaoM, thanks for your RFC.

Could you please elaborate a little more about the change? Please complete the [RFC template](https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/003_rfc-proposal.md). The **Detailed RFC** section is incomplete. Essential aspects of that are not explained like: 

- What are the impacts of the change?
- What are the benefits of that?

Why not add `cons *const` (or similar) to all the fields that should not change at all at runtime?

**Comment by carlescufi** [comment]
Architecture WG:

- There is some reluctance to accept this change given the size of the change vs the gains, which are very small
- @LingaoM could you please do the following:
   1. Document the memory savings for each net_buf_pool
   2. Respond to "An obvious question that can come up is: "Why not add cons *const (or similar) to all the fields that should not change at all at runtime?""
   3. Extend this issue so that it complies with the RFC template

**Comment by cfriedt** [comment]
Many of our API structures are broken into `data` (rw) and `config` (ro) components. I can understand the reasoning here, because we typically want to avoid something like a stack overflow breaking function pointers.

I'm not sure if `net_buf_pool_rt_ctx` is as descriptive as it could be (I like the `data` and `config` conventions personally).

I guess the bigger question is that it would be a breaking API change.
