### ISSUE TITLE
[Coverity CID: 183059] Memory - corruptions in /samples/net/mbedtls_dtlsclient/src/dtls_client.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6673]
Static code scan issues seen in File: /samples/net/mbedtls_dtlsclient/src/dtls_client.c
 Category: Memory - corruptions
 Function: dtls_client
 Component: Samples
 CID: 183059
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by sritej20** [comment]
Can be closed as they are false positives same as #6695 , #7509 , #7510 . The structs can have different sizes only if different config files are loaded for the test tool and the source code. Since this cant be possible as the CONFIG_MBEDTLS_CFG_FILE="config-***.h" is passed the prj.conf file of each of the samples code, which in turn is used to compile the source code , the struct's will have the same size as when declared and memset .
