### ISSUE TITLE
[Coverity CID: 183030] Memory - corruptions in /drivers/console/uart_console.c

### ISSUE THREAD

**Issue by Shilpashree3lc** [zephyrproject-rtos/zephyr#6702]
Static code scan issues seen in File: /drivers/console/uart_console.c
 Category: Memory - corruptions
 Function: uart_console_isr
 Component: Drivers
 CID: 183030
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by pfalcon** [comment]
This issue was apparently assigned to me by mistake, I'm not the owner of drivers/console/uart_console.c
(I am of subsys/console/). The relevant code was added by Johan un 
8683dc4836e78fd233ef55db157e4d3f29be6f68. At the same time, trying to look at CID 183030 says that it has status of "Fixed", even the code looks the same as before. Fairly speaking, even the original error was a bit confusing:

> CID 183030 (#1 of 1): Out-of-bounds access (ARRAY_VS_SINGLETON)
> 17. callee_ptr_arith: Passing &esc_state to function atomic_test_and_clear_bit which uses it as an array. This might corrupt or misinterpret adjacent memory locations. [show details]

Perhaps, an issue was on the side of  atomic_test_and_clear_bit() and was fixed there. Either way, if Coverity says it's Fixed, closing this.
