### ISSUE TITLE
net: ppp: doc: PPP documentation page ('connectivity/networking/api/ppp') needs updating

### ISSUE THREAD

**Issue by kartben** [zephyrproject-rtos/zephyr#67171]
**Describe the bug**

Spotted two issues with [PPP documentation page](https://docs.zephyrproject.org/latest/connectivity/networking/api/ppp.html) while looking for dead links in the documentation:

- "See also the [samples/net/sockets/echo_server/overlay-ppp.conf](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/net/sockets/echo_server/overlay-ppp.conf) file for configuration option examples." is a dead link.
- "The PPP support in Zephyr 2.0 is still experimental [...]" sentence needs updating

**Environment**

* Page: `connectivity/networking/api/ppp`
* Version: main
* SHA-1: 69d19ae9fb68d0be38ceb22ba43c9fff985cbbaa

**Comment by cfriedt** [comment]
@jukkar - a really long time ago, I had a development branch that moved HDLC to its own library, since it can be used even without the IP layer. I know of one product that used that over a board-level uart connection, but that's mainly it.

The nice thing about a library implementation is that it can be separately tested. Would that be a worthwhile change?

**Comment by jukkar** [comment]
> The nice thing about a library implementation is that it can be separately tested. Would that be a worthwhile change?

Sure, that sounds like a good change, please submit to upstream for a review.
