### ISSUE TITLE
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC is not right for acrn_defconfig 

### ISSUE THREAD

**Issue by bensenq** [zephyrproject-rtos/zephyr#69318]
**Describe the bug**
defconfig for x86 acrn boards declares:
```
# boards/x86/acrn/acrn_defconfig
CONFIG_APIC_TSC_DEADLINE_TIMER=y
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=25000000
```
This is definitely not right as TSC frequency is the CPU Core Freq which should not be 25MHz small.

Please also mention any information which could help others to understand
the problem you're facing:
 - What target platform are you using? x86
 - What have you tried to diagnose or workaround this issue? Runing a sleep test app.

**Impact**

Time/timeout not work correctly.

**Comment by jhedberg** [comment]
@bensenq would you like to submit a pull request to fix this?

**Comment by jhedberg** [comment]
@nashif @dcpleung @najumon1980 fyi

**Comment by najumon1980** [comment]
Yes this is wrong and TSC APIC timer frequency will be the processor’s bus clock or core crystal clock frequency divided by the value specified in the divide configuration register. But core clock frequency varies from platform to platform and even with different SKUs (for Intel platforms it usually from ~1GHz to ~4GHz).  But even with same platform type (for different SKU) this can be changed. **So best way is read via CPUID/MSR and then configure dynamically instead of kernel/app using via static macro CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC.** But this might need a wider discussion.

**Comment by najumon1980** [comment]
it seems dynamic reading supported if CONFIG_TIMER_READS_ITS_FREQUENCY_AT_RUNTIME enabled. But looks currently it not implemented for APIC timer driver. Also the kernel/test codes still using CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC instead of using sys_clock_hw_cycles_per_sec() and this also need to fix.

**Comment by bensenq** [comment]
> @bensenq would you like to submit a pull request to fix this?

why not just use HPET or APIC Timer? It seems to be more stable.
```
# TSC on this board is 1.9 GHz, HPET and APIC are 19.2 MHz
config SYS_CLOCK_HW_CYCLES_PER_SEC
        default 1900000000 if APIC_TSC_DEADLINE_TIMER
        default 1900000000 if APIC_TIMER_TSC
        default 19200000
```

**Comment by najumon1980** [comment]
Created a PR:https://github.com/zephyrproject-rtos/zephyr/pull/69705 for the issue and please have a look:

**Comment by najumon1980** [comment]
> > @bensenq would you like to submit a pull request to fix this?
> 
> why not just use HPET or APIC Timer? It seems to be more stable.
> 
> ```
> # TSC on this board is 1.9 GHz, HPET and APIC are 19.2 MHz
> config SYS_CLOCK_HW_CYCLES_PER_SEC
>         default 1900000000 if APIC_TSC_DEADLINE_TIMER
>         default 1900000000 if APIC_TIMER_TSC
>         default 19200000
> ```

APIC/TSC timer clock frequency will be varied with platform to platform as well SKUs within same platforms. So we need to use run time support for Intel platforms.
