### ISSUE TITLE
Hal: NXP: Typo in fsl_iomuxc.c for MIMXRT1041, MIMXRT1042, MIMXRT1051, MIMXRT1052, MIMXRT1062, MIMXRT1064

### ISSUE THREAD

**Issue by allemanm** [zephyrproject-rtos/zephyr#69911]
**Describe the bug**
In fsl_iomuxc.c is the macro IOMUXC_GPIO_SD_B1_08_LPSPI2_SD0 defined for boards: MIMXRT1041, MIMXRT1042, MIMXRT1051, MIMXRT1052, MIMXRT1062, MIMXRT1064. This is not consistent with other MIMXRT variants or other similar macros for instance IOMUXC_GPIO_EMC_28_LPSPI1_SDO.

**Expected behavior**
The macro should have the following name: IOMUXC_GPIO_SD_B1_08_LPSPI2_SDO. The last character should be replaced by O.

**Impact**
No impact

**Comment by danieldegrasse** [comment]
@allemanm Thanks for reporting this- I don't think we will rename the identifier here though. Once these identifiers are included in an SDK release it is unfortunately often more churn for customers to change them than it is to leave the inconsistency (since a new identifier will break builds for anyone using the old one)
