### ISSUE TITLE
tests/kernel/smp: Test fails, scheduler schedules the threads on only one core

### ISSUE THREAD

**Issue by spoorthik** [zephyrproject-rtos/zephyr#7020]
The test at tests/kernel/smp is failed as it is scheduling the threads on only one core. Please refer the sample log:

**Board used:** ESP32

**build/zephyr/.config:**

CONFIG_SMP=y
CONFIG_MP_NUM_CPUS=2

I just added few prints in the code, to recheck that, 
```
@@ -21,11 +21,14 @@ K_THREAD_STACK_DEFINE(t2_stack, T2_STACK_SIZE);
 struct k_thread t2;
 
 volatile int t2_count;
+int main_core, t2_core;
 
 #define DELAY_US 50000
 
 void t2_fn(void *a, void *b, void *c)
 {
+       t2_core = _arch_curr_cpu()->id;
+
        ARG_UNUSED(a);
        ARG_UNUSED(b);
        ARG_UNUSED(c);
@@ -46,7 +49,8 @@ void t2_fn(void *a, void *b, void *c)
 void test_main(void)
 {
        int i, ok = 1;

+       main_core = _arch_curr_cpu()->id;
        /* Sleep a bit to guarantee that both CPUs enter an idle
         * thread from which they can exit correctly to run the main
         * test.
@@ -67,7 +71,7 @@ void test_main(void)
                 */
                k_busy_wait(DELAY_US + (DELAY_US / 8));
 
-               if (t2_count <= i) {
+               if (t2_count <= i && main_core == t2_core) {
                        ok = 0;
                        break;
                }
@@ -76,6 +80,7 @@ void test_main(void)
        if (ok) {
                TC_END_REPORT(TC_PASS);
        } else {
+               printk("t2_core = %d, main_core = %d\n", t2_core, main_core);
                TC_END_REPORT(TC_FAIL);
        }
 }

```

**Sample log:**

```

***** Booting Zephyr OS v1.11.0-613-g85e8eaa *****
t2_core = 0, main_core = 0
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by andyross** [comment]
Yeah, that looks like a bug.  The failure is clear, but FWIW: the logging of CPU IDs isn't informative.  The main thread can exit the sleep (or the k_thread_create call, in fact) on a different CPU than it started on.  What this looks like is that the secondary thread never runs at all, so t2_core is left at zero from static initialization.

Did you try a quick bisection to the 1.11 release?  I know it was working there. There are some changes to the asm2 layer and to the scheduler that have gone in since that could conceivably have broken it.  Will check in the morning.

**Comment by andyross** [comment]
Got it.  Took a while to see, because it's timing related.  My WROVER board worked, as did the WROOM board I had at home.  But the WROOM on my desk fails every time, and it turns out if you do a bunch of reboots you can get any of these to fail or succeed randomly.

The root cause is the _smp_global_lock() abstraction, which replaces irq_lock() in SMP code.  It's wrong in two ways, one is a giant whopper (that results in the lock being mostly a noop) and one is more subtle (that would have deadlocked the system if the whopper bug hadn't hidden it).  Working on a fix now.

**Comment by spoorthik** [comment]
Fix is merged, the issue is no more seen.
