### ISSUE TITLE
Have Sphinx search display txt not ReST as results

### ISSUE THREAD

**Issue by mgielda** [zephyrproject-rtos/zephyr#7032]
We had this issue in our own documentation once and managed to fix it by some clever Makefile tricks so I thought I'd take this up.

If you make a search in the Zephyr docs, like:

http://docs.zephyrproject.org/search.html?q=device+tree&check_keywords=yes&area=default

You get results in unrendered ReST, which is kind of unreadable (especially for headers). This is because the search looks in the sources directory which contains ReST files and outputs content directly from them. This can be worked around by producing text files instead.

I think @dbkinder is probably the right person to mention here, I saw you are involved in most Sphinx-related stuff.

**Comment by dbkinder** [comment]
There have been attempts by the community to address this over the years (as noted in https://github.com/sphinx-doc/sphinx/issues/1618 for example) including hacks to patch the problem (such as https://pypi.python.org/pypi/sphinxprettysearchresults).

We've also had a (long standing) issue associated with the zephyrproject.org website to use Google search instead of the docs-restricted Sphinx search so search results would return hits from all zephyrproject.org sites (www.zephyrproject.org, docs.zephyrproject.org, wiki.zephyrproject.org, lists.zephyrproject.org).  You can simulate this by using the google **site:** option, such as in https://www.google.com/search?&q=site:zephyrproject.org+intel

The one nice thing about the current Sphinx search is it's confined to the current doc set version (e.g., if you're viewing an archived version of the docs, say the [1.10 version](http://docs.zephyrproject.org/1.10.0/index.html), the search results returned are within the 1.10 document set and not from other versions.  We can't control that if we're using Google search, and with Google search, we'd have hits from all visible versions of the docs unless we use a robots.txt to restrict Google scans (something that was [rejected when proposed earlier](https://github.com/zephyrproject-rtos/zephyr/pull/4978)).

That said, I'll see what minimal tweak we can do to at least change the display of the raw ReST format from search results.

**Comment by mgielda** [comment]
Thanks for the extensive answer @dbkinder - I know there have been attempts to address this. Of course, searching more broadly is not something we can achieve (easily) with Sphinx, but I was thinking of improving the current readability situation if possible. How I solved this in our case was:

1) generate `txt` files with `make text`
2) change the generated files to have a `rst` extension and put them in the `sources` directory (overwriting the original `rst` files)

There may be an easier way to do this, but this just worked. The search results looked nicer. 
A more minimalistic but not so bad solution is to change the CSS for the `.context` class

```css
    white-space: pre;
    font-family: Courier;
```

**Comment by nashif** [comment]
fixed

**Comment by mgielda** [comment]
@nashif @dbkinder I daresay the `white-space: pre;` is still a good idea, see below:
![screenshot from 2018-04-23 19-56-32](https://user-images.githubusercontent.com/140166/39144375-e8213884-4730-11e8-8091-32e498727c89.png)
![screenshot from 2018-04-23 19-59-41](https://user-images.githubusercontent.com/140166/39144376-e8404a6c-4730-11e8-9490-1b1536e4c9a1.png)
