### ISSUE TITLE
doc build kconfig warning for XOROSHIRO_RANDOM_GENERATOR

### ISSUE THREAD

**Issue by dbkinder** [zephyrproject-rtos/zephyr#7097]
It's not stopping the doc build, but a warning is reported by the script used to create the configuration options documentation:

    warning: default on the choice symbol XOROSHIRO_RANDOM_GENERATOR
    (defined at subsys/random/Kconfig:50,
    arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.mkw41z4:65)
    will have no effect

**Comment by ulfalizer** [comment]
@dleach02 
It will be ignored as long as `subsys/random/Kconfig` is included at least, since that's what makes it a choice symbol. See these issues as well: https://github.com/zephyrproject-rtos/zephyr/issues/7120, https://github.com/zephyrproject-rtos/zephyr/issues/7054

An easy way to tell whether the `default` is being ignored is to check if you get the warning.

Another complication for the second issue linked above that choices do not prefer later defaults (I think people forgot to change it there). Otherwise, you would have been able to override a choice default in a `Kconfig.defconfig` file by giving the choice a name and doing something like this:

```
choice NAME
    default XOROSHIRO_RANDOM_GENERATOR

endchoice
```

https://github.com/zephyrproject-rtos/zephyr/issues/6890#issuecomment-377909641 provides an overview of what I think the thinking behind the design is by the way. It wasn't obvious to me.

**Comment by dleach02** [comment]
In the end, I need a way to force the KW41 to use XOROSHIRO without messing with every other platform that selects a random number generator source. I too am a bit confused about the configuration hierarchy and how this all works. I see the warning but "somehow" it works for me??? Not a satisfying result though when one doesn't fully understand what is going on.

**Comment by nashif** [comment]
@dleach02 it works for you because you have it set also in `boards/arm/frdm_kw41z/frdm_kw41z_defconfig` maybe?

**Comment by dleach02** [comment]
Maybe. Question: What is the right way then to ensure that the XOROSHIRO gets selected for KW41 based boards?

**Comment by nashif** [comment]
2 options I can see now:
1. keep the choice and set this per board
2. remove the choice completely and make it selectable in SoCs.

**Comment by nashif** [comment]
opting for option 1 now, revisit this an implement a better solution later. lowering priority for now
