### ISSUE TITLE
Section type conflict when using CONFIG_LOG_FMT_SECTION in C++

### ISSUE THREAD

**Issue by Jokubaskaralius** [zephyrproject-rtos/zephyr#73455]
The most minimal example that I can think of to reproduce the issue is to have configuration enabled:

```
CONFIG_LOG=y
CONFIG_LOG_FMT_SECTION=y
CONFIG_CPP=y
```

Upon compiling source code below with arm-zephyr-eabi-g++ (Zephyr SDK 0.16.5-1) 12.2.0:
 
```
#include <stdio.h>
#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(app, 4);

class TestClass {
public:
    void Try() {
        LOG_ERR("Try");
    }
};

int main(void)
{
    LOG_INF("Hello World! %s\n", CONFIG_BOARD_TARGET);

    TestClass foo;
    foo.Try();
    return 0;
}
```

Getting the error `'_fmt' causes a section type conflict with '_fmt'`. If opting to not use the class and use the logging macros in the function directly, there seem to be no compilation issues.

Looking at the main.cpp.s file the only difference we can see is the name mangling and that there's an additional .weak directive for the symbol   `_ZZN9TestClass3TryEvE4_fmt` in the non-working example.

Note: we get the error both on v3.3 zephyr and on main branch (git hash for convenience: 4efc03520966a96e1a5dcf5369f75503626c2b42). For this example I used qemu_x86 but it's the same on nrf53 based board.

**Comment by quinnabrvau** [comment]
Can this be reopened? it's quite annoying to have to work around this limitation. 

I spent some time digging into the issue is with these lines
https://github.com/zephyrproject-rtos/zephyr/blob/8748a056f0d8b8aa15f6c9203c34a1849960f1bf/include/zephyr/logging/log_msg.h#L445-L450
What is happening here is gcc wants to put the C strings in functions into .rodata as I would expect, but for some reason it wants to put the C strings for the class into a different memory region. The class behavior surprises me because all const char[] should be in .rodata and just be referenced by a pointer. 

I tried a few things for C++ like using constexpr instead of const but nothing seemed to help.
