### ISSUE TITLE
Fix confusing wording about "test suite", "test", "test identifier", "test case", "test case project", "test projects", and "test scenario"

### ISSUE THREAD

**Issue by yashi** [zephyrproject-rtos/zephyr#74151]
**Describe the bug**

The first sub-section in the "[Test Framework](https://docs.zephyrproject.org/latest/develop/test/ztest.html#test-framework)" is "[Creating a test suite](https://docs.zephyrproject.org/latest/develop/test/ztest.html#creating-a-test-suite)".  The sub-section states:

> Using Ztest to create a test suite is as easy as calling the `ZTEST_SUITE`.

Thus, readers, including me, assume that a "test suite" is something we define using `ZTEST_SUITE()`.  The first argument to the macro is `SUITE_NAME` as documented in https://docs.zephyrproject.org/apidoc/latest/ztest__test_8h.html .

The next sub-section is "[Adding tests to a suite](https://docs.zephyrproject.org/latest/develop/test/ztest.html#adding-tests-to-a-suite)". It says:

> [ZTEST](https://docs.zephyrproject.org/latest/develop/test/ztest.html#c.ZTEST) `(suite_name, test_name)` - Which can be used to add a test by `test_name` to a given suite by `suite_name`.

So if you have

```c
ZTEST(my_suite, test_my_test)
{
}
```

We all assume `my_suite` is a test suite and `test_my_test` is a test.  In fact, if you ask twister to print list of tests, it sort of prints the test I just added:

```
$ ./scripts/twister ... --list-tests
[...]
 - sec.sub.my_test
```

Now if you go to the next section, [Test Runner (Twister)](https://docs.zephyrproject.org/latest/develop/test/twister.html#test-runner-twister), you encounter a section called [Test Cases](https://docs.zephyrproject.org/latest/develop/test/twister.html#test-cases), which reads:

> Test cases are detected by the presence of a testcase.yaml or a sample.yaml files in the application’s project directory. This file may contain one or more entries in the test section each identifying a test scenario.

As I understand, this paragraph says:

- there is something called "test case".
- the entries in `.yaml` files are  test scenarios

And the following sentence makes me read more than twice.

> The name of each testcase needs to be unique in the context of the overall testsuite and has to follow basic rules:

"test case" is not defined here, but if you go back to "Test Framework, you can find:

> A test case project may consist of multiple sub-tests or smaller tests that either can be testing functionality or APIs.

With this, we can assume that "test case" is a project?

It also says "test case" must be unique _ in the context of the overall testsuite_. Remember test suite is some thing we defined in `.c`. Or is "testsuite" different from "test suite"?

And the following list talk about "test identifier" and not "testcase".  is "test identifier" a name of a testcase?

farther you go, on to `testcase.yaml` and the out put of `twister -h`, you get more confused by these words.

This came to me when I wanted to run a single test in my test suite.  That's doable for many non-embedded testing frameworks.  Thus, I first assumed that we can also do it.

**Expected behavior**
A clear and concise usage of the following words:

- "testsuite"
- "test suite"
- "test"
- "test identifier"
- "test case"
- "test scenario"
- "test case project"
- "test project"

**Impact**

Confusing.

**Additional context**

If you can tell me which is what, I can create a PR for this.  I hope my description is clear enough to realize that we have some wording problem. Thanks.

**Comment by PerMac** [comment]
we tried to fix this in https://github.com/zephyrproject-rtos/zephyr/discussions/31090. There is a pdf with my proposal which I believe we agreed on but it is already out date since it was before ztest rework. However, might give some more insight.

We agreed that "[test] configuration" = certain "test scenario" on certain "platform" 
"test scenario" is a "test" entry in test/sample.yaml
a "configuration" links to a particular build image.

The idea was that test cases are the smallest unit, and back then only made sense when referring to ZTEST (test_name). Now we also can have such layer in pytest tests, although, those are not yet treated individually nor reported that way.

"test identifier" refers to "test scenario". IMO this section shouldn't be called Test Cases as this is the most confusing. I believe "test identifier" was added later on, and the name might make more sense than "test scenario". 

IMO one of the culprits might be the name of section "tests" in the testcase.yaml and the file name "testcase.yaml" itself. "tests" don't have info about tests but rather build configurations for the whole app. So you can have several "tests" in yaml, but in fact the same tests (e.g. matching regex, or ztest suites) will be executed on all of them. 
They only can be considered a test when dealing with entries that have "harness: console", as e.g. hello_world sample. In that case these entries define tests, by providing at least some conditions that have to be passed, but it is as special case, not a rule.  

ZTest defines "SUITE" which is yet another thing. AFAIK a single built application can call several SUITs, right? Therefore, ztest suite cannot easily be linked to "test identifier" nor "test configuration". 

I think we need to again go back to all this names, figure out what is what and how we want to call it, and then align docs

**Comment by PerMac** [comment]
reading
``` 
To run all tests defined in a test project, run:

./scripts/twister -T tests/foo/bar/
```
I assume here "test projects" refer to the whole directory where testcase/sample.yaml is located, otherwise it would tell to call `-s/--test`. Later calls to "test project" seems to refer to a level of a full executed application so probably "scenario"? But those are my guesses
