### ISSUE TITLE
pm: Implementation of wakeup capability in drivers is inconsistent with documentation

### ISSUE THREAD

**Issue by jakubtopic** [zephyrproject-rtos/zephyr#74897]
**Describe the bug**
According to the [documentation](https://docs.zephyrproject.org/latest/services/pm/device.html#wakeup-capability) and [description](https://github.com/zephyrproject-rtos/zephyr/blob/a9456221cd73d7026cda3fe3e1ed72de42c7665d/dts/bindings/base/pm.yaml#L7-L17) of the `wakeup-source` property, this property sets a `pm_device` flag indicating that the device is capable of waking up the system. It is the responsibility of the user application to enable this capability by calling `pm_device_wakeup_enable()`. However, there is currently no way to notify the device drivers that this capability has been enabled. Because of that, the current implementation in existing drivers enables the capability upon device initialization, which is not the expected behavior.

**Expected behavior**
Device drivers should only enable the wakeup capability when the user application explicitly calls `pm_device_wakeup_enable()`. The capability should not be enabled automatically upon device initialization.

**Impact**
This bug causes the wakeup capability to be enabled prematurely, potentially leading to unintended wakeups and inconsistent power management behavior. It prevents the user from enabling or disabling this feature dynamically.

**Additional context**
Examples of affected devices:
- nxp,hci-ble
  https://github.com/zephyrproject-rtos/zephyr/blob/a9456221cd73d7026cda3fe3e1ed72de42c7665d/drivers/bluetooth/hci/hci_nxp.c#L421-L423
- nxp,lpc-rtc
  https://github.com/zephyrproject-rtos/zephyr/blob/a9456221cd73d7026cda3fe3e1ed72de42c7665d/drivers/counter/counter_mcux_lpc_rtc.c#L408-L411 
- nxp,os-timer
  https://github.com/zephyrproject-rtos/zephyr/blob/a9456221cd73d7026cda3fe3e1ed72de42c7665d/drivers/timer/mcux_os_timer.c#L267-L269

**Comment by ceolin** [comment]
> **Describe the bug** According to the [documentation](https://docs.zephyrproject.org/latest/services/pm/device.html#wakeup-capability) and [description](https://github.com/zephyrproject-rtos/zephyr/blob/a9456221cd73d7026cda3fe3e1ed72de42c7665d/dts/bindings/base/pm.yaml#L7-L17) of the `wakeup-source` property, this property sets a `pm_device` flag indicating that the device is capable of waking up the system. It is the responsibility of the user application to enable this capability by calling `pm_device_wakeup_enable()`. However, there is currently no way to notify the device drivers that this capability has been enabled. Because of that, the current implementation in existing drivers enables the capability upon device initialization, which is not the expected behavior.

It may be confuse but I am not sure if it is inconsistent. There is a note in documentation that says:

"""
This property is only used by the system power management to identify devices that should not be suspended. It is responsibility of driver or the application to do any additional configuration required by the device to support it.
"""

This property is just used by the power management subsystem to avoid suspend devices that are used as wake up sources.

Maybe the problem is the lack of guidance of how devices should do it. Right now the way to do this from a device that requires additional configuration is no register a callback for a notification from when the system is about to sleep and in this callback checking if this property is set and take the necessary action.

I particularly liked the idea of inform the device when this API is called, but I need to think more about it.

That's said if the documentation is causing this kind of doubts it is because it needs improvements, I will change it to reflect the current state.

**Comment by jakubtopic** [comment]
@ceolin, thanks for the clarification. I agree that driver developers need more guidance on interfacing with the PM subsystem. Additionally, it’s important to distinguish that while the hardware determines if a device is capable of waking up the system, the decision to issue wakeup events is a policy managed by user space.

> Right now the way to do this from a device that requires additional configuration is no register a callback for a notification from when the system is about to sleep and in this callback _checking if this property is set_ and take the necessary action.

This approach is sound. However, instead of relying on a static device tree property, drivers should check the runtime PM info.

I will consider this further and familiarize myself with this Zephyr subsystem. Here’s a thought: rather than requiring drivers to register an additional notifier for system power state changes, why not use the existing `pm_action_cb` interface? The PM subsystem could issue suspend actions to all PM-aware devices, including those enabled as wakeup sources. The device would then either suspend or activate the necessary interrupts to wake up the system if wakeup capability is enabled. This approach aligns more closely with how Linux handles it, I think.
