### ISSUE TITLE
Odroid Go Boot Failure

### ISSUE THREAD

**Issue by gschwaer** [zephyrproject-rtos/zephyr#76447]
> [!NOTE]
> This issue will be fixed by https://github.com/zephyrproject-rtos/zephyr/pull/76383. The issue is just for backporting purposes, see https://github.com/zephyrproject-rtos/zephyr/pull/76383#issuecomment-2254252661.

**Describe the bug**

On the latest Zephyr release 3.7.0, an image generated with, e.g.,
```text
west build -p always -b odroid_go/esp32/procpu zephyr/samples/hello_world
```
does not boot. The UART output reads as follows:
```text
[...snip...]
I (124) quad_psram: This chip is ESP32-D0WD
I (124) esp_psram: Found 4MB PSRAM device
I (125) esp_psram: Speed: 40MHz
I (125) esp_psram: PSRAM initialized, cache is in normal (1-core) mode.
SPIRAM size is less than configured size, aborting.
abort()
```

**To Reproduce**

1. `west build -p always -b odroid_go/esp32/procpu zephyr/samples/hello_world`
2. `west flash`
3. connect to uart and power cycle board

**Expected behavior**

Boot successfully.

**Impact**

Showstopper

**Logs and console output**

see above

**Environment (please complete the following information):**

 - OS: Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: `v3.7.0` also `main`

**Additional context**

N/A

**Comment by rftafas** [comment]
Please, check around as support was not added to this chip and we (we = Espressif) don't have it on our roadmap, as this device is NRND. Support for ESP32 starts with Rev3 (which was the recommended device when we joined the project in 2020). While it boots, there are bugs, instabilities, security concerns, etc.

PTAL: https://github.com/zephyrproject-rtos/zephyr/issues/51622

Main reason we didn't add a block yet or added it to documentation for now is because community may decide to do it, as it is opensource (they can look into ESP-IDF and port code to workaround bugs and etc). We are debating internally on adding some form of [INFO]+experimental option to force awareness of this issue.
