### ISSUE TITLE
doc: Documentation issue in 'boards/aspeed/ast1030_evb/doc/index'

### ISSUE THREAD

**Issue by igudich** [zephyrproject-rtos/zephyr#77118]
**Describe the bug**

Link [Aspeed Zephyr SDK User Guide](https://github.com/AspeedTech-BMC/zephyr/releases/download/v00.01.03/Aspeed_Zephy_SDK_User_Guide_v00.01.03.pdf) is broken.

**Environment**

* Page: `boards/aspeed/ast1030_evb/doc/index`
* Version: main
* SHA-1: 8dc3f856229ce083c956aa301c31a23e65bd8cd8

**Comment by ttmut** [comment]
It seems the document has been removed from their github page.

**Comment by kartben** [comment]
@kane-chen-as @stevenlee7189 can you help?

**Comment by aspeeddylan** [comment]
Due to Aspeed Technology’s policy, the SDK User Guide is no longer available for download on Aspeed’s GitHub. Please contact your ASPEED representative to obtain the SDK User Guide. I will address this issue by making a commit to update the documentation and adding a description in boards/aspeed/ast1030_evb/doc/index.rst.

**Comment by kartben** [comment]
link is no longer a 404 as per https://github.com/zephyrproject-rtos/zephyr/issues/77118#issuecomment-2295564528
