### ISSUE TITLE
net: Loopback broken: Packets sent locally to loopback address are now dropped 

### ISSUE THREAD

**Issue by GAnthony** [zephyrproject-rtos/zephyr#7821]
Previously, packets sent locally to the the loopback address 127.0.0.1 were returned to the sender (as expected).  

The commit 68ef8f06a5082ee3baa4128c4fe8e84832f22a57 broke this behaviour, by adding an is_invalid_packet() function which results in dropping packets sent locally from the loopback address.

This issue breaks the WIP MQTT over sockets PR #5854, which relies on the loopback address for a socket server restart. 

Possible solution: pass the is_loopback flag from the process_data() function on to the net_conn_input() function into the is_invalid_packet() call so that the loopback packets are not dropped.

**Comment by pfalcon** [comment]
> The commit 68ef8f0 broke this behaviour

This commit broke the behavior, because it was buggy. 4dd5867a79b8919c89e1f19544480446af51d6d8 fixed it. Can you please retest with the latest master?

If you look at the cumulative change, the check added makes a good sense, in particular, it triggers only if source and dest port numbers are the same - which should happen very rarely in the real life on its own, and never when src addr is also a local addr. If we with @rmstoi miss something there, we'd be glad to know.

**Comment by GAnthony** [comment]
@pfalcon, yes, verified, fixed with 4dd5867.  
Thanks.
