### ISSUE TITLE
Incorrect ADC Output Data Formatting on EFR32BG22 IADC Peripheral

### ISSUE THREAD

**Issue by tbitcs** [zephyrproject-rtos/zephyr#78366]
**Describe the bug**
The EFR32BG22 MCU's IADC peripheral supports flexible output formatting, allowing configurations for 12-bit, 16-bit, and 20-bit data formats with programmable left or right alignments. The default reset value of the ALIGNMENT register sets the ADC output data to 12-bit right-aligned. However, the default Gecko driver implementation assumes the ADC output data to be 12-bit left-aligned, with no option to cleanly change the data alignment. As a result, EFR32BG22 MCU's (and likely many others as well) return incorrect ADC values due to this assumption.

**Workaround**
Modify the `GECKO_DATA_RES12BIT(DATA)` macro to use the correct 12-bit mask without a shift, accommodating the right alignment.

This is the patch for iadc_gecko.c (zephyr\zephyr\drivers\adc\iadc_gecko.c):

![image](https://github.com/user-attachments/assets/f22ef5ac-5202-47d3-bd3d-1b0bde93d838)
*Left: Original, Right: Patch*

**Proposed Fix**
Introduce a new child ADC node property to define the ADC output alignment, and apply the correct register configuration, as well as the appropriate shift and masking, based on the selected data format.

|  Name            | Type   | Details                                           |
| ---------------- | ------ | ------------------------------------------------- |
| zephyr,alignment | string | Legal values: `ADC_ALIGN_LEFT`, `ADC_ALIGN_RIGHT` |

**To Reproduce**
1. Configure the IADC on an EFR32BG22 (e.g., BG22 Thunderboard).
2. Write a small program to take ADC readings.
3. Compare the input voltage to the output reading from the ADC and observe incorrect readings.

**Expected behavior**
The output reading from the ADC should correctly correlate with the input voltage based on the selected alignment.

**Impact**
This issue causes incorrect ADC values due to misinterpretation of the ADC output data format.

**Logs and console output**
N/A

**Environment**
- OS: Windows 11
- Toolchain: Zephyr SDK 0.16.3
- Zephyr Version: v3.5.0

**Additional Context**
Would this issue warrant spawning a **feature request** that introduces a more flexible solution, addressing the ADC output alignment configuration for **any part**, not just for the EFR32BG22? A general feature could provide options for configurable alignment and bit-width across multiple platforms.

**Comment by asmellby** [comment]
When it comes to the bug, it seems to have already been fixed in #67399.

As for the proposal for a more flexible solution: I don't think specifying alignment is sufficient to make it a useful configuration option for users of the driver, as there is nothing to guarantee that the `void *buffer` used by the API for samples has a certain layout:

> The buffer must be of an appropriate size, taking into account the number of selected channels and the ADC resolution used, as well as the number of samplings contained in the sequence. 

It seems to me that the API allows drivers to put 12-bit samples into either 16-bit or 32-bit words, or even densely packing them 2 samples per 3 bytes, and that this is all driver-specific. Without also specifying the expected bit width of each sample in the buffer, it's not possible to know what to align the sample _to_.

Also: DeviceTree is intended to describe the hardware. The alignment of samples within a buffer seems to me to maybe stray too far towards being software configuration rather than hardware configuration, despite technically being a question of "if you dump hardware register state into a buffer without modifying it, what format does it have?". Even if the sample alignment properties of the hardware are exposed and implemented by the driver, the user of the ADC API doesn't really gain anything from it at a generic level. If they know which hardware they're using, they get some more control of the layout of the buffer, but it doesn't transfer between implementations. As such, it might be more appropriate as a Silabs-specific property if it was to be added.

Since the bug on EFR32 was already fixed in 3.6 and 3.5 is EOL, I'm closing this bug report.

@anangl @decsny How do you want to handle the secondary feature request?
