### ISSUE TITLE
Button example is not using `gpio-keys` driver

### ISSUE THREAD

**Issue by arifbalik** [zephyrproject-rtos/zephyr#78813]
The [basic button example](https://docs.zephyrproject.org/latest/samples/basic/button/README.html) shows the use of [`gpio-keys`](https://docs.zephyrproject.org/latest/build/dts/api/bindings/input/gpio-keys.html) but does not use the [input subsys](https://docs.zephyrproject.org/latest/services/input/index.html) to read the button events, instead it initializes the gpio pin again and reads it with GPIO API.

It has to be decided if this example wants to show how to use GPIO API or how to use `gpio-keys`. If the answer is GPIO API, `zephyr-user` can be used;

```devicetree
#include <zephyr/dt-bindings/gpio/gpio.h>

/ {
     zephyr,user {
             signal-gpios = < &gpio0 PIN FLAGS >;
     };
};
``` 

Alternatively, `gpio-keys` can be used fully and input subsystem can be showcased.

**Comment by fabiobaltieri** [comment]
Yeah the two examples (blinky and button) are essentially "gpio output" and "gpio input", they were created before the respective subsystems (leds and input).

What are you proposing exactly? The input sample is there and it's pretty much just an empty option (all the debugging code is part of the subsystem). Moving the node in `zephyr,user` does not make much sense to me, the current alias works just fine and allows for buttons to be used with both the subsystem or directly.

**Comment by arifbalik** [comment]
Well, it kinda creates a confusion, at least it did for me. Also there is not a simple example showing how `input` works with individual buttons and switches. My proposal is that we use `input` api

**Comment by fabiobaltieri** [comment]
> Well, it kinda creates a confusion, at least it did for me. Also there is not a simple example showing how `input` works with individual buttons and switches. My proposal is that we use `input` api

Ok now we are getting somewhere, that's the issue.

The simple example for input is https://docs.zephyrproject.org/latest/samples/subsys/input/input_dump/README.html, it really does not get much simpler than that, there's [no code](https://github.com/zephyrproject-rtos/zephyr/blob/main/samples/subsys/input/input_dump/src/main.c), it just prints any input event, buttons and everything else.

This is linked from the button sample doc (https://docs.zephyrproject.org/latest/samples/basic/button/README.html) but I think that there's some discoverability issue because I've heard people saying that Zephyr has no debounced input driver while it's just there waiting to be used.

Is that what you expected? How do you think we could make that easier to find? Maybe a comment in the button code as well?

**Comment by arifbalik** [comment]
Exactly, the reason i opened the issue is precisely this because I did write my own debounced button driver. Although I was happy about the implementation which was very similar :)

**Comment by fabiobaltieri** [comment]
Thanks, yeah if you could open a PR with an extra comment in the code it'd be much appreciated.

**Comment by arifbalik** [comment]
Oh, my bad, it seems like you've added this note 2 months ago; https://github.com/zephyrproject-rtos/zephyr/commit/2455291da85cfd31529b00bd89eb66232a50a9b6#diff-2912957f693319cfdabe6cf4c2ccecba7c25c2123c0c58b1d5433cad090ed707R13

I would like to write another example, reading buttons with `input` if you think discoverability is still an issue.

**Comment by fabiobaltieri** [comment]
> Oh, my bad, it seems like you've added this note 2 months ago; [2455291#diff-2912957f693319cfdabe6cf4c2ccecba7c25c2123c0c58b1d5433cad090ed707R13](https://github.com/zephyrproject-rtos/zephyr/commit/2455291da85cfd31529b00bd89eb66232a50a9b6#diff-2912957f693319cfdabe6cf4c2ccecba7c25c2123c0c58b1d5433cad090ed707R13)

Yeah, it was after listening an episode of the Embedded FM podcast where the guest said that Zephyr did not have any button debouncing drivers :-)

I think an input based sample there would be redundant to the `input_dump` one, but a comment in the code (in addition to the one in the sample documentation) may go a long way.

**Comment by ITachiLab** [comment]
I'd like to put my $0.02 here since I'm another person who trip over this.

I'm not entirely convinced that referencing another sample is sufficient, especially in this case. The `samples/subsys/input/input_dump` doesn't really give any clues how to connect `gpio-keys` with the input subsystem, so why is it linked on the first place? Take a look at that from the perspective of someone who analyses the code for the first time:

1. I'm looking at the basic button example, and I see it uses `gpio-keys` driver, nice.
2. I look at the button code, and see lots of low-level code. "Why? Shouldn't it be covered by the driver?"
3. I look at the [input_gpio_keys.c](https://github.com/zephyrproject-rtos/zephyr/blob/main/drivers/input/input_gpio_keys.c) and see exactly the same set of low-level code. "Why is it repeated in the application code then? How to avoid this?"
4. I look at the `input_dump` example, and I know even less than before because now I'm convinced I'm an idiot because I still don't get it.
5. Going through samples and documentation doesn't give any clues. Only after I had analysed the code of the `gpio-keys` driver thoroughly, I found out how to **really** make use of the driver.

I've spent definitely too much time on something that could took me 5 minutes if the button sample used the correct (updated) approach. Even @fabiobaltieri confirmed that those examples became musty:

> Yeah the two examples (blinky and button) are essentially "gpio output" and "gpio input", they were created before the respective subsystems (leds and input).

So, given that we have new subsystems which deal with those tasks much better, and have all those scary boilerplate handled nicely, couldn't we update those examples? I think the original suggestion made by @arifbalik should be revisited: either we make a full use of `gpio-keys` driver, or don't use it at all because the example in the current state is simply misleading: "Hey, I'm using `gpio-keys` driver... Nah, I'm kiddin', it's there but I'm trippin'".

**Comment by fabiobaltieri** [comment]
@ITachiLab yeah I agree with your assessment.

@kartben how about we rename `samples/basic/button` to something like `samples/basic/gpio_interrupt` and replace `samples/basic/button` with a sample that registers an input callback for the first `gpio-keys` instance and prints that? without necessarily using the input dump functionality

**Comment by hacst** [comment]
@fabiobaltieri that would be very useful. I am yet another user new to Zephyr that got very confused in just the ways @ITachiLab described.
