### ISSUE TITLE
wifi: hostap: PBKDF2 SHA1 (PSA/NS) takes longer increasing Wi-Fi connection time

### ISSUE THREAD

**Issue by fengming-ye** [zephyrproject-rtos/zephyr#79834]
**Describe the bug**
https://github.com/zephyrproject-rtos/hostap/commit/e84a82b4efd5de1c297486890c6f96ed18cbd850
is causing 2 seconds more to enable hostapd AP.

hostapd_derive_psk->pbkdf2_sha1 in previous code costs 0.7s but new code costs  more than 2s.

**To Reproduce**
1. Use `samples/net/wifi`, build and flash, e.g., nrf7002dk
2. Check Wi-Fi connection take it increases by 2s

**Expected behavior**
Wi-Fi connection time should be same before the commit.

**Impact**
Delayed Wi-Fi connection

**Logs and console output**
NA

**Environment (please complete the following information):**

 - OS:Linux
 - Toolchain: Zephyr SDK
 - Commit SHA or Version used: e84a82b4efd5de1c297486890c6f96ed18cbd850

**Additional context**
Same issue was found in NCS earlier with `NS` builds which is equivalent using PSA API. This seems to a regression as NCS 2.7.0 seems to work fine.

**Comment by fengming-ye** [comment]
@krish2718 @VivekUppunda Pls check it by crypto module test in test_sha1 and trace time.
Honestly I have no clue why this happens. So I'm raising bug to track this.

**Comment by krish2718** [comment]
> @krish2718 @VivekUppunda Pls check it by crypto module test in test_sha1 and trace time. Honestly I have no clue why this happens. So I'm raising bug to track this.

Thanks. We already have a bug internally as we see the same behaviour with PBKDF2_SHA1 in NCS, sometimes it takes ~13secs, will keep you posted.

**Comment by henrikbrixandersen** [comment]
Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

**Comment by krish2718** [comment]
> @krish2718 @VivekUppunda Pls check it by crypto module test in test_sha1 and trace time. Honestly I have no clue why this happens. So I'm raising bug to track this.

I was able to build the tests using:

1.  https://github.com/zephyrproject-rtos/zephyr/pull/78367/ 
2. build command: `west build -p -b nrf7002dk/nrf5340/cpuapp samples/net/wifi/ -- -DCONFIG_WIFI_NM_WPA_SUPPLICANT_CRYPTO_MBEDTLS_PSA=y -DCONFIG_WIFI_NM_WPA_SUPPLICANT_CRYPTO_ENTERPRISE=y -DCONFIG_NET_TCP_ISN_RFC6528=n`
3. Enable `WIFI_NM_WPA_SUPPLICANT_CRYPTO_TEST` manually. IMHO we should just make this Kconfig as configurable instead of hidden to avoid modifying source files.

But it fails with `supp_psa_crypto_init failed ret -148` i.e., `PSA_ERROR_INSUFFICIENT_ENTROPY`, as there is not entropy PSA driver for nRF boards yet. So, will continue looking at this in NCS and update if I find a fix.

**Comment by fengming-ye** [comment]
> 3. Enable `WIFI_NM_WPA_SUPPLICANT_CRYPTO_TEST` manually. IMHO we should just make this Kconfig as configurable instead of hidden to avoid modifying source files.
> 

It is an option that we don't want user to configure. So it will be hidden and only configurable by developer

**Comment by krish2718** [comment]
> > 3. Enable `WIFI_NM_WPA_SUPPLICANT_CRYPTO_TEST` manually. IMHO we should just make this Kconfig as configurable instead of hidden to avoid modifying source files.
> 
> It is an option that we don't want user to configure. So it will be hidden and only configurable by developer

IMHO, as it has `TEST` in the name we could make it configurable and if needed add a warning in Cmake, that is what we are doing with othe TEST options, hidden symbols are mainly for internal dependencies and not for hiding configurable options that needs a change.

**Comment by fengming-ye** [comment]
> > > 3. Enable `WIFI_NM_WPA_SUPPLICANT_CRYPTO_TEST` manually. IMHO we should just make this Kconfig as configurable instead of hidden to avoid modifying source files.
> > 
> > 
> > It is an option that we don't want user to configure. So it will be hidden and only configurable by developer
> 
> IMHO, as it has `TEST` in the name we could make it configurable and if needed add a warning in Cmake, that is what we are doing with othe TEST options, hidden symbols are mainly for internal dependencies and not for hiding configurable options that needs a change to the files to enable it.

Could you share one example? I can modify it later.

**Comment by krish2718** [comment]
> Please use our bug template when reporting bugs. You need to edit this issue to include the information requested in https://github.com/zephyrproject-rtos/zephyr/blob/main/.github/ISSUE_TEMPLATE/001_bug_report.md

Re-looking at this, this issue might be unrelated to the internal bug, without `MBEDTLS_PSA_ACCEL_ALG_PBKDF2_HMAC` HW accelerator MbedTLS uses `PSA_HAVE_SOFT_PBKDF2_HMAC` which is ~50% slower than non-PSA implementation (probably because of added separation due to PSA). So, unless we find a platform that support this accelerator, PSA would be slower than legacy but secure :).

**Comment by krish2718** [comment]
Let's close this for now, if we have more data we can re-open.
