### ISSUE TITLE
mem_slab/mslab_threadsafe testcase fails in CI sporadically

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/zephyr#8069]
```
***** Booting Zephyr OS v1.12.0-rc2-18-g4a9bfa1f6 *****
Running test suite mslab_threadsafe
===================================================================
starting test - test_mslab_threadsafe

    Assertion failed at /home/buildslave/src/github.com/zephyrproject-rtos/zephyr/tests/kernel/mem_slab/mslab_threadsafe/src/test_mslab_threadsafe.c:39: tmslab_api: (ret is true)
memory is not allocated
FAIL - test_mslab_threadsafe
===================================================================
===================================================================
PROJECT EXECUTION FAILED
```

**Comment by andyross** [comment]
This looks like a test bug to me.  Unless I'm insane, the operation of this test is:

0. Create a slab with 3 blocks in it
1. Spawn 4 threads that all run the same function, which is:
2. Allocate all 3 blocks
3. Free all three blocks

So if you schedule them simultaneously or otherwise change the scheduling order (*Hello!*) then you can end up in a situation where the threads legitimately hit a allocation failure, which the test treats as an "error".

There are other issues with this test too:

* It doesn't check the validity of the returned memory (should match the slab address, shouldn't be double-allocated, etc...)

* It doesn't test OOM situations (except accidentally in this bug)

Will come up with a quick fix for now.  Long term we should rework this to have better coverage
