### ISSUE TITLE
tests/kernel/common fails to build on xtensa / ESP32

### ISSUE THREAD

**Issue by inakypg** [zephyrproject-rtos/zephyr#8093]
commit 43553da9b2bb9e537185695899fb5184c3b17ebe

Toolchain: ZEPHYR_GCC_VARIANT=espressif

```
...
[ 63%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/pinmux/pinmux_esp32.c.obj
[ 64%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/timer/sys_clock_init.c.obj
zephyr.git/tests/kernel/common/src/intmath.c:50:30: error: enumerator value for '__build_assert37' is not an integer constant
zephyr.git/tests/kernel/common/src/intmath.c:52:30: error: enumerator value for '__build_assert41' is not an integer constant
 ROLLOVER_CHECK(int, 2147483647, -2147483648);
                              ^
```

**Comment by andyross** [comment]
What's happening is that the we have a test where on GCC 4.x+, we use the C99 _Static_assert() feature instead of our own preprocessor hack.  But on ESP32, something in the toolchain headers is redefining __STDC__ to say that it's C90, not C99 (I checked: the compiler emits C99 by deafault, so we don't use the builtin.

And of course our own macro is bitrotten and broken and produces that error.
