### ISSUE TITLE
CONFIG_SPI_FLASH_W25QXXDV_MAX_DATA_LEN doesn't work in proj.conf

### ISSUE THREAD

**Issue by mazhenke** [zephyrproject-rtos/zephyr#8327]
In Kconfig.w25qxxdv file:

```
config SPI_FLASH_W25QXXDV_MAX_DATA_LEN
	int
	range 1 256
	default 256
	help
	  Maximum transmit or receive data length in one user data frame.

```

I want to change the CONFIG_SPI_FLASH_W25QXXDV_MAX_DATA_LEN value in my project, so I add
CONFIG_SPI_FLASH_W25QXXDV_MAX_DATA_LEN=32 in my proj.conf
but the CONFIG_SPI_FLASH_W25QXXDV_MAX_DATA_LEN in 
zephyr/include/generated/autoconf.h
is still 256, and I got the following cmake warning:

`warning: SPI_FLASH_W25QXXDV_MAX_DATA_LEN (defined at drivers/flash/Kconfig.w25qxxdv:77) was assigned the value "32" but got the value "256" -- check dependencies`

**Comment by ulfalizer** [comment]
@mazen-neifer 
`SPI_FLASH_W25QXXDV_MAX_DATA_LEN` doesn't have a prompt, so it can't be set directly from a `prj.conf` file.

See http://docs.zephyrproject.org/porting/board_porting.html#setting-configuration-values for an overview of how to set symbols with and without prompts.

Currently a `Kconfig.defconfig` file would be needed to set the value, but only boards and SoCs can have `Kconfig.defconfig`, afaik. Maybe it's supposed to be a fixed board setting.

@tbursztyka touched this code recently. He might have some comments.

**Comment by tbursztyka** [comment]
Perhaps it can be removed (and code modified accordingly). 
When I switched that driver to new spi API I got rid of this:
 struct spi_flash_data {
        struct device *spi;
-       u8_t buf[CONFIG_SPI_FLASH_W25QXXDV_MAX_DATA_LEN +
-                   W25QXXDV_LEN_CMD_ADDRESS];
+       struct spi_config spi_cfg;

It looks like this length was only about internal buffer length, which is now useless due to new SPI API.
I'll verify that in the datasheet.

**Comment by tbursztyka** [comment]
yes it's a left-over. I'll remove that
