### ISSUE TITLE
bluetooth: request the capability to change gap device name programmatically 

### ISSUE THREAD

**Issue by jli157** [zephyrproject-rtos/zephyr#8357]
The device name of a bluetooth device is currently configured by the macro `CONFIG_BT_DEVICE_NAME`, which presents the device from being named by the device name data stored in its internal flash memory or OTP memory.  So, an API shall be added to support changing device name programmatically.

**Comment by carlescufi** [comment]
I am all in favor of this. I do not see why we couldn't allow this, barring current technical limitations on the way we handle advertising data.

**Comment by jhedberg** [comment]
You can already now do this for the name that's present in advertising data, however for the name that's exposed through the GAP GATT service we'd need to add a new API. It should be fairly simple to do, however since it's currently just `static const char *gap_name = CONFIG_BT_DEVICE_NAME;` in `subsys/bluetooth/host/gatt.c`. I.e. we need a function to assign some other string to it.

**Comment by Vudentz** [comment]
I guess we would also need to persist it as well and perhaps have some means to notify about name changes so it can update adv data.
