### ISSUE TITLE
Network stack cleanup: connection

### ISSUE THREAD

**Issue by tbursztyka** [zephyrproject-rtos/zephyr#8722]
connection.c needs cleanup:
 . revise the connection cache logic: use sys_slist instead of looping on an array. See what has been done in subsys/net/l2/ethernet/arp.c

declutter using #8723 rules

**Comment by pfalcon** [comment]
I'd like to propose simplification of connection callback functions, let me crossreference it from here: https://github.com/zephyrproject-rtos/zephyr/issues/8723#issuecomment-415040335

**Comment by pfalcon** [comment]
> @pfalcon You are taking things out of the context and making false conclusions.

The point is that there's not enough context, guidelines, and requirements are provided, so one literally can only try to make conclusions from the sparse data provided, which can easily turn out to be false...

**Comment by tbursztyka** [comment]
I think we all know what needs to be done here, no need to take by hand whoever is going to do that work.

**Comment by pfalcon** [comment]
> I think we all know what needs to be done here, no need to take by hand whoever is going to do that work.

So let me clarify: I don't know, so that's why I didn't participate in it. Actually, I had issues with reviewing patches claiming to be cleanups/fixes based on this and related tickets - if it's known exactly *what* should be done and *why*, it's hard to assess whether a particular change is improvement, regression, or just sideways work.

Anyway, just a friendly feedback.
