### ISSUE TITLE
[Coverity CID :187070] Control flow issues in /drivers/bluetooth/hci/spi.c

### ISSUE THREAD

**Issue by mandarcthorat1** [zephyrproject-rtos/zephyr#8996]
Static code scan issues seen in File: /drivers/bluetooth/hci/spi.c
 Category: Control flow issues
 Function: bt_spi_rx_thread
 Component: Bluetooth
 CID: 187070
 Please fix or provide comments to square it off in coverity in the link: https://scan9.coverity.com/reports.htm#v32951/p12996

**Comment by jhedberg** [comment]
I'm not familiar enough with this code, so assigning to those who hopefully are. @cpriouzeau I'd have assigned it to you but seems you're not part of the correct github group?). It looks to me like this code was introduced by commit 7b02e6dc551cba9d30b29b9b6ee5ddc61ae5471d from PR #7160

**Comment by erwango** [comment]
@mandarcthorat1 

'Issue' is true only if CONFIG_BT_SPI_BLUENRG is unset, which makes do while condition always false.
In this case, 'continue' gets us exiting the do while loop, but since we're in a while(true) we'll enter it again at the next while(true) iteration, which is fine.
Though, we don't want to use breaks statement because it will modify the behavior when CONFIG_BT_SPI_BLUENRG is set, which is as expected.

I propose to keep code as is and discard this issue, what I've not been able to do.
Would you be able to do it?

**Comment by nashif** [comment]
closing based on comment from @erwango
